cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/cleanup/main.go
cmd/migrate/main.go
cmd/server/main.go
go.mod
go.sum

We can merge as-is, or wait until https://github.com/google/exposure-notifications-server/pull/742 and then I'll use that to remove some of the duplication around listening for cleanup signals.

Gracefully stop and cleanup servers

---

pkg/sms/noop.go
pkg/sms/sms.go
pkg/sms/twilio.go
pkg/sms/twilio_test.go

This doesn't add any envconfig because we're going to want this to be multitenant and stored in the database.
@mikehelmick do we want to provision a Twilio account so we can inject the test credentials into the build for CI?

Add SMS interfaces and Twilio implementation

---

cmd/server/assets/home.html
pkg/api/api.go
pkg/controller/home/home.go
pkg/controller/issueapi/issue.go
pkg/database/database.go
pkg/database/migrations.go
pkg/database/sms_config.go
pkg/database/sms_config_test.go
pkg/database/vercode.go
pkg/database/vercode_test.go
pkg/sms/noop.go
pkg/sms/sms.go
pkg/sms/twilio.go
pkg/sms/twilio_test.go

Add more SMS functionality

---

pkg/database/authorized_app.go
pkg/database/migrations.go

* drop unique authorized app by name index so different realms can use same name
* change that to a composide realm+name index so a realm doesn't use the same name twice.
Part of the fun of #104

Fix up indexes after MT upgrade.

---

scripts/presubmit.sh

presubmit.sh script already has errexit set, so the script exits right away when the exit code of a command is non-zero. This makes checking 0 afterwards being noop, thus the error message would never get hit. Fixing this so that the error messages are surfaced

Fix presubmit test bug to surface error message better

---

.dockerignore
Dockerfile

Updates our dockerfile
- Move to Alpine - current image has less vulnerabilities than ubuntu. Less of an issue since we aren't running on ubuntu, but #shrugs
- Add a docker ignore to prevent adding files we don't want in our images. Less of an issue because we are using seperate run container, but a best practice.
- Split out env layers for easier reading
- Add goproxy env arg to speed build time by grabbing from secure proxy server.

Docker updates

---

cloudbuild.yaml

First step of cloud build automation is to set up trigger on commits to `main` to autobuild to gcr. Decided to go this route instead of wrapping the existing build script because I didn't want to build an image with gcloud, git and bash all in it. Downsides to this are these builds happen in serial, but not a big deal.

Initial cloud build for auto building of all images

---

pkg/controller/certapi/certificate.go

Fixes #186
```release-note
NONE
```

Certificate issue API doesn't need an active session.

---

pkg/render/html.go
pkg/render/json.go
pkg/render/render.go

This fixes an error where a true crash (e.g. panic) leaves the buffer filled. Then, next time it's used in the pool, it has partial data and renders weird JSON/HTML.
This also updates our templates to always use the "zero" value when something does not exist.
```release-note
Always reset render buffer before use.
```

Always reset the buffer before rendering

---

Dockerfile
cloudbuild.yaml

* Reverts docker file to ubuntu for building, it's faster
* Sets build server to multi cpu for building in parallel faster
* Parallelizes steps
* Adds timeouts, mainly specified in case there are weird network delays. Example build in screenshot
```release-note
Switches build environment for Dockerfile back to ubuntu from Alpine.
```

Fix cloudbuild and Docker optimizations

---

terraform/database.tf
terraform/variables.tf

Fixes GH-194
```release-note
Allow customizing database backup location (defaults unchanged)
```

Allow customizing database backup location

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/cleanup/main.go
cmd/server/main.go
go.mod
pkg/controller/healthz.go
pkg/database/database.go
pkg/render/render.go

Some progress towards #180
* Adds a /healthz handler that can be hit by probers. if /healthz?service=database we can also find out if the database connection is working.
* This is useful for lightweight health checking
```release-note
Adds a /healthz to all server binaries for healthchecking.
```

Add a /healthz

---

pkg/config/admin_server_config.go
pkg/config/issue.go
pkg/config/server_config.go
pkg/controller/certapi/certapi.go
pkg/controller/cleanup/cleanup.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/issueapi.go

* Just reading through code, fixing typos
```release-note
Minor spelling fixes
Environment variable 'COLISSION_RETRY_COUNT' renamed 'COLLISION_RETRY_COUNT'
Server config field  'SESSION_DUATION' to 'SESSION_DURATION'
```

Spelling Nits

---

go.mod
go.sum
pkg/ratelimit/config.go

Refs GH-209
I don't want to change the default value, but we can override this in our configurations after we build and deploy a new version if this continues to be an issue.
```release-note
Allow configuring the rate limiter to succeed on backend connection failures (default unchanged)
```
/assign @gurayAlsac 
/cc @mikehelmick

Allow configuring the rate limiter to fail open

---

README.md
pkg/controller/issueapi/issue.go
pkg/render/html.go
pkg/render/json.go
pkg/render/render.go

This reduces the number of error codes that clients need to check against to:
- `400` - search for `"errors"` key in JSON response
- `401` - unauthorized, usually with no `"errors"`, but clients can try to read the JSON body to see if there's additional information (it may be empty)
- `404` - routing error (app coding error)
- `405` - wrong HTTP method (app coding error)
- `429` - rate limited, check headers `X-Retry-After` to determine when to retry
- `5xx` - internal server error
```release-note
Standardize known HTTP response codes on 400, 401, 404, 405, 429, and 5xx.
```

Unify on BadRequest

---

pkg/api/api.go
pkg/controller/issueapi/issue.go
pkg/database/vercode.go
pkg/otp/code.go
pkg/otp/code_test.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/109
* Include the Database ID for the issued verification code. This will be later used in a new API to check the claimed/unclaimed status of the code.
* Are there any security concerns with using this DB handle / do we need to create an artificial GUID key for this purpose. The DB key is an auto-increment uint which may allow for scraping or counting; However the user must be authenticated to retrieve code status.
```release-note
Include ID in the issue VerificationCode response
```

Emit ID for verification code

---

pkg/api/api.go
pkg/controller/certapi/certificate.go
pkg/controller/verifyapi/verify.go
pkg/database/token.go
pkg/render/render.go

part of #134 
```release-note
Verification and certificate APIs have well defined error codes for localization on the client side.
```

add well defined errorCode strings in responses

---

Dockerfile
cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/server/main.go
go.mod
go.sum
pkg/config/admin_server_config.go

- Download go modules in dedicated step for faster local builds
- Update go-limiter to fix a redis TTL issue
- Update adminapi server config to use shared ratelimit config
- Rate limit by X-Forwarded-For, ensure limiting is applied in correct order
```release-note
Rate limit by x-forwarded-for headers to get the real client IP
The adminapi now uses `RATE_LIMIT_TOKENS` instead of `RATE_LIMIT` to define the limits
IP addresses are hashed before stored in redis for limiting
Each service has its own key namespace in the rate limiter to avoid clobbering
```

Fix rate limiting

---

pkg/render/render.go

Adds ability to inject template functions - the only function is `strings.Join` for now.
```release-note
NONE
```
/assign @icco

Add template functions stub

---

cmd/add-realm/main.go
cmd/add-users/main.go
cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/cleanup/main.go
cmd/migrate/main.go
cmd/server/main.go
pkg/controller/healthz.go
pkg/database/database.go
pkg/database/database_util.go
tools/seed/main.go

The previous "Open" command would parse the configuration and then establish the connection. This separates into two separate invocations. This is important because retrying Open() was actually unsafe in local development because config parsing mutated state. By moving config parsing to be separate, we can parse once, then call Open() as many times as we'd like.
```release-note
NONE
```

Separate database config loading from connection opening

---

terraform/database.tf

Fixes GH-228
```release-note
Set encryption keys in initial Terraform migration
```

Set encryption keys in initial Terraform migration

---

cmd/adminapi/main.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/234
* Fixes the handler for the checkcodestatus endpoint
* This is reorganized better in https://github.com/google/exposure-notifications-verification-server/pull/227 but I've pulled this bit out of it
```release-note
Fixes the handler for the checkcodestatus endpoint
```

Fix the handler for checkcodestatus

---

pkg/database/migrations.go

Fixes GH-213
```release-note
Allow migrations to succeed in the case a "default" realm already exists
```

Allow migrations to pass if a default realm already exists

---

go.mod
pkg/jsonclient/client.go

https://github.com/google/exposure-notifications-verification-server/issues/180
* Adds trace headers to requests originating with the jsonclient
```release-note
NONE
```

Add tracing to jsonclient

---

cmd/server/assets/header.html
cmd/server/assets/realm.html
pkg/config/admin_server_config.go
pkg/config/issue.go
pkg/config/server_config.go
pkg/controller/home/home.go
pkg/controller/issueapi/issue.go
pkg/controller/realmadmin/save.go
pkg/database/duration.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_test.go
pkg/database/token.go
pkg/database/token_test.go
pkg/database/vercode.go
pkg/database/vercode_test.go
pkg/otp/code.go
pkg/otp/code_test.go

Fixes #138
Fixes #143
Fixes #213 
* add region designator for a realm, i.e. `US-WA`
* Generate both 'short' and 'long' codes
* short codes have shorter timeouts and are meant to read over the phone, long codes only over SMS
* long codes are alphamumeric a-v,0-9
* Option to use deep links for codes in SMS
* for example `ens://v?r=US-WA&c=ABCD1234`
* add all of these settings into the realm setting page
```release-note
Short and long verification codes issued at the same time. Long codes can be valid for up to 24 hours. Option to generate a SMS 'deeplink' to make it so the code doesn't need to be copied / retyped. Settings screen for realm settings.
```

SMS Deep links and settings

---

cmd/server/assets/login.html
cmd/server/main.go
pkg/controller/login/controller.go
pkg/controller/login/login.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/141
* Create an alternative login page
* Will Unblock us from using the Identity Platform login w/ multi-factor
* At the moment it's overly verbose with an alert bar at the top. We'll make it pretty later.
* Will someday replace our index.html login
Note: FirebaseUI does not support multi-factor auth. That's a shame because it does all the html for us and it is pretty.
```release-note
Create a new login page without firebaseUI
```

Alternative sign-in page using Identity Platform

---

pkg/controller/verifyapi/verify.go
pkg/jsonclient/client.go
pkg/render/html.go
pkg/render/json.go

* set correct content-type return header
* one case where error was returning 200
*
```release-note
Proper content-type set on all HTTP responses.
```

fix content-type on return and a stray 200 code

---

pkg/database/token.go
pkg/database/vercode.go
pkg/otp/code.go
pkg/otp/code_test.go

* Return plain text verification codes (short/long) to controller instead of hmac version
* On expiration check both plaintext and hmac version when matching for expiration date
```release-note
BUG FIX - check expiration correctly after verification code HMAC upgrade.
```

Fix code display in UI and verification checks against HMAC values.

---

cmd/server/assets/login/verifyemail.html
cmd/server/main.go
pkg/controller/login/verifyemail.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/141
* Creates a new page for email verification
Next: 
1)  middleware to require verified email
2) knock out existing index login
```release-note
Page for email verification
```

Create an email verification page

---

pkg/controller/certapi/certapi.go
pkg/controller/certapi/certificate.go
pkg/controller/verifyapi/verify.go
pkg/gcpkms/gcpkms.go
pkg/keys/keys.go

Refactor before #149 
* Rename signer package to keys
```release-note
Potentially breaking: Renamed pkg/signer to pkg/keys and renamed the interface from KeyManager to Manager
```

rename interface from signer to keys

---

cmd/server/assets/login/verifyemail.html
pkg/controller/middleware/auth.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/141
* Requires that user have verified email address
* if not, redirects to verification page
```release-note
Require all users have verified email address to log-in
```

Require user emails be verified to authenticate

---

terraform/variables.tf
terraform/versions.tf

* terraform module now requires Terraform 0.13
```release-note
The terraform module now requires Terraform 0.13
```

upgrade terraform module to tf 0.13

---

pkg/cache/cacher.go
pkg/cache/cacher_test.go
pkg/cache/in_memory.go
pkg/cache/in_memory_test.go
pkg/cache/noop.go
pkg/cache/redis.go
pkg/cache/redis_test.go
pkg/database/database.go
pkg/database/sms_config.go

Part of the stats work, this adds a new cacher interface which can use an in-memory or redis-based implementation. Fields have to be public per the laws of the reflection, although I'm using gob, so we could implement custom marshalers if we really need private fields to be in the cached object.
I didn't switch to Redis or make any of this configurable because I'm trying to keep the PR small and do it piece-meal. 
```release-note
NONE
```

Add generic cache interfaces

---

cmd/server/assets/login/login.html

Issue https://github.com/google/exposure-notifications-verification-server/issues/141
* Accepts SMS as the second factor for auth
* Assumes (badly) that there is only one second factor
* uses window.alert for input which is not ideal for now
TODO:
* Allow other auth factors
* Present a choice for auth factors
* Replace alert with real html 
```release-note
Accept SMS codes for 2 factor auth
```

Accept SMS authentication

---

cmd/server/main.go
pkg/cache/cacher.go
pkg/cache/cacher_test.go
pkg/cache/config.go
pkg/cache/in_memory.go
pkg/cache/noop.go
pkg/cache/redis.go
pkg/controller/apikey/apikey.go
pkg/controller/apikey/show.go
pkg/controller/login/controller.go
pkg/controller/user/show.go
pkg/controller/user/user.go
pkg/database/config.go
pkg/database/database.go
pkg/database/database_util.go
pkg/database/realm.go
pkg/database/sms_config.go
pkg/ratelimit/limitware/middleware.go

Switch to JSON encoding for the cacher. Gob is faster, but misconfigurations turn into runtime errors. It also decouples the cacher from the database.
This also introduces a KeyFunc type on the cacher to mutate keys before they are stored (e.g. to obfuscate or encrypt them), and fixes the SHA calculations on the rate limiter keys.
```release-note
Switch to JSON encoding for cacher, decouple cacher from database
```

Switch to JSON encoding for cacher, decouple cacher from db

---

terraform/keys.tf
terraform/variables.tf

Make KMS key ring name configurable
```release-note
Make KMS key ring name configurable in Terraform
```

Make KMS key ring name configurable

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_server.tf

```release-note
Sets cloud run request timeout for three main API services to 25s.
```

Set request timeout for services behind a GCLB to 25s

---

go.mod
go.sum
pkg/database/database.go

* Update pinned ENS version to 0.5.0 - preparation for next release
```release-note
Changed dependency on exposure-notifications-sever from v0.4.0 to v0.5.0
```

pin verification server to exposure notifications v0.5.0 release

---

pkg/controller/verifyapi/verify.go

Fixes #317
```release-note
/api/verify returns correct error codes now code_expired/code_invalid instead of token_invalid/token_expired
```

Correct error codes

---

pkg/controller/codestatus/logic.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/341
* Allow both users and authorized apps to check code status
```release-note
Allow authorized apps to check code status
```

Allow auth app to check code status

---

cmd/server/assets/codestatus/index.html
cmd/server/assets/home.html
pkg/controller/codestatus/index.go
pkg/controller/codestatus/show.go
pkg/database/vercode.go

Render inline codestatus responses

---

go.mod
go.sum
pkg/ratelimit/config.go
pkg/ratelimit/limitware/middleware.go

Fixes #266
* Change redigo to opencensus/redigo
* Change redisstore to instrumented redisstore
```release-note
Add redis opencensus metrics to the verification server, this will enable to monitor problems with redis connections itself.
```

Add redis opencensus metrics to the server

---

cmd/server/assets/codestatus/index.html

* Change the label for uuid input to 'UUID' instead of xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
* Enforce GUID-valid characters and dashes vs javascript as the user types

Use js to groom uuid formatting

---

cmd/server/assets/codestatus/show.html
pkg/controller/codestatus/show.go

* Adds the test type field
* Adds information about either the
* Issuing User Name
OR
* Issuing App Name
```release-note
Add test type and issuer to show code page 
```

Expand the show code page to include more fields

---

cmd/apiserver/main.go
pkg/config/api_server_config.go
pkg/config/certificate_signing_config.go
pkg/config/server_config.go
pkg/config/token_signing_config.go
pkg/controller/certapi/certapi.go
pkg/controller/certapi/certificate.go
pkg/controller/certapi/signers.go
pkg/controller/realmkeys/render.go
pkg/controller/verifyapi/verify.go
pkg/database/config.go
terraform/services.tf

```release-note
Create separate key manager instances instead of using a shared pool. This changes the configuration to require a prefix on the key managers (e.g. TOKEN_KEY_MANAGER and CERTIFICATE_KEY_MANAGER) if you are overriding the defaults.
```

Create separate key manager instances for certs, tokens, and db

---

cmd/adminapi/main.go
pkg/api/api.go
pkg/controller/codestatus/expire.go
pkg/database/vercode.go
pkg/database/vercode_test.go

* Add the expire code API to allow users to invalidate a code (set expiry time to now)
* Spinning the logic out of: https://github.com/google/exposure-notifications-verification-server/pull/373 so I can focus on UX separately

Add code expire endpoint

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/server/main.go
pkg/controller/middleware/hsts.go

Fixes GH-381
```release-note
Set HSTS headers in production service
```

Add middleware for setting HSTS headers

---

pkg/cache/config.go
pkg/cache/redis.go
pkg/ratelimit/config.go
pkg/redis/config.go
terraform/main.tf
terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_server.tf
terraform/services.tf

Centralize our Redis configuration and set a 1m idle timeout on all Redis connections
```release-note
Set a 1m idle timeout on all Redis connections. `REDIS_HOST` and `REDIS_PORT` are now prefixed based on their scope (e.g. `CACHE_REDIS_HOST` and `RATE_LIMIT_REDIS_HOST`). This enables using a different Redis cluster or configuration for rate limiting vs caching.
```
/assign @icco

Set 1m idle timeout on Redis connections

---

cmd/server/assets/realmkeys.html
cmd/server/main.go
pkg/controller/realmkeys/destroy.go
pkg/controller/realmkeys/realmkeys.go
pkg/controller/realmkeys/render.go
pkg/database/realm.go

Fixes GH-349
Part of https://github.com/google/exposure-notifications-server/issues/913. 
```release-note
Add support for destroying signing key versions
```

Add support for destroying signing key versions

---

pkg/config/api_server_config.go
pkg/config/token_signing_config.go
pkg/controller/certapi/certapi.go
pkg/controller/certapi/certificate.go
pkg/controller/verifyapi/verify.go

Fixes #94
* Allow the token signing key to be rotated by the server operator. This is totally independent from the certificate signing keys
```release-note
Verification server operators can rotate their token signing key. `TOKEN_SIGNING_KEY` and `TOKEN_SIGNING_KEY_ID` are now array based env vars. They must be the same length. The first items in the lists represents the active key/kid and the remaining entries are allowed to validate.
```

implement token signing key rotation

---

pkg/config/admin_server_config.go
pkg/config/api_server_config.go
pkg/config/server_config.go

Fixes GH-400
```release-note
Fix redis cache environment variable
```

Do not double-prefix cache

---

pkg/database/cleanup.go

Fixes GH-401
```release-note
Fix SQL error in cleanup logic
```

Fix cleanup failure logic

---

terraform/services.tf

removes unused one, and sets another (although this is currently the default value)
```release-note
NONE
```

fix db connection var

---

pkg/database/config.go
pkg/database/database.go
pkg/database/database_util.go
terraform/services.tf

Per https://golang.org/src/database/sql/sql.go?s=24445:25000#L871, the
idle conn timeout is only observed if the max conn timeout is also set.
```release-note
Allow configuring database max lifetime idle timeout
```

Configure max lifetime idle timeout too

---

cmd/adminapi/main.go
cmd/server/assets/codestatus/_codescripts.html
cmd/server/assets/codestatus/show.html
cmd/server/main.go
pkg/controller/codestatus/expire.go
pkg/controller/codestatus/show.go

* Adds a button to an invalidate endpoint that sets the code to expire now
* Alternative to ajax https://github.com/google/exposure-notifications-verification-server/pull/373 
* @sethvargo may have suggestions to make this look nicer
```release-note
Allow users to expire a code
```

Use a form (not ajax) for invalidating codes

---

pkg/api/api.go
pkg/clients/apis.go
pkg/controller/issueapi/issue.go

Not all browsers send timezone offsets as integers.
Updates #63
* Fix tzoffset parsing by changing the type to float, and passing it correctly around.
```release-note
NONE
```

pkg/controller/issueapi: fix json parsing of tzOffset

---

terraform-e2e/README.md
terraform-e2e/main.tf

This new module contains some random prefix/suffix for GCP resources that can not be deleted by terraform, so that the same GCP project can be used for smoke testing terraform deployment repeatedly
/assign @sethvargo 
/cc @yegle

Add terraform module for smoke test terraform configuration

---

.gitignore
cloudbuild.yaml
cmd/e2e-runner/e2e.go
cmd/e2e-runner/main.go
pkg/config/e2e_runner_server_config.go
scripts/build
scripts/deploy
scripts/promote
terraform/service_e2e_runner.tf
terraform/services.tf

This commit refactored the existing e2e-test CLI into a web service.
It currently provides /default and /revise handlers, maps to the
`-revise=false` and `-revise=true` flag of the original CLI.
This service is currently guarded by an IAM policy to avoid hammering
the API servers repeatedly.
Fixes #265
*Release Note**
```release-note
A simple e2e test is added to test APIs provided by the verification server and the key server.
```

Create e2e-runner service.

---

terraform/services.tf

This allows `terraform apply` to proceed without error.
```release-note
NONE
```

Add default envvar values to e2e-runner service

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_server.tf

force_override isn't persisted in the spec

---

cmd/server/assets/admin/new.html
cmd/server/assets/admin/realms.html
cmd/server/assets/header.html
cmd/server/main.go
pkg/controller/admin/admin.go
pkg/controller/admin/create_realm.go
pkg/controller/admin/index.go
pkg/controller/user/create.go
pkg/database/realm.go
pkg/database/user.go

* System admins can create new realms (very basic)
* clear user from cache when realms change - otherwise you can't select the new realm until record expires.
```release-note
System admin page to create realms from the UI instead of command line tools.
```

add sys admin screen for creating realms

---

cmd/server/assets/realm.html
cmd/server/main.go
pkg/controller/realmadmin/express.go
pkg/controller/realmadmin/index.go
pkg/controller/realmadmin/save.go
pkg/database/migrations.go
pkg/database/realm.go

* Simplified settings for ENX
```release-note
Realm settings to enable ENX (EN Express)
```

settings for enx

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_server.tf
terraform/variables.tf

This allows us to assign multiple domains to a single service.
```release-note
BREAKING CHANGE! `*_custom_domain` are now `*_custom_domains` in Terraform and the type has changed from `string` to `set(string)` to support specifying multiple domains mapped to a single service.
```

Support multiple custom domains

---

pkg/api/api.go

Semi-revert of GH-239. This adds two "error" fields to our responses, but it's the best interim solution I can think of.
```release-note
Temporarily return `error_code` and `errorCode` in API JSON responses for backwards compatibility. `error_code` will be removed in a future version.
```

Restore the old API key code

---

docs/api.md

Fixes #452
```release-note
API documentation corrected casing in JSON examples.
```

correct casing in json examples

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_cleanup.tf
terraform/service_server.tf

Fixes #
Container images are not in sync with changes in builder scripts
Container images in terraform scripts are pointing towards an older path which was recently changed in cloud builders.
Old Path : gcr.io/${var.project}/github.com/google/exposure-notifications-verification-server/cmd/SERVICE-NAME:initial
New Path : Old Path : gcr.io/${var.project}/github.com/google/exposure-notifications-verification-server/SERVICE-NAME:initial

Fix intial container images path in terraform services

---

pkg/database/migrations.go

Apparently this turned into a panic instead of a silent failure in a recent version.
```release-note
Fix migration logging
```
/cc @chaodaiG

Ensure Debugw always has the right number of fields

---

cmd/server/assets/codestatus/show.html
pkg/controller/codestatus/show.go
pkg/database/vercode.go

* Long code expiration displayed in code check UI
```release-note
When checking code status via UUID, the long expiry time/countdown will be shown.
```

show long code expiry in UI on code check

---

cmd/adminapi/main.go
cmd/apiserver/main.go

* Moves /api requests into a subrouter
* Makes /health not require an API key
```release-note
/health no longer requires an API key to call
```

Move API requests to a sub router

---

cmd/adminapi/main.go

Fixes a bug in https://github.com/google/exposure-notifications-verification-server/pull/465
```release-note
NONE
```

Copy pasta error

---

docs/production.md
pkg/config/server_config.go
pkg/database/authorized_app.go
pkg/database/config.go
pkg/database/database.go
pkg/database/database_util.go
pkg/database/migrations.go
pkg/database/token.go
pkg/database/token_test.go
pkg/database/vercode.go

This isn't 100% complete, but it's about 95% toward GH-429. I'd eventually like to write a utility in `tools/` that generates the secrets and puts them in Secret Manager so a human never sees them, but didn't want to muddle that with the actual docs/implementation.
```release-note
Add support for rotating HMAC and encryption keys
```

Allow rotating most secrets

---

docs/api.md

Fixes #469 
* Add API docs for admin APIs
*
*
```release-note
Added documentation for ADMIN APIs
```

add admin API to api docs

---

terraform/alerting/notifications.tf
terraform/alerting/probers.tf
terraform/alerting/variables.tf

Begins #461
* Adds a new terraform module you can include to get alerts
Example:
```
module "en-alerting" {
source  = "github.com/google/exposure-notifications-verification-server/terraform/alerting"
project = "example"
adminapi-host  = "adminapi.example.org"
apiserver-host = "apiserver.example.org"
server-host    = "example.org"
notification-email = "example+alert@google.com"
}
```
```release-note
There is now an alerting module you can initialize to get alerts for server health.
```

Add existing alerts to terraform

---

docs/api.md
pkg/api/api.go

This adds a padding field to all requests and responses. We don't use it anywhere yet, but it will allow clients to send us padded responses for network obfuscation, and we can gradually start sending our own padding back in responses that the client should ignore.
```release-note
Add `padding` fields to all API requests and responses
```

Add padding fields to API

---

docs/production.md

Fixes GH-478
```release-note
Document users, realms admins, and sys admins
```

Document users and admin configuration

---

cmd/e2e-runner/main.go

Log lines like this indicating our probing frequency is fast enough to
cause duplications:
```
error trying to create a new Admin API Key: pq: duplicate key value
violates unique constraint "realm_apikey_name"
```
```release-note
NONE
```

Use crypto/rand to generate random suffixes in API keys.

---

pkg/database/database.go

Tracing gorm's code is... challenging, but `Callback()` creates a clone. We're shadowing it, so maybe we have to create a new one each time?
```release-note
NONE
```

Don't save the returned callback struct

---

pkg/api/api.go

I'm open to what arbitrary upper bound we put
```release-note
Include random padding bytes in API responses. Clients should not process these bytes.
```
/hold to make sure it won't break clients

Add random padding to responses

---

builders/build.yaml
go.mod

Fixes GH-441
```release-note
Upgrade to Go 1.15.1
```

Upgrade to Go 1.15.1

---

pkg/jsonclient/client.go
tools/e2e-test/main.go

Reverts google/exposure-notifications-verification-server#495
These logs provide feedback to the UI tools.

Revert "Remove some unnecessary logs"

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/server/main.go
pkg/controller/middleware/debug.go

If the request sends an x-debug header with any value, the response headers will be populated with the build ID and tag.
```release-note
Return build information in response headers if `X-Debug` is supplied as a request header
```
/cc @icco

Add middleware for debug headers

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/server/main.go
docs/development.md
docs/production.md
pkg/cache/cacher.go
pkg/cache/config.go
terraform/redis.tf
terraform/services.tf

Fixes GH-429 (most of it is done, this was the last remaining bit)
```release-note
Use HMAC instead of hashes in cacher keys
```

HMAC instead of hash keys in the cacher

---

terraform/build.tf

Terraform deprecation
```release-note
Rename Terraform `bucket_policy_only` to `uniform_bucket_level_access` to handle depreaction
```

Rename bucket_policy_only -> uniform_bucket_level_access

---

pkg/database/database.go
pkg/database/database_util.go

This should fix the sporadic data race issues we see in CI, at the expense of increasing the test suite by ~3s.
```release-note
NONE
```

Acquire a lock before registering callbacks

---

.gitignore
scripts/e2e-test.sh
scripts/terraform.sh
terraform-e2e/README.md
terraform-e2e/main.tf
terraform/database.tf

Production code change
- Tag "migrate" image as "initial` just like the other images
- output `db_inst_name`
Test related changes:
- Add  a script for terraform smoke test
- Bring terraform-e2e module closer to the module used in prod
Note for code reviewer:
This PR overlaps a lot with it's peer PR in key server https://github.com/google/exposure-notifications-server/pull/948
/hold
Let's resolve https://github.com/google/exposure-notifications-server/pull/948 first

Terraform smoke test

---

terraform/alerting/dashboards/e2e.yaml
terraform/alerting/dashboards/verification-server.yaml
terraform/alerting/monitoring.tf
terraform/main.tf

NOTE: the chart on metric
custom.googleapis.com/opencensus/en-verification-server/ratelimit/limitware/rate_limited_count
was removed as it's no longer exported by the code.
The API requires JSON config but writing multi-line strings in JSON is PITA. I've decided to write it in YAML which is more compact and easier to write multi-line queries.
Related issue: #460 
```release-note
NONE
```

Add dashboards to be managed by Terraform.

---

terraform/alerting/dashboards/e2e.yaml
terraform/alerting/dashboards/verification-server.yaml

* Fixes https://github.com/hashicorp/terraform-provider-google/issues/7242 from wanting to recreate the dashboards every time.
```release-note
NONE
```

Change to columns strings for dashboards

---

cmd/server/assets/home.html
cmd/server/assets/realm.html
docs/api.md
pkg/api/api.go
pkg/controller/issueapi/issue.go
pkg/controller/realmadmin/save.go
pkg/database/migrations.go
pkg/database/realm.go

Fixes GH-519
This adds a new realm-specific configuration for requiring a date. The default is false and backfilled as false.
```release-note
Add realm configuration for requiring a date when generating a verification code. This includes a new `missing_date` error code in the issue API.
```

Add realm configuration for requiring dates

---

pkg/controller/realmkeys/render.go

This fixes a bug where trimSpace gets passed nil and the template fails to render
```release-note
Fix a rendering bug when retrieving a public key fails
```

Populate cert as empty string on error

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/server/main.go
docs/development.md
docs/production.md
pkg/ratelimit/config.go
pkg/ratelimit/limitware/middleware.go
terraform/redis.tf
terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_server.tf
terraform/services.tf

This changes rate limiting for API keys to be "per API key realm, per IP" to reduce the chance of someone being able to DOS the system if they were to uncover an API key.
It also switches to HMAC (instead of just hash) the values before they are stored in Redis.
```release-note
**Major change!** Change rate limiting for API keys to rate limit by "Realm + IP" to reduce the chance of a DOS attack. Re-evaluate your rate limits to ensure they still make sense in this new model.
```

Switch to APIKey+IP rate limiting, HMAC values

---

pkg/database/migrations.go

This uses the existing stats we've been collecting to backfill them onto the realm stats. It only includes backfill up to 9/15, which is when we'll cut a new release.
```release-note
Add backfill migration for realm stats
```

Backfill realm stats based on user and apikey stats

---

cmd/server/assets/users/index.html
cmd/server/main.go
pkg/controller/user/index.go
pkg/database/realm.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/538
* Adds pagination when there is a large number of users per realm
* Still probably not ideal for order ~thousands
```release-note
Pagination for Users page
```

Implement pagination for the Users page

---

pkg/controller/user/index.go
pkg/database/realm.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/538
* Some follow-up on https://github.com/google/exposure-notifications-verification-server/pull/541
* Adds a fast-forward and backward button to skip many pages if the set is long
* Fix a constant
* Handle atoi err

Adding a fast-forward for very-long lists

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/server/main.go
go.mod
go.sum
pkg/ratelimit/limitware/middleware.go

This upgrades us to the new limiter that supports multi-tenancy. It doesn't actually _implement_ that multi-tenancy on this server yet.
```release-note
NONE
```

Upgrade rate limiter

---

cmd/server/assets/realm.html
pkg/controller/realmadmin/save.go
pkg/database/migrations.go
pkg/database/realm.go

This adds the new realm fields and UI elements. The form is wired up to save and persist them in the database, but there's no enforcement or historical calculations yet.
Part of GH-534
```release-note
Add database fields and UI structure for abuse prevention
```

Add initial scaffolding for abuse prevention

---

cmd/enx-redirect/assets/404.html
cmd/enx-redirect/assets/500.html
cmd/enx-redirect/assets/header.html
cmd/enx-redirect/main.go
pkg/config/redirect_config.go
pkg/controller/redirect/index.go
pkg/controller/redirect/redirect.go

First towards #549 
* Standalone service to redirect https:// links to ens:// for mobile 
```release-note
Introduce deep link redirect service to support exposure notification express.
```

https -> ens protocol redirect service

---

cmd/server/assets/realmstats.html
cmd/server/assets/users/import.html
cmd/server/assets/users/index.html
cmd/server/assets/users/new.html
cmd/server/assets/users/show.html
cmd/server/main.go
pkg/controller/user/import.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/517
* Create empty pages for user import
* Fix up users page card, put in an import button
* Fix a few back-links

Create empty page for user import.

---

builders/migrate.dockerfile

Don't mount migrations on the verification server

---

cmd/server/assets/header.html
cmd/server/assets/login/_loginscripts.html
cmd/server/assets/login/login.html
cmd/server/assets/login/register-phone.html
cmd/server/assets/login/reset-password.html
pkg/controller/login/select.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/545
* Create a custom html pin form for login and registerphone
* Resend SMS link is disabled and enables on a 15s timer.
* Use the close-icon to return to previous
* Some css tweaks
```release-note
Use custom html for entering SMS pin
```

OTP entry form instead of window alert

---

cmd/server/assets/users/_form.html
cmd/server/assets/users/new.html
cmd/server/main.go
go.mod
go.sum
pkg/controller/user/create.go
pkg/controller/user/user.go

* We currently generate new user accounts on the client, this moves it to the server.
* Ideally we'd send an email from the server too, but we don't have and email service.
* Someday I'd love to restrict the public firebase APIKey from creating accounts and only allow the server to do it (and rotate a private/secret key)

Generate new user account on the server-side

---

scripts/terraform.sh

Terraform smoke test failed due to destroy action not able to reuse terrafrom state file, initiate terraform before destroy should fix this problem
Smoke test is failing: https://testgrid.k8s.io/googleoss-en-server#verification-terrafrom-smoke

Fix terraform smoke test: initiate before destroy

---

builders/build.yaml
builders/deploy.yaml
builders/promote.yaml
cmd/modeler/main.go
cmd/server/assets/header.html
cmd/server/assets/realm.html
cmd/server/assets/users/import.html
cmd/server/main.go
go.mod
go.sum
pkg/config/modeler.go
pkg/controller/modeler/modeler.go
pkg/controller/modeler/modeler_test.go
pkg/controller/realmadmin/realmadmin.go
pkg/controller/realmadmin/save.go
pkg/database/database.go
pkg/database/migrations.go
pkg/database/modeler_status.go
pkg/database/realm.go
pkg/database/realm_stats.go
pkg/digest/digest.go
pkg/ratelimit/limitware/middleware.go
terraform/service_modeler.tf
tools/seed/main.go

Part of GH-534
```release-note
Add modeling service for abuse detection (and prevention in the future)
```

Add modeling service for abuse prevention

---

cmd/server/assets/admin/info.html
cmd/server/assets/header.html
cmd/server/main.go
pkg/controller/admin/info.go
pkg/controller/middleware/template.go
pkg/render/render.go

```release-note
Add info page for admins to see build info
```

Add admin/info page to display build info

---

cmd/server/assets/login/register-phone.html
cmd/server/assets/login/verify-email.html
cmd/server/assets/realm.html
cmd/server/main.go
pkg/api/api.go
pkg/controller/login/register.go
pkg/controller/login/verify_email.go
pkg/controller/middleware/emailverified.go
pkg/controller/realmadmin/save.go
pkg/controller/session.go
pkg/controller/user/import.go
pkg/database/migrations.go
pkg/database/realm.go

* Adds a realm setting to configure email-verification requirements for the realm
```release-note
New realm setting to allow skipping or requiring email verification
```

Email verification requirement setting

---

cmd/server/assets/_flash.html
cmd/server/assets/header.html

Success notices are auto-dismissed. Warnings and errors are dismissable via the X.
```release-note
Switch to toasts for notices
```

Switch to toasts for notices

---

cmd/server/assets/login/select-password.html
cmd/server/main.go
pkg/controller/login/select_password.go

* Adds a new password selection page
* TODO: validate introduce length / complexity requirements.
```release-note
Add a password selection page
```

Create a password  selection  page

---

cmd/adminapi/main.go
cmd/server/main.go
pkg/config/admin_server_config.go
pkg/config/issue.go
pkg/config/server_config.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/issueapi.go
pkg/controller/issueapi/metrics.go

Fixes GH-534
This adds an optional (off by default) enforcement mechanism for per-realm daily quota enforcement.
```release-note
Add enforcement mechanism for realm quotas
```

Add enforcement mechanism for realm quotas

---

pkg/config/server_config.go

Part of GH-574
```release-note
Change default session duration from 24h to 20h
```

Make default session duration 20h

---

cmd/server/assets/login/select-password.html
pkg/config/server_config.go
pkg/controller/login/select_password.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/573
* Javscript-enforces complexity requirements for password change
* Template provides complexity reqs from server config
```release-note
Added UI for password complexity requirements
```

Complexity requirements UI

---

cmd/server/assets/home.html
cmd/server/main.go
pkg/config/server_config.go
pkg/controller/middleware/auth.go
pkg/controller/middleware/sessions.go
pkg/controller/session.go

Fixes GH-574
```release-note
Add session idle duration with a default of 20min
```

Add session idle duration

---

builders/deploy.yaml
builders/promote.yaml

```release-note
Add enx to deployment and promote
```

Add enx to deployment and promote

---

cmd/server/assets/realm.html
pkg/controller/realmadmin/save.go
pkg/database/migrations.go
pkg/database/realm.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/575
* Adds two new settings
* Require password rotation at N days
* Warn users about upcoming rotation at N days before expiry
```release-note
New realm setting for password rotation requirements
```

Realm setting for password rotation

---

cmd/server/assets/login/reset-password.html
cmd/server/main.go
pkg/controller/controller.go
pkg/controller/login/reset_password.go
pkg/controller/middleware/realm.go
pkg/controller/session.go

Fixes #https://github.com/google/exposure-notifications-verification-server/issues/575
* Enforce password age per realm setting
* Currently redirects to a change-password page that is the same as reset-password.
* We should create a real password change page so an authed user nearing the deadline doesn't need the full email re-verification.
```release-note
Enforce password rotation
```

Enforce password  rotation

---

cmd/server/assets/users/new.html
cmd/server/assets/users/show.html
pkg/controller/user/create.go
pkg/controller/user/importbatch.go
pkg/controller/user/show.go
pkg/controller/user/update.go

* Redirect the user to the show-user page after creation
* The current experience is potentially confusing as the user winds up back at the new-user page (despite the flash alert). This makes it more clear that the user is created.
* Adds a send-password reset button to the user page so admins can resend the reset if need-be.
```release-note
Add password-reset button for admins
Change new-user redirect to show-user
```

Redirect to show page after user-create

---

cmd/server/assets/login/select-password.html

Fixes https://github.com/google/exposure-notifications-verification-server/issues/600
* As-your-type verify the user's password for more feedback
* Fixes an issue where the [mistakenly] included loginscript redirects if the user is already logged-in
```release-note
as-you-type password validation
fix redirects from password change page
```

As you type verify password

---

cmd/server/assets/admin/_nav.html
cmd/server/assets/admin/info.html
cmd/server/assets/admin/realms/index.html
cmd/server/assets/admin/realms/new.html
cmd/server/assets/admin/users/index.html
cmd/server/assets/admin/users/new.html
cmd/server/assets/header.html
cmd/server/main.go

* Load the current realm for admin pages
* Currently if you navigate to an admin page, the rest of the nav menu is lost which is a weird UX dead-end. This is cruft from when we only had RequireRealm (you can still get to this page if no particular realm is selected)
* Differentiated coloring and navigation for admin pages reinforces that this is a different experience.
```release-note
Differentiated nav bar for System Admin
```

Load realm for system admin pages

---

terraform/alerting/probers.tf
terraform/alerting/variables.tf

* Let terraform alerting configs define extra hosts to monitor.
```release-note
extra-hosts variable added to alerting terraform to let people setup alerts for other hosts they care about.
```

Add extra hosts flag to monitor

---

cmd/server/assets/codestatus/show.html
pkg/controller/codestatus/show.go

* Don't show the expiration countdown if a code is already claimed. Previously you would see the red countdown clock for a code that has already been redeemed.
```release-note
NONE
```

don't show expiry countdown if claimed

---

cmd/server/assets/realmadmin/edit.html

```release-note
Make it more difficult to accidentally disable ENX
```
/cc @mikehelmick 

Hide ENX settings once enabled behind advanced panel

---

cmd/server/assets/login/reset-password.html

* Respond the same for users who's emails are not found
* This won't fool anyone savvy - we need to be either:
1) sending these from our own SMTP server
2) find a firebase toggle that disables this response
2) run all firebase from node.js in a function as a proxy, filter server side, keep the firebase api key secret

Suppress user-not-found error

---

pkg/controller/modeler/modeler.go
pkg/controller/modeler/modeler_test.go
pkg/database/modeler_status.go

```release-note
Avoid integer overflow when model is negative
```

Avoid integer overflow when model is negative

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/modeler/main.go
cmd/server/main.go
pkg/config/modeler.go
pkg/controller/modeler/modeler_test.go
terraform/service_modeler.tf

This is required so that the new values display in the UI
```release-note
Give modeler ability to clear the cache
```

Give modeler ability to clear the cache

---

cmd/apiserver/main.go
cmd/server/main.go
go.sum
pkg/controller/certapi/certapi.go
pkg/controller/certapi/signers.go
pkg/controller/jwks/jwks.go
pkg/controller/realmkeys/realmkeys.go
pkg/controller/realmkeys/render.go
pkg/keyutils/public_keys.go

Fixes GH-346
```release-note
Use the configured cacher for public key and signing key caches
```
/assign @jeremyfaller

Use the same cacher for public key and signing caches

---

cmd/server/assets/realmadmin/_form_abuse_prevention.html
cmd/server/assets/realmadmin/_form_codes.html
cmd/server/assets/realmadmin/_form_general.html
cmd/server/assets/realmadmin/_form_security.html
cmd/server/assets/realmadmin/_form_sms.html
pkg/controller/realmadmin/settings.go
pkg/database/database.go
pkg/database/migrations.go
pkg/database/realm.go

This is required for the ENX redirector, but we've also always made the
assumption that these need to be globally unique.
Note that this requires changing the column to citext (for
case-insensitive matching) and to NULL out the default of '', since ''
is a duplicate of ''.
It also handles any existing duplicates by appending -N to them before
applying the database-level unique constraint.
```release-note
**Potentially breaking** Require region codes be globally unique, add database constraint for realm name uniqueness
```
/cc @icco @mikehelmick

Require region codes are globally unique

---

pkg/cache/config.go

It was always documented this way, but it's never been honored since it was coded as "TYPE".
This is technically breaking, but I don't think we should accept a config value from an envvar of "TYPE", and I don't think anyone is actually configuring this.
```release-note
Fix cache type envvar as `CACHE_TYPE`
```

Fix cache type envvar as CACHE_TYPE

---

cmd/server/assets/header.html
cmd/server/assets/realmadmin/_form_abuse_prevention.html
cmd/server/assets/realmadmin/_form_sms.html
pkg/controller/realmadmin/settings.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/sms_config.go

First part of GH-432.
There's currently no way to create or delegate SMS configs - that will be a follow-up PR. All of the UI is guarded by the SMS config being delegated though.
```release-note
Introduce scaffolding for system SMS configs
```

Introduce concept of "system SMS config"

---

cmd/server/assets/login/_loginscripts.html
cmd/server/assets/login/login.html
cmd/server/main.go
pkg/controller/login/reauth.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/609
* Creates and serves the login page without the /home redirect
* Pre-fill email field if session has a user alreadu
* Calls reauthenticateWithCredential for existing user
* Allows the session to specify a redirect on success. This will be used to get  back  to the phone, email change, or password change page respectively.
```release-note
Created a login page for re-authorizing an already logged-in user
```

Create a login page for re-authing a user

---

cmd/server/assets/login/login.html
cmd/server/assets/login/register-phone.html
cmd/server/main.go
pkg/controller/login/reauth.go

* Phone enrollment can fail if the session is old. Firebase needs re-authentication for sessions that aren't "recent" (which is vaguely unspecified)
```release-note
Redirect to login if re-authorization is required
```

Handle re-auth redirect

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/server/assets/realmadmin/_form_security.html
cmd/server/main.go
pkg/controller/middleware/apikey.go
pkg/controller/middleware/firewall.go
pkg/controller/realmadmin/settings.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/ratelimit/limitware/middleware.go

This adds per-realm firewall settings (by allowed CIDR blocks) for the adminapi, apiserver, and main server. 
```release-note
Add per-realm firewall security settings
```

Add application-level per-realm firewall configuration

---

pkg/controller/verifyapi/verify.go
pkg/database/authorized_app.go

```release-note
Don't log a 500 when it's a user error
```

Don't log a 500 when it's a user error

---

go.mod
go.sum

We're seeing crashes in prod, that we think are fixed at HEAD. I've
forked the repo so we can pick up the changes.
Fixes $GOOG_BUG
```release-note
NONE
```

Replace github.com/jackc/puddle with a fork.

---

cmd/server/assets/login/_loginscripts.html
cmd/server/assets/login/account.html
cmd/server/assets/login/change-password.html
cmd/server/assets/login/select-password.html
cmd/server/main.go
pkg/controller/login/change_password.go
pkg/controller/middleware/emailverified.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/609
* Allow an authenticated user to change their password
* No longer need to send a reset password email
* Handles recent-auth redirect
TODO: Switch this to Seth's server-side client library
```release-note
Allow users to change their password
```

Allow authed user to change password

---

terraform/redirect-lb.tf
terraform/verification-lb.tf

* If you are using enx-redirect, and you modify the map variable, this will recreate the cert, which will create unknown amounts of downtime. So instead, you need to manually create a new cert with the new domains, append it to the FE, and then wait for it to become healthy, and then change the FE again by removing the old cert.
* This changes the FE to use two certs, so that the "main" cert is just `www.` and then the region domains are on a separate cert, this makes the above process easier. 
* Also split the two LBs into separate files.
```release-note
Changes the certificates on the redirect server.
```

Make certificate swapping easier for enx-redirect

---

pkg/controller/issueapi/issue.go
pkg/controller/issueapi/metrics.go
terraform/alerting/dashboards/verification-server.yaml
terraform/alerting/monitoring.tf

Fixes #572
* Record metric for realm capacity on issuing a verification token
* Add dashboard and alerting for monitoring realm capacity
```release-note
Record and monitor realm verification token capacity
```

Add monitoring and alerting for realm capacity

---

pkg/controller/middleware/realm.go
pkg/database/user.go
pkg/database/user_test.go

* Password change will be the account creation time if the new column is unset
* "unknown" string for the UI just in case, but we don't expect to see that
```release-note
Password creation time field falls back to user creation time
```

Make sure password change time is something

---

pkg/controller/admin/sms.go
pkg/controller/realmadmin/settings.go

```release-note
Ensure SMS provider type is set on system configs
```

Ensure provider type is always set

---

cmd/server/assets/login/reset-password.html
cmd/server/main.go
internal/firebase/error.go
internal/firebase/password_reset_email.go
pkg/controller/login/controller.go
pkg/controller/login/reset_password.go
pkg/controller/user/create.go
pkg/controller/user/importbatch.go
pkg/controller/user/user.go

* Moves the password-reset logic to the server-side
* Allows us to better hide the not-found response if the user email isn't in our system
```release-note
Move password reset call to the server
```

Server-side password reset

---

terraform/alerting/dashboards/verification-server.yaml

Fixes dashboard definition mistake which prevents Terraform operations
* Fix dashboard definition
```release-note
NONE
```

Fix dashboard definition

---

terraform/alerting/monitoring.tf
terraform/alerting/variables.tf

The end goal is to have 3 variables
- monitoring-host-project: preferrably a separate project to host alerts
and dashboards.
- verification-server-project: Optional if empty
- key-server-project: Optional if empty
If the agency running the service only care about one of
verification/key server, they can choose to leave out the one they don't
care about.

Better organize the project variables in the alerting TF module.

---

cmd/server/assets/_flash.html
cmd/server/assets/login/select-password.html
pkg/controller/login/select_password.go

* This is based on some user feedback / confusing over expired invite links. I'm hoping this makes it clear what to do to make a login.
* Disable fields and link to password reset if there is an invalid code
* We could just redirect there and skip over this with a flash message, but I find that jarring
* Wrap flash with if in case it's not set. That can be the case pre-login where there is no session/middleware setting flash to empty

Direct users back to password reset email if code invalid/expired

---

cmd/server/assets/login/account.html
cmd/server/assets/login/select-password.html
cmd/server/assets/login/verify-email.html
cmd/server/main.go
pkg/controller/login/select_password.go
pkg/controller/middleware/emailverified.go
pkg/database/user.go

* Redirect to verify email / select password based on the firebase mode
I like this less, but firebase doesn't allow for custom URL per email template. I think it's pretty geared for their UI component.
Note: We'll switch the template to manage-account and remove the old routing after deployment

Redirect firebase emails on 'mode' query param

---

cmd/server/assets/admin/realms/new.html
pkg/database/realm.go

* previous validation didn't all top level, 2 character, ISO regions.
```release-note
Allow country level ISO regions for EN Express
```

fix iso code validation

---

cmd/server/assets/login/_loginscripts.html
cmd/server/assets/login/change-password.html
cmd/server/assets/login/select-password.html

* Password validity should get re-checked on retype because we now validate that they match
```release-note
Minor fix to password selection validation UI
```

Ensure password validity updated on retype

---

cmd/server/assets/login/register-phone.html

* We can't check MFA factors from the server (not in the go library yet) so we push the MFA factor count to session. However we need to refresh the count as new factors are enrolled, or a user can get stuck without logout/sign-in for a realm with MFA marked 'required'
```release-note
Refresh session with enrolled MFA on registration
```

Refresh session on MFA enrollment

---

.github/workflows/codereview.yaml

Inspired by @mattmoor 's work in knative, adding a code review github action. This action does:
- Comment when upcoming PR contains `.Errorw`
A POC is: https://github.com/chaodaiG/github-action-exp/pull/3/files

Automatic code review: comment wheen there is a new .Errorw added

---

scripts/terraform.sh

Fetching database instance name from terraform output isn't always reliable, to achieve mroe reliable terraform smoke test, deleting all database instances prefix with en-verification during smoke test

Terraform smoke test: fetching DB instance name from terraform state

---

cmd/server/assets/header.html
cmd/server/assets/mobileapps/_app.html
pkg/database/migrations.go
pkg/database/mobile_app.go
pkg/database/mobile_app_test.go

Fixes GH-697
```release-note
Make mobile app names unique by realm_id _and_ platform
```

Make mobile app names unique by realm_id and platform

---

cmd/server/assets/login/register-phone.html

Fixes https://github.com/google/exposure-notifications-verification-server/issues/649
* Use the nice telephone input with country-code  preselection for MFA registration
* Based on: https://github.com/google/exposure-notifications-verification-server/pull/656
```release-note
Telephone input widget  for MFA registration
```

Pretty phone for  MFA registration

---

cmd/server/assets/realmadmin/_form_general.html
pkg/database/realm.go

* Go back to allowing any non-empty region code - the validation was breaking test environments.
```release-note
NONE
```

remove attempts at country code validation and just require one is set

---

cmd/server/assets/mobileapps/_app.html
cmd/server/assets/mobileapps/show.html

Also a little more clarity re SHA256 vs SHA1
* Use the phrase "package name" to identify android apps (as opposed to "bundle identifier")
* Add a little more clarity re SHA256 vs SHA1
NONE

Changed Bundle ID to package name for Android apps

---

docs/production.md

```release-note
Add setup instructions for Twilio
```

Document Twilio setup and recommendations

---

cmd/cleanup/main.go
pkg/controller/cleanup/cleanup.go
pkg/controller/cleanup/metrics.go
pkg/database/database.go
pkg/database/metrics.go

Fixes GH-716
Add metrics for cleanup and audits.
```release-note
Add metrics for cleanup and audits
```
/cc @icco

Add metrics for cleanup and audits

---

.github/workflows/codeql-analysis.yml

Looks cool, unclear if it'll work: https://github.blog/2020-09-30-code-scanning-is-now-available/
```release-note
NONE
```

Enable code scanning?

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/e2e-runner/main.go
cmd/server/assets/apikeys/new.html
cmd/server/assets/apikeys/show.html
cmd/server/assets/mobileapps/_app.html
cmd/server/assets/realmadmin/_form_sms.html
pkg/controller/apikey/create.go
pkg/controller/middleware/apikey.go
pkg/database/authorized_app.go
pkg/database/authorized_app_test.go
pkg/database/migrations.go
tools/seed/main.go

Since Go's default value for ints is 0, there have been a number of edge
cases where we have to manually set or check the APIKeyType as -1 to
indicate a value of "unset".
This PR changes the APIKeyType to be an iota with a default value of 0.
That means existing database records are updated 0->1 and 1->2.
```release-note
NONE
```

Update APIKeyType to have a basis of 0

---

docs/realm_guide.md
docs/user_guide.md

As I was reading through these I noticed some spelling issues at the end of the realm_guide. In training with some users, they mentioned it was confusing setting up 2fa due to the need to prefix the phone number with +1 and suggested adding a note about that to the docs. I also ran the 2 files through grammarly and accepted most of the suggestions. Some items felt like personal preference not worth changing.
* Fix spelling issues in realm_guide
* Explain multiple 2fa phones are useful
* General small fixes
NONE

Doc cleanup largely based on spelling/grammar check

---

pkg/controller/modeler/modeler.go

```release-note
Use abuse prevention limit factor when setting the limit
```

Actually use factor when setting limit

---

cmd/server/assets/login/change-password.html
cmd/server/assets/login/login.html
cmd/server/assets/login/register-phone.html
pkg/controller/admin/users.go
pkg/controller/login/reset_password.go
pkg/controller/login/select_password.go
pkg/controller/user/create.go
pkg/controller/user/update.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/726
* Trim whitespace from a few user-input spots
* User name/email input
* Login email input
* Login MFA code input
```release-note
Trim whitespace from login and create-user inputs
```

Trim whitespace from user-input

---

cmd/server/assets/realmadmin/_form_security.html
cmd/server/assets/users/import.html
pkg/controller/middleware/mfa.go
pkg/controller/realmadmin/settings.go
pkg/database/duration.go
pkg/database/migrations.go
pkg/database/realm.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/607
* Adds a new realm setting for MFA required mode that allows users to skip MFA registration for a number of days.
TODO: Update the registration page to show days remaining
```release-note
MFA registration grace period
```

Create a grace period before MFA is required

---

pkg/controller/certapi/certificate.go
pkg/controller/certapi/metrics.go
pkg/controller/cleanup/cleanup.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/metrics.go
pkg/controller/verifyapi/metrics.go
pkg/controller/verifyapi/verify.go
pkg/database/database.go
pkg/database/metrics.go
pkg/observability/observability.go
pkg/ratelimit/limitware/middleware.go

Also refactor realm_id injection to be simpler, save a database lookup.
Refs https://github.com/google/exposure-notifications-server/issues/1023
```release-note
Always include build_id and build_tag in metrics
```

Always include build_id and build_tag in metrics

---

pkg/observability/observability.go

```release-note
Include knative info in metrics if present
```

Include knative info in metrics if present

---

cmd/server/assets/users/_form.html
pkg/controller/user/update.go

* Admins may not change user emails
1) We could allow changing email, but we would also want to update the firebase login and chang email-verified to false.
2) We could have a separate, editable 'contact email' that isn't the same as login email
```release-note
Disable modifying user email
```

Disable editing user email

---

cmd/server/assets/login/change-password.html
cmd/server/assets/login/select-password.html

* Password select/change should respond to both keyup, paste, and change to handle all methods of input
* It currently assumes the user is typing
```release-note
Password validation responds to copy/paste
```

Respond to paste, keyup, and change

---

cmd/server/assets/realmadmin/_form_abuse_prevention.html
go.mod
go.sum
pkg/controller/issueapi/issue.go
pkg/controller/realmadmin/express.go
pkg/controller/realmadmin/settings.go

- Display the currently configured limit and remaining tokens on the realm settings page.
- Only create the metrics for realms that have abuse prevention enabled.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/735
```release-note
Display the currently configured limit and remaining tokens on the realm settings page
```

Attempt to fix realm quota alert

---

cmd/server/assets/login/login.html
internal/firebase/error.go
pkg/controller/login/reset_password.go

* Show "Too many attempts" error message in flash
* We currently eat firebase errors and show a generic one. This was done to hide certain responses (user not-found) that could leak information. However too-many-attempts/requests we should let the user know about so they don't keep trying.
* This issue was found by an early tester who was rapidly resetting password.
```release-note
Show error message on too-many-attempts
```

Too many attempts message

---

cmd/server/main.go

* Minor change to the regex
* Ensures the verifyEmail link goes to the right place
* Remove deprecated URLs

Deprecate old routing for resetPassword / verifyemail

---

terraform/README.md
terraform/alerting/probers.tf
terraform/alerting/variables.tf
terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_server.tf
terraform/variables.tf
terraform/verification-lb.tf

\*_custom_domains are now \*_custom_hosts and fronted by a load balancer for more control and flexibility.
```release-note
**Breaking change** unify custom host handling logic in Terraform. `*_custom_domains` are now `*_custom_hosts` and fronted by a load balancer for more control and flexibility.
```

Unify custom host handling logic

---

terraform/README.md

```release-note
Update Terraform quick setup docs
```

Update Terraform quick setup

---

cmd/server/assets/users/show.html
pkg/controller/login/reset_password.go
pkg/controller/user/create.go
pkg/controller/user/reset_password.go
pkg/controller/user/show.go

* When resetting password, ensure that if we have a db.User that we also have a firebase user
* Move password-reset to server-side for Users/ page
**Note: ** This does send the user back through the email verification flow (which is currently bundled with our password-reset invitation and therefore not seen by most users)
_This PR fixes the issue without adding a metric. That will be done as a separate PR. See https://github.com/google/exposure-notifications-verification-server/pull/685_
```release-note
Ensure that password-reset flows also check that the firebase user auth is created if it's missing and we have an entry for the user.
```

Recreate firebase user, no metric

---

Makefile
scripts/presubmit.sh

I'm tired of getting dinged on this in code reviews.

Add presubmit check for tabs in html files.

---

pkg/controller/login/reset_password.go
pkg/controller/metrics.go
pkg/controller/user/reset_password.go
pkg/controller/user/show.go

* Record a metric for recreating firebase users
There was some discussion on initializing metrics on:  https://github.com/google/exposure-notifications-verification-server/pull/685 with  the switch to openCensus sharing should be a non-issue as everything is handled in init()

Record metric for recreated firebase user

---

cmd/server/assets/realmadmin/_form_abuse_prevention.html
pkg/config/admin_server_config.go
pkg/config/server_config.go
pkg/controller/modeler/modeler.go
pkg/controller/realmadmin/settings.go

If realm quota is enabled and then someone "takes" from the bucket before the modeler runs, then the realm gets the default quota (which is low). Worse, it gets the default TTL (60s), which also isn't correct.
More comments inline in the code
```release-note
Handle edge case when realm quota is first enabled, enforce realm quota by default.
```

Handle edge case when realm quota is first enabled

---

terraform/database.tf
terraform/variables.tf

Fixes GH-768
```release-note
Make prevent_destroy configurable in Terraform configurations
```

Make prevent_destroy configurable

---

terraform/database.tf

Terraform already requires confirmation, and this makes it difficult to iterate.
/cc @chaodaiG for thoughts
```release-note
NONE
```

Remove prevent_destroy

---

cmd/server/assets/codestatus/index.html
pkg/controller/codestatus/expire.go
pkg/controller/codestatus/index.go
pkg/controller/codestatus/show.go
pkg/database/token.go
pkg/database/vercode.go
pkg/database/vercode_test.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/232
Show a few (5) recently issued codes on the code-status page
* TODO: change code status page to GET, make links real links instead of JS filling the form
* TODO: consider indexing this query
* TODO: clean up the date format
```release-note
Show a list of recent codes on the code-status page
```

List recent codes on code-status page

---

cmd/server/assets/codestatus/index.html
cmd/server/main.go
pkg/controller/codestatus/show.go

* Switch the show-code page from POST to GET
* Use hrefs for the code-list for better navigation (less javascript magic)
```release-note
Moved the /code/show page to GET /code/show/{uuid}
```

Switch show-code to GET

---

cmd/server/assets/firebase.html
cmd/server/assets/login/reset-password.html
pkg/controller/login/reset_password.go

* Sends the password-reset email from the client
* Should allow for better attribution for IP-based rate-limiting
* Difference from pre- https://github.com/google/exposure-notifications-verification-server/pull/668 is that we go to the server first to confirm that the user exists and has a firebase account created before responding with firebase details.
```release-note
Move firebase password reset to the client
```

Client-side password-reset

---

cmd/server/assets/codestatus/index.html

Issue https://github.com/google/exposure-notifications-verification-server/issues/232
* Server sends createdAt in UTC, now we interpret them on the client in javascript and replace them in local time
* Should be a little user-friendlier
```release-note
Show code created time in local timezone
```

Show code createdAt in local time

---

pkg/controller/certapi/certificate.go
pkg/controller/certapi/metrics.go
pkg/controller/metrics.go
pkg/observability/observability.go

Part of https://github.com/google/exposure-notifications-verification-server/issues/773
The new metric will eventually replace all other metrics under /api/certificate.

Add a /request metric with blame/result field.

---

cmd/server/assets/login/reset-password.html
cmd/server/assets/users/show.html
cmd/server/main.go
internal/firebase/password_reset_email.go
pkg/controller/user/create.go
pkg/controller/user/importbatch.go
pkg/controller/user/reset_password.go
pkg/controller/user/show.go

* Move the password-reset send to the client from the users page
* Change the name of firebase/internal  SendPasswordResetEmail to SendNewUserInvite with a note about its current and future usage
* Fix a few javascript nits
```release-note
Move the send-password-reset email to the client for admin users
```

Move password-reset to the client for users/show in admin

---

cmd/enx-redirect/main.go
pkg/config/redirect_config.go
pkg/controller/associated/android.go
pkg/controller/associated/index.go
pkg/controller/associated/ios.go
pkg/database/mobile_app.go
pkg/database/realm.go

Fixes #779
* use hostname when deciding what mobile app config to serve on .well-known
* if no configuration, serve a 404
* make cache TTL configurable
```release-note
BUGFIX: Ensure that .well-known is served for the correct region.
```

use redirect hostname to lookup realm for correct mobile app

---

cmd/e2e-runner/main.go

* Currently are our logs are incomplete for e2e failures.
```release-note
NONE
```

Add log errors for e2e fail

---

cmd/enx-redirect/main.go
pkg/controller/redirect/appstore.go
pkg/controller/redirect/index.go
pkg/controller/redirect/index_test.go
pkg/controller/redirect/redirect.go
tools/seed/main.go

Redirector will first redirect to itself,
on Android adding bounce=1 to ensure app link has a chance
to trigger.
iOS is also supported, but for now assuming it doesn't need
the extra bounce.
When an App Link is not configured for a platform,
continue to fall back to ens://
```release-note
Apps that can support app links should now configure a store URL.
```

Adding support for App Links, fallback to Play Store.

---

pkg/controller/issueapi/issue.go
pkg/controller/issueapi/metrics.go

Intend to replace
- /api/issue/realm_token_issued
- /api/issue/realm_token_remaining
- /api/issue/realm_token_capacity
The capacity can be calculated like this:
```
generic_task ::
'custom.googleapis.com/opencensus/en-verification-server/api/issue/realm_token_latest'
| {
filter metric.state == "USED";
ident
}
| [metric.realm]
| ratio
```

Add /api/issue/realm_token metric.

---

cmd/server/main.go
pkg/config/server_config.go
pkg/controller/user/importbatch.go
pkg/controller/user/reset_password.go
pkg/controller/user/user.go
pkg/email/config.go
pkg/email/firebase.go
pkg/email/smtp.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/787
* This PR allows for a server-level override to sending new user invitations via a custom SMTP server
* If no secret is present, it falls back to our firebase hack with the password-reset template
In the future we can use this to
* Allow per-realm overrides of the email server
* Allow per-realm templates for the invitation email itself
This gets around our server-side call to the firebase client API which may face IP rate limiting.
https://cloud.google.com/identity-platform/quotas#email_link_generation_limits_2
Note that generating the link has 10x quota and is intended to be called from the server.
We could someday send other kinds of emails (eg. TOTP for 2nd factor auth if we want to roll our own 2nd …

Allow custom email server for invitations

---

pkg/controller/issueapi/issue.go
pkg/controller/issueapi/metrics.go

Prior to this change, the # of used tokens are calculated by:
issued := uint64(limit) - remaining
This calculation doesn't take burst tokens into consideration. Imaging
the limit is set to 10, and at a time someone added 1000 burst into the
bucket, and the actual used token is 10. We now have limit=10,
remaining=1000, and the calculated issued=-1000, which doesn't make
sense.
The used token should be a CUMULATIVE/view.Count metric, which is
recorded each time we successfully called `limiter.Take()`.

Fix realm token related metrics in /api/issue.

---

pkg/controller/issueapi/issue.go
pkg/controller/issueapi/metrics.go

Since we record the used tokens in a separate metric, we can now keep
using /api/issue/realm_token_latest for the purpose of getting metrics
from the limiter.
We can now calculate the capacity of the limiter by:
generic_task ::
'custom.googleapis.com/opencensus/en-verification-server/api/issue/realm_token_latest'
| {
filter metric.state == "AVAILABLE";
filter metric.state == "LIMIT"
}
| [metric.realm]
| ratio
| value if(val() > 1.0, 1.0, val())

Also modify how /api/issue/realm_token_latest is recorded.

---

pkg/controller/user/index.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/805
Worked great... for even counts
* Ensure we loop till < one more pageSize after the count / pageSize
* offset starts at 0 so add 1 for the text
* min/max functions to simplify
```release-note
Fix pagination off-by-one
```

Fix pagination off-by-one

---

pkg/controller/verifyapi/metrics.go
pkg/controller/verifyapi/verify.go

Those metrics are no longer referenced by dashboards or alerts.
Part of https://github.com/google/exposure-notifications-verification-server/issues/773

Cleanup verify API metrics.

---

pkg/controller/issueapi/issue.go
pkg/controller/issueapi/metrics.go

Those are not referenced by dashboards or alerts.
Also remove /realm_token_issued. As demonstrated in
https://github.com/google/exposure-notifications-verification-server/pull/801,                            
this metric contains an incorrect number. We already have a                                               
/realm_token_used_count metric which is accurate.
Part of https://github.com/google/exposure-notifications-verification-server/issues/773

Cleanup issue API metrics

---

cmd/server/assets/400.html
pkg/controller/controller.go
pkg/controller/redirect/index.go

```release-note
Return 404 on enx-redirect lookup when realm is not found.
```

Return on realm lookup error

---

cmd/server/assets/realmadmin/show.html
pkg/controller/realmadmin/show.go
pkg/controller/realmadmin/show_test.go
pkg/database/realm.go
pkg/database/realm_test.go
pkg/database/user_stats.go

Fixes #799
NB: We display the user's name, **NOT** their ID. The bug was ill-specified. If this is wrogn, please comment.
* Add a per-user-per-realm stats chart
```release-note
Stats page now contains a per-user-per-realm chart.
```

Add a per-realm-per-user chart on the stats page.

---

terraform/alerting/verification-server/monitoring.tf

Part of #824
* Makes all alert names space seperated.
```release-note
Changes two alert names to have spaces in them.
```

Make alert names consistent

---

cmd/e2e-runner/main.go

Fixes: https://github.com/google/exposure-notifications-verification-server/issues/818

e2e test runner random suffix 32 chars instead of picking an int under 10000

---

pkg/database/token_test.go

Makes the test run about 1/2 as fast, but seems to fix the race.
Fixes #830

Fix race in TestIssueToken

---

cmd/server/assets/realmadmin/show.html

Fixes #799
```release-note
Selecting a row in the realm stats highlights the day in the per-user-per-realm chart.
```

When a date is clicked in the realm, highlight day in per-user data.

---

pkg/controller/redirect/appstore.go
pkg/controller/redirect/index.go
pkg/controller/redirect/index_test.go

This fixes behavior of Facebook Messenger when
the app is installed (currently it always redirects to the store),
and appears to generalize to more SMS clients.
It also more closely matches this approach:
https://firebase.google.com/docs/dynamic-links/operating-system-integrations
NOTE: For iOS ENX, Store URL should be left blank, as no App Link triggers ENX.
Custom Apps using the verification server currently can't do the
"fancier" clipboard trick described in the link above, see:
https://github.com/google/exposure-notifications-verification-server/issues/844
```release-note
NOTE: ENX Apps configured for Android for Android should configure Store URL.
iOS ENX regions should NOT.
```

Use Android intent links in place of bouncing.

---

pkg/database/vercode.go
pkg/database/vercode_test.go
pkg/timeutils/midnight.go

Fixes #819
```release-note
Fixes the dates reported in the statistics.
Before this change, it's quite likely that the date reported for all statistics on VerificationCode creation was a day earlier than it was supposed to be.
```

Use midnight when updating stats while creating a VerificationCode

---

terraform/verification-lb.tf

* Sets the TLS policy to 1.2+ and modern as defined in https://cloud.google.com/load-balancing/docs/ssl-policies-concepts#defining_an_ssl_policy
```release-note
Sets the default TLS to 1.2+ for the verification server loadbalancer.
```

Set default to tls 1.2

---

terraform/redirect-lb.tf

Similar to #852 and https://github.com/google/exposure-notifications-server/pull/1093
* Updates redirector LB to use 1.2+ TLS
```release-note
Limits redirector load balancer to only use TLS 1.2+
```

Limit redirector LB to TLS 1.2+

---

pkg/controller/issueapi/issue.go
pkg/controller/realmadmin/show_test.go
pkg/database/authorized_app.go
pkg/database/realm.go
pkg/database/realm_test.go
pkg/database/token.go
pkg/database/token_test.go
pkg/database/user.go
pkg/database/vercode_test.go

**** NB *****
This PR will be marked HOLD until all reviews requested on this PR give
it an LGTM. If you want to HOLD this CL, please add yourself as
reviewer, and mark yourself as NON-LGTM.
**** /NB *****
PTAL. These are all references to Truncate that:
`grep -R Truncate * | grep 24`
returned, and I think all changes are correct. Please verify.
Fixes #848
```release-note
Fixed statistics reporting dates.
Previously, it was possible for many statistics to report themselves on the wrong day. This has been fixed.
```

Fix uses of time.Truncate

---

scripts/terraform.sh

There are 2 scripts used for running e2e tests: `scripts/e2e-tests.sh` and `scripts/terraform.sh`, the former is a thin wrapper of the latter. Adding guard to the latter in this PR to avoid it from being used on prod resource

e2e test script is guarded against prod resources

---

scripts/terraform.sh

`gcloud --filter` will change its `name=value` behavior to regex matching in future updates, and recommending `name<=value AND name>=value` if desire an equality checking. See: https://cloud.google.com/sdk/gcloud/reference/topic/filters
Updating the usage to prevent future breakages

E2E test: update usage of gcloud to prevent breakage from future breaking API changes

---

docs/production.md
terraform/database.tf
terraform/variables.tf

```release-note
Support multiple keys for HMAC secrets
```

Support multiple keys for HMAC secrets

---

terraform/README.md

Fixes GH-867
```release-note
Document setting versioning and lifecycle on Terraform state
```

Document setting versioning and lifecycle on Terraform state

---

cmd/server/main.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/873
* Verify email does not strictly require a loaded realm. This pops up for a system admin which is not a member of any realm.
This assumes we are requiring system admin to verify their email address. The alternative would be to not require email verification for system admin in the case where no realm is selected, but this feels like the more secure thing to do.

Realm not required for email verify

---

terraform/database.tf
terraform/variables.tf

Fixes https://github.com/google/exposure-notifications-verification-server/issues/864
**Nuances**
- Cloud SQL doesn't seem to support per-instance IAM, so we have to grant at the project level (yuck, but it's only viewer)
- I'm relying on bucket versioning instead of actually naming the exports with a datetime. This is mostly a design decision to avoid needing a middle service. Ideally Cloud Scheduler would support a template syntax, but it does not.
- The backups aren't compressed (for the same reason as above), but our last backup was 2MB. I'm not really worried about large databases for this project.
- Backup time is configurable via the cron notation.
```release-note
Automatically backup the Cloud SQL database to GCS every 6 hours
```
/assign @jeremyfaller @icco

Backup the Cloud SQL database to GCS every 6 hours

---

cmd/server/main.go
internal/routes/routes.go
internal/routes/server.go

Copy-paste into its own file. This is important so we can share the routes and construction with the upcoming browser-level tests, and I plan to backport some of this into the `integration` package to reduce duplication.
Doing this as a separate PR to keep the diff small.
```release-note
NONE
```

Move routes for server into internal package

---

cmd/server/assets/email/default_email_verify.html
cmd/server/assets/login/verify-email.html
internal/routes/server.go
pkg/render/render.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/873
* Drops the realm required for verifying email
* Protect the template in the case realm is nil
* Make sure the email link works properly (html unescape)
```release-note
Fix redirect loop when verifying email for an admin with no realm selected
```

Fix verify email flow with no realm

---

cmd/server/assets/mobileapps/_app.html

* Add help text around mobile app for iOS. Adding one when using ENX can break things.
```release-note
NONE
```

add help text around iOS ENX

---

terraform/database.tf

Part of https://github.com/google/exposure-notifications-verification-server/issues/885
```release-note
Add Terraform output for backup command
```

Add output for backup command

---

pkg/api/api.go
pkg/controller/issueapi/issue.go
pkg/controller/verifyapi/verify.go
pkg/database/migrations.go
pkg/database/token.go
pkg/database/token_test.go
pkg/database/vercode.go
pkg/database/vercode_test.go
pkg/otp/code.go

Fixes #882
* Add test date into verify API return
* Thread this all the way through the verification token
```release-note
API CHANGE : /api/verify now returns the testDate in addition to symptom date if present. When the verification certificate is issue only one interval is inserted: symptomDate if present, testDate if not.
```

thread test date all the way through

---

cmd/server/assets/header.html
cmd/server/assets/static/js/application.js
pkg/controller/middleware/csrf.go

When I moved the javascript to be external, `{{.csrfToken}}` no longer renders.
```release-note
Pull CSRF token from meta tags
```

Pull CSRF token from metadata

---

pkg/email/smtp.go

```release-note
Fix context race when sending email via SMTP
```

Fix context race when sending email

---

pkg/clients/e2e.go

Looks like 2s is too aggressive, and we can see these log lines:
```
error issuing verification code: sending request: Post
"https://adminapi-lilkbg3hpq-uc.a.run.app/api/issue": net/http: request
canceled (Client.Timeout exceeded while awaiting headers)
```

Increase e2e test timeout.

---

pkg/config/cleanup_server_config.go
pkg/controller/cleanup/cleanup.go
pkg/database/authorized_app.go

Fixes #905
```release-note
Clean up deleted API keys after 1 week
```

Clean up deleted API keys after 1 week

---

pkg/controller/issueapi/issue.go

* Fixes metric based on conversation with @sethvargo 
* Found while writing docs with @mariliamelo 
```release-note
Fixes overflow error in capacity metrics when burst quota is given.
```

Try and fix use case of burst capacity

---

terraform/alerting/verification-server/alerts.tf
terraform/alerting/verification-server/alerts/RealmTokenRemainingCapacityLow.yaml
terraform/alerting/verification-server/scripts/upsert_alert_policy.sh

This alert is currently set up using a local-exec provisioner, due to
the lack of support to define alert policies using MQL in Terraform.
Part of #810
This is a revive of #831.

Create alerts using MQL

---

cmd/server/assets/email/_plainheader.txt
cmd/server/assets/email/default_email_verify.txt
cmd/server/assets/email/default_invite.txt
cmd/server/assets/email/default_reset_password.txt
cmd/server/assets/realmadmin/_form_codes.html
cmd/server/assets/realmadmin/_form_email.html
pkg/controller/email.go
pkg/controller/realmadmin/settings.go

* Add UI for admins to override  the realm invitation template
```release-note
Allow realm custom template for invitations
```

Allow override of invite template

---

pkg/config/admin_server_config.go
pkg/config/server_config.go

* Default symptom age changed to 27 days from 14
This is to cover this use case
Someone has symptom onset 27 days ago, and didn't get their verification code until "today." In that case the oldest TEK on that person's phone would be +14 days from symptom onset and could still cause exposure notifications on someone else's phone.
```release-note
Change default symptom age from 14 to 27 days.
```

change default allowed back dating to 27 days (from 14)

---

cmd/server/assets/home.html
cmd/server/assets/login/login.html
cmd/server/assets/login/register-phone.html
go.mod
go.sum
internal/auth/auth.go
internal/auth/firebase.go
internal/auth/local.go
internal/browser/browser.go
internal/browser/executor.go
internal/envstest/envstest.go
internal/envstest/random.go
internal/envstest/server.go
internal/project/root.go
pkg/controller/home/home_test.go
pkg/controller/login/session.go
pkg/controller/middleware/auth.go
pkg/controller/middleware/sessions.go
pkg/database/database_util.go

After evaluation, I decided to use chromedp since it's a pure-go solution that should work headlessly on our existing CI infrastructure (fingers crossed).
This also adds a few new internal-only packages to help with testing:
- `internal/project` - project-wide helpers. Currently the only function is one that returns the filesystem root of the project, which is needed for telling the server where to find its assets. It will also be used by enx-redirector and any other filesystem-ey things.
- `internal/envstest` - globally shared test helpers. I'm going to start centralizing things here across all our test suites. This package also includes all the logic and helpers for spinning up a full in-memory UI server (with database and dependencies) for local testing.
- `internal/browser` - wrapper …

Add test harness for headless browser testing

---

pkg/database/realm.go
pkg/database/realm_test.go

Fixes #928
```release-note
[SECURITY] Scope mobileapp lookup to the realm.
```

Scope mobileapp lookup to the realm

---

pkg/database/database.go
pkg/database/database_test.go
pkg/database/realm.go

* add unicode zero width no-break space to our cutset for certififcate issuer and audience
Workaround of https://github.com/golang/go/issues/42274
```release-note
Fixes an issue where certain non-printable unicode characters would accepted as valid characters for the verification certificate issuer and audience.
```

add ZERO WIDTH NO-BREAK SPACE to our cut set

---

cmd/server/assets/realmadmin/show.html

* An alternative way to show download links for stats

Download stats in a card at the end?

---

internal/routes/server.go
pkg/controller/realmadmin/show.go
pkg/database/realm.go
pkg/database/realm_stats.go

Supports 2 modes:
${SERVER}/realm/stats?csv
Returns overall realm stats.
${SERVER}/realm/stats?csv&user
Returns the per-user realm stats.
Fixes #916
```release-note
Realm stats now supports CSV export:
${SERVER}/realm/stats?csv
Returns overall realm stats.
${SERVER}/realm/stats?csv&user
Returns the per-user realm stats.
```

Return CSV if requested from realm stats.

---

cmd/server/assets/admin/_nav.html
cmd/server/assets/admin/mobileapps/show.html
internal/routes/server.go
pkg/controller/admin/mobile_apps.go
pkg/database/mobile_app.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/910
* Gets the basic pages of mobile-apps into system admin
* Lists all mobile  apps
TODO
* currently action links / hrefs go back to realm admin
* Show realm name per app
* Might want pagination/filtering?
```release-note
Show all mobile apps in system  admin
```

Show mobile apps in system admin  - Part 1

---

pkg/controller/certapi/certificate.go
pkg/controller/verifyapi/verify.go
pkg/database/token.go
pkg/database/vercode.go
pkg/otp/code_test.go

Fixes #946 
* Add debug logging to device APIs
```release-note
Added debug logging to device APIs
```

add debug logging to device APIs

---

cmd/server/assets/apikeys/index.html
cmd/server/assets/mobileapps/edit.html
cmd/server/assets/mobileapps/index.html
cmd/server/assets/mobileapps/new.html
cmd/server/assets/mobileapps/show.html
pkg/controller/mobileapps/create.go
pkg/controller/mobileapps/create_test.go
pkg/controller/mobileapps/index.go
pkg/controller/mobileapps/show.go
pkg/controller/mobileapps/update.go
pkg/database/realm.go

```release-note
Add pagination to mobile apps
```

Paginate mobile apps

---

cmd/server/assets/admin/mobileapps/show.html
pkg/controller/admin/mobile_apps.go
pkg/database/mobile_app.go
pkg/database/mobile_app_test.go
pkg/database/pagination.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/910
* Paginates the mobile apps in system admin using @sethvargo's common paginator
* Creates another override in paginator for queries that aren't just a gorm .Find() - in this case a join and scan rows.

Paginate mobile apps in system admin

---

go.mod
pkg/config/cleanup_server_config.go
pkg/controller/cleanup/cleanup.go
pkg/controller/codestatus/logic.go
pkg/database/database_util.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/vercode.go
pkg/database/vercode_test.go

Fixes #961 
* Check RealmID at DB when looking up a verification code by UUID
* Re-index verification codes to be scoped by realm (code space currently shared across all realms)
* Split code cleanup into 2 phases (1) recycle codes by returning them to the pool (2) purge status records
* Change code recycle from 24h to 48h
* Retain code status for 14d (configurable)
```release-note
Verification code changes: available pool is now scoped by realm. codes are retained 48 hours after expiration by default (instead of 24). Status of a code (by UUID) is retained for 14d instead of 24h.
```

improve verification code retention and UUID checking

---

pkg/controller/user/delete.go
pkg/controller/user/show.go
pkg/controller/user/update.go

* We currently look at currentRealm to find a user within the realm
* System admins should be able to find users globally
* Technically we could go further (someone could be a realm admin of more than one realm so we could instead check that currentuser canAdmin the other user) but this should be good enough to build a system admin view.

Allow system admin users to see/edit all users

---

cmd/server/assets/admin/_nav.html
cmd/server/assets/admin/superusers/index.html
cmd/server/assets/admin/superusers/new.html
cmd/server/assets/admin/users/index.html
internal/routes/server.go
pkg/controller/admin/superusers.go
pkg/controller/admin/users.go
pkg/database/user.go

Issue #https://github.com/google/exposure-notifications-verification-server/issues/975
* Creates a new users tab in system-admin
* Keeps system-admin list and regular users separate
* Allow system admin to delete a user
* Searching and pagination
```release-note
Show regular users across realms in system-admin. Allow deletion.
```

Split admin and regular users in system-admin. Allow delete user

---

cmd/server/assets/header.html
cmd/server/assets/login/account.html
internal/routes/server.go
pkg/controller/admin/superusers.go
pkg/controller/login/select.go
pkg/controller/middleware/auth.go
pkg/controller/user/show.go
pkg/database/migrations.go
pkg/database/realm_test.go
pkg/database/user.go
pkg/database/user_test.go
tools/seed/main.go

Just a simple rename, but now that we're merging some functionality, I want to be clear when we say "system admin". This has also confused our partners in the past.
```release-note
Rename users `admin` to `system_admin` for clarity.
```

Rename Admin to SystemAdmin in users table

---

cmd/server/assets/admin/users/index.html
pkg/database/user.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/975
* Show pills for system/realm admins in the admin console
* Now shows all users for the Users page
* Later I'll fold in the System admin stuff and remove that tab

Show pills for realm/system admin

---

cmd/server/assets/header.html
cmd/server/assets/login/select-realm.html

* Link directly to system-admin page from realm-select
* Note that if the admin is not a member of any realms, we go straight to admin already. https://github.com/google/exposure-notifications-verification-server/blob/f76a3cea09d53d076a47a204ce9c948e183c8f35/pkg/controller/login/select.go#L50
* Remove "launch admin" from navigation if already there

Link to system admin from realm select

---

cmd/server/assets/admin/users/index.html
pkg/controller/admin/users.go
pkg/database/user.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/975
* Allows the user search to toggle between all users and system admins
```release-note
Toggle for user search for all/system-admin
```

Filter user search to system admins

---

terraform/alerting/verification-server/dashboards/e2e.yaml
terraform/alerting/verification-server/metrics.tf

- Include request count and latency charts
- Inculde request count chart with filter on failed requests.

Make e2e-runner dashboard more useful.

---

pkg/clients/e2e.go

In the context of this key server API request, the `err` indicate the
HTTP transport layer error (E.g. HTTP timeout). We actually want to log
when there's application layer error.

Move the log line.

---

cmd/server/assets/realmkeys.html
pkg/controller/realmkeys/render.go
pkg/controller/realmkeys/save.go
pkg/database/config.go
pkg/database/database.go
pkg/database/realm.go
pkg/database/realm_test.go

Fixes #993
```release-note
Limit number of non-deleted KMS signing keys on a realm (default: 5, configurable)
```
I went with 5 instead of 3 because the cost differential is ~$0.12 and I'd rather never be in the way of the end-user.

Limit number of non-deleted KMS signing keys on a realm

---

pkg/database/authorized_app.go
pkg/database/authorized_app_test.go
pkg/database/database.go
pkg/ratelimit/limitware/middleware.go

All our systems are 64-bit, so uint == uint64. However, on 32-bit systems, we would overflow.
```release-note
Ensure bits don't overflow when running on 32-bit systems
```

Ensure bits don't overflow

---

pkg/database/database_util.go
terraform/mirror/docker.tf
terraform/mirror/main.tf
terraform/mirror/service.tf
terraform/mirror/variables.tf
terraform/variables.tf

Also allow customizing the image used in CI via an environment variable.
Fixes #959
```release-note
Add Terraform module to optionally mirror dependent Docker Hub images for tests
```
/assign @chaodaiG

Optionally mirror dependent Docker Hub images

---

terraform/service_e2e_runner.tf

* stagger the e2e runners so logs are easier to discern
```release-note
NONE
```

stagger the e2e runners

---

cmd/e2e-runner/main.go
pkg/clients/e2e.go
terraform/service_e2e_runner.tf

* Fix race condition in e2e-runner
* Actually generate an HMAC secret (instead of using 00000...)
* make both e2e runners run "at the same time" some of the time
```release-note
e2e-runner improvements, fixes race condition
```

E2e improvements

---

terraform/database.tf
terraform/variables.tf

Support regional database replicas in Terraform. The default is still none, and the existing instances are still resilient to zonal failures within a region.
When setting `database_failover_replica_regions`, each region will have a read-only replica in the selected zone. Switching that replica to primary is a manual process. 
Fixes #998
```release-note
Support configuring regional database replicas.
```

Support configuring regional database replicas

---

terraform-e2e/state.tf

It was renamed to terraform-e2e-ci, was left during refactoring

Cleanup unused terraform-e2e directory

---

cmd/server/assets/apikeys/index.html
pkg/controller/apikey/index.go
pkg/database/realm.go
pkg/database/scopes.go

This became obviously necessary on the e2e test project where there are thousands of keys waiting to be cleaned up.
```release-note
Allow searching API keys
```

Allow searching API keys

---

pkg/database/pagination.go

10 rolls off the page when there's a lot of pages.
```release-note
Only show 5 next/prev pages in pagination.
```

Only show 5 next/prev pages

---

cmd/server/assets/admin/_nav.html
cmd/server/assets/admin/events/index.html
internal/routes/server.go
pkg/controller/admin/events.go
pkg/database/audit_entry.go

* Adds the event log to system admin scoped across all realms
TODO: next PR will add in a `Realm` column
```release-note
Show event logs in system-admin
```

Show event log across realms in system-admin

---

cmd/server/assets/header.html
cmd/server/assets/login/account.html
cmd/server/assets/users/_form.html
cmd/server/assets/users/import.html
cmd/server/assets/users/index.html
cmd/server/assets/users/new.html
cmd/server/assets/users/show.html
internal/routes/server.go
pkg/controller/user/delete.go
pkg/controller/user/search_test.go
pkg/controller/user/update.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/1026
We have 
1. `/realm/settings`
2. `/realm/stats`
3. `/realm/keys`
4. `/realm/events`
but
1. `/users`
2. `/apikeys`
3. `/mobileapps`
4. `/home`
5. `/code/stats`
This relocates `/users` to `/realm/users` but I'm also putting this out for a discussion of what we want our paths to look like
/hold
```release-note
Move /users to /realm/users
```

Move /users to /realm/users

---

pkg/controller/issueapi/issue.go

Looks like this got lost when we added the o11y `defer`.
```release-note
Do not return successful JSON on SMS error
```

Do not return successful JSON on SMS error

---

cmd/server/assets/realmadmin/_form_codes.html
pkg/controller/home/home_test.go
pkg/database/realm.go

* Make date required the default for new realms to encourage usage of this feature.
```release-note
"date required" is the default setting on NEW realms only. Existing realms not changed on upgrade.
```

make date required default true for new realms

---

cmd/server/assets/admin/realms/index.html
pkg/controller/admin/realms.go
pkg/database/realm.go
pkg/database/scopes.go

```release-note
Add realm search for system admins.
```

Add realms search

---

.github/workflows/codeql-analysis.yml

Security findings are only available to admins anyway
```release-note
NONE
```

Run codeql on interval

---

cmd/server/assets/users/import.html
internal/auth/auth.go
internal/auth/firebase.go
internal/auth/local.go
pkg/api/api.go
pkg/controller/admin/users_operations.go
pkg/controller/user/create.go
pkg/controller/user/importbatch.go

* Allows the user to skip sending password-reset invitations when bulk-importing users
* This would be used, for example, if a state moving to ENX wants to import firebase auth (and doesn't want to send reset-passwords)
```release-note
Option to skip password-reset invitations on bulk user import
```

Skip invitations checkbox for bulk-import

---

terraform/alerting/verification-server/alerts.tf
terraform/alerting/verification-server/monitoring.tf

Also created an alert if the error rate is exceeding 0.1/s.
Fixes #1065

Add log-based metric to monitor OpenCensus stackdriver export.

---

scripts/ci-e2e-test.sh

Just discovered that incremental e2e test had been creating images and migrating db, but didn't really deploy new services, so the test had been testing the old services from last month. This PR should fix it
/cc @sethvargo @hueich

Incremental e2e tests: use latest service for running tests

---

terraform/alerting/main.tf

adding variable propagation for notification-email

---

cmd/server/assets/admin/events/index.html
pkg/controller/admin/events_test.go

* Creates an audit event with a known time
* Searches for events in that time frame and asserts the one
* Searches and hour before and asserts no results
```release-note
Integration test for system-admin events page
```

Test system-admin audit event search

---

docs/api.md
pkg/api/api.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/issue_test.go
pkg/database/migrations.go
pkg/integration/integration_test.go
pkg/otp/code.go
pkg/render/render.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/1061
* Allow client to provide the tracking UUID for an issued code
* Thus will allow us to pre-allocate these for the bulk-upload scenario which will help with tracking / retryability
* Backwards-compatible, if not provided the server will generate the UUID.
* Redo the UUID index as UNIQUE for enforcement
```release-note
Allow client-provided UUID for issuing a code
Drop and re-create UUID index as UNIQUE
```

Accept client UUID for issued-code tracking

---

cmd/adminapi/main.go
cmd/server/assets/admin/_nav.html
cmd/server/assets/codestatus/index.html
cmd/server/assets/codestatus/show.html
cmd/server/assets/header.html
cmd/server/assets/home.html
cmd/server/assets/login/register-phone.html
cmd/server/assets/login/verify-email.html
internal/routes/server.go
internal/routes/server_test.go
pkg/controller/codes/api.go
pkg/controller/codes/controller.go
pkg/controller/codes/expire.go
pkg/controller/codes/index.go
pkg/controller/codes/logic.go
pkg/controller/codes/show.go
pkg/controller/codestatus/show.go
pkg/controller/home/home_test.go
pkg/controller/login/change_password.go
pkg/controller/login/login.go
pkg/controller/login/select.go
pkg/controller/user/delete.go
pkg/database/migrations.go
pkg/testsuite/integration.go

Also a few nits:
- Fixes the HTML nesting on code lookup form
- Redirects a good UUID in the wrong format/casing to the correct URL
```release-note
NONE
```
The /home -> /code was never deployed, so we don't need to do a /code -> /codes redirect.

Cleanup codes/ paths

---

cmd/server/assets/codes/issue.html
internal/routes/server.go
pkg/controller/codes/issue.go
pkg/controller/codes/issue_test.go

Redirects are in place and tested
```release-note
/home paths redirect to /codes
```

Remove remaining remnants of /home

---

docs/playbooks/Fast_Error_Budget_Burn.md
docs/playbooks/index.md
terraform/alerting/verification-server/alerts.tf

Fixes #
* added fast error budget burn alert (2% in 1 hour)
* added playbook
* updated alerting docs to point to playbook
```release-note
Added fast error budget burn alert and corresponding documentation.
```

Fast burn alert

---

cmd/server/assets/realmadmin/_form_codes.html
pkg/controller/realmadmin/settings.go
pkg/database/migrations.go
pkg/database/realm.go

Issue #1061
* Adds a bit to the realm to allow bulk upload
```release-note
Realm setting to allow/disallow bulk upload
```

Setting to allow bulk upload

---

pkg/controller/issueapi/issue.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1091
Issue https://github.com/google/exposure-notifications-verification-server/pull/1069
* Try to find code by UUID before issuing one to check for conflict.
* Prevents quota-consumption for this error case.

Don't consume quota for client-provided code UUID

---

pkg/controller/realmadmin/settings.go
pkg/database/audit_entry.go

Fixes #926
```release-note
Generate an audit entry when quota is increased
```

Generate an audit entry when quota is bumped

---

cmd/server/assets/codes/bulk-issue.html
pkg/controller/issueapi/issue.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/1061
* Stop at 429 Too Many Requests which we give when the user runs out of codes
* Stop a few permanent errors for good measure
```release-note
Cancel remaining bulk upload when throttled by the server
```

Stop bulk upload if we see certain permanent errors or throttling

---

terraform/alerting/dashboards/verification-server.yaml

The underlying metric has been deleted in
https://github.com/google/exposure-notifications-verification-server/pull/1118

Remove chart from dashboard.

---

pkg/controller/login/reset_password.go

* For security reasons we don't want to differentiate between user not-found and when we really send and email. A malicious user could use this to trawl account-existence.
* I think we accidentally "fixed" this in https://github.com/google/exposure-notifications-verification-server/pull/902

Keep fake success on no-user

---

terraform/database.tf
terraform/variables.tf

Part of #1103
```release-note
Parameterize database_version in Terraform configuration
```

Parameterize database_version

---

pkg/database/migrations.go

I'm not sure how postgres creates a column with default set, but our other columns are initialized like this

Switch how we make this bool column

---

cmd/apiserver/main.go
docs/api.md
pkg/api/api.go
pkg/config/admin_server_config.go
pkg/config/issue.go
pkg/config/server_config.go
pkg/controller/issueapi/issue.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/1139
* Creates an environment variable for maintenance mode which rejects api/issue requests
* random nits
```release-note
Environment variable for maintenance mode
```

Maintenance mode env var

---

cmd/server/assets/header.html
pkg/config/api_server_config.go
pkg/controller/middleware/template.go
pkg/controller/verifyapi/verify.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1139
* Blocks request to verify
* Puts up a scary banner when in maintenance mode
```release-note
Maintenance mode block issue and verify requests. Adds a banner to the header.
```

block verify and throw up a banner

---

pkg/config/admin_server_config.go
pkg/config/server_config.go

* change max age from 27.5 to 28 days. Was off by 12 hours
```release-note
Default max test/symptom age is 28 days 
```

fix off by 12 error

---

scripts/ci-terraform.sh

This had been tested and this grep worked

Terrafrom smoke test: stricter db name matching so it won't mess up

---

docs/playbooks/alerts/FastErrorBudgetBurn.md
docs/playbooks/alerts/SlowErrorBudgetBurn.md
docs/playbooks/alerts/_ErrorBudgetBurn.md
docs/playbooks/playbook_test.go

We don't need two separate pages as the triage process would be the
same.

Add an "Error Budget Burn" playbook page

---

cmd/server/assets/realmadmin/_form_email.html
cmd/server/assets/realmadmin/_form_sms.html
pkg/controller/realmadmin/settings.go
pkg/controller/realmadmin/sms_test.go
pkg/controller/realmadmin/smtp_test.go

```release-note
Do not display passwords in HTML forms
```
/cc @mikehelmick 

Do not display passwords in HTML forms

---

cmd/server/assets/codes/bulk-issue.html
internal/routes/server.go

```release-note
Don't serve session cookie over javascript, restrict retry storage to 24h
```

Don't serve session cookie over javascript, restrict retry storage to 24h

---

pkg/database/database_util.go

```release-note
Document that creds are for tests only
```

Document that creds are for tests only

---

internal/auth/auth.go
internal/auth/firebase.go
internal/auth/local.go
pkg/controller/login/signout.go
pkg/database/user.go

⚠️ We should talk about whether to actually revoke refresh tokens! Revoking the refresh token ensures a signout, and it occurs on _all_ devices. That means for local testing, if one person logs out, we all get logged out (we'll need to make our own accounts for testing auth). I think this is probably the best solution, but open to other ideas.
```release-note
Fully revoke signout tokens and update last_revoke_checked
```

Fully revoke signout tokens and update last_revoke_checked

---

cmd/server/assets/admin/email/show.html
cmd/server/assets/admin/sms/show.html

/cc @whaught 
```release-note
Do not use show-password on sentinel forms
```

Do not use show-password on sentinel forms

---

pkg/controller/controller.go
pkg/controller/middleware/secure.go

```release-note
Only trust HTTP Referer from same origin domain
```

Only trust Referer from same domain

---

pkg/config/cleanup_server_config.go
pkg/controller/cleanup/cleanup.go

* Reverses the values from code recycle / code purge
* Validates that the time for recycle is shorter than purge
* Add documentation
```release-note
Ensure code status is retained for 14 days, but the code itself is zeroed at 48h
```

Flip the cleanup code lifetime values, document, & validate

---

pkg/clients/e2e.go
pkg/controller/certapi/certificate.go
pkg/controller/cleanup/cleanup.go
pkg/controller/issueapi/issue.go
pkg/controller/verifyapi/verify.go
pkg/observability/observability.go

The realm id is usually added to ctx much later in the function body. We
need the defer of observability.RecordLatency() at the beginning of the
function body to accurately record the latency.
Fixes #1180

Capture ctx pointer when recording latency.

---

pkg/database/database.go
pkg/database/database_util.go
pkg/database/migrations.go
terraform/database.tf
terraform/variables.tf

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1150
This enables pgaudit, but the migration succeeds if the extension isn't available (e.g. in dev/test) with a warning.
```release-note
**Warning!** - Enable and configure pgaudit. You **must** run the Terraform configuration changes _before_ deploying this commit with migrations.
```

Enable and configure pgaudit

---

pkg/controller/realmadmin/show.go

@jeremyfaller found this as part of https://github.com/google/exposure-notifications-verification-server/pull/1159, but we might spend more time on that, and I'd like to get this part of the fix into the next release.
```release-note
Stop processing after the controller returns an error in admin statistics pages.
```

Return on controller error

---

pkg/controller/admin/events.go
pkg/database/scopes.go

Fixes https://github.com/google/exposure-notifications-verification-server/security/code-scanning/7
```release-note
Lookup realm before passing in ID
```

Lookup realm before passing in ID

---

terraform/database.tf

The API accepts "all", but then saves it as "'all'" which causes a diff in Terraform.
```release-note
NONE
```

Quote pgaudit all for Cloud SQL

---

terraform/database.tf

This is rather frustrating... The API returns 'all', but specifying 'all' in the API call is valid but then points the instance in a bad state trying to apply the configuration change.
```release-note
NONE
```

Remove quotes around 'all'

---

pkg/controller/healthz.go

Part of https://github.com/google/exposure-notifications-verification-server/issues/1126
```release-note
Add scaffolding for query param alert
```

Add scaffolding for query param alert

---

cmd/server/assets/codes/bulk-issue.html

* Dates should be in ISO 8601.
* This question was asked over email, therefore it's nonobvious and should be there in the text.

Document date format

---

cmd/server/assets/codes/bulk-issue.html

Issue https://github.com/google/exposure-notifications-verification-server/issues/1197
* Adds a card for displaying errors from CSV upload
TODO:
Show # successful above the errors?
Button to download this as text?
```release-note
Include a table of errors for CSV bulk import
```

Add an error table to the csv results

---

pkg/database/migrations.go
pkg/database/vercode.go

```release-note
Fix missing column in migration for verification code statistics
```

Ensure external_issuer_id column exists

---

pkg/database/authorized_app.go

```release-note
Trim API key parts and log invalid signatures in debug
```

Trim API key parts and log invalid signatures in debug

---

terraform/main.tf

```release-note
Enable cloudidentity.googleapis.com in Terraform
```

Also enable cloudidentity.googleapis.com

---

pkg/database/realm.go
pkg/database/realm_user_stats.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1211
```release-note
Include user email addresses in stats export
```

Include email addresses in stats export

---

cmd/server/assets/codes/issue.html
cmd/server/assets/static/css/application.css
pkg/controller/codes/issue_test.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1212
```release-note
When SMS numbers are provided, clarify that the 6-8 digit codes are _backup_ codes.
```

Clarify backup code vs short code

---

cmd/server/assets/codes/issue.html

Turns out the library does this - we just needed to remove our placeholder...
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1213
```release-note
Internationalize SMS placeholder input
```

Internationalize SMS placeholder input

---

cmd/server/assets/login/login.html

Fixes #https://github.com/google/exposure-notifications-verification-server/issues/1214
* Add a link to the Google marketing page  for Exposure Notifications info / spec / docs
```release-note
Added an 'about' link to the login page
```

About link

---

cmd/apiserver/main.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1223
```release-note
Do not rate limit chaff requests
```

Do not rate limit chaff requests

---

docs/playbooks/alerts/StackdriverExportFailed.md

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1203

Add triage steps for StackdriverExportFailed alert

---

docs/api.md

* add some clarifying details about chaff requests
```release-note
DOCS: clarified usage of chaff requests from client perspective
```

update docs around sending chaff requests

---

cmd/server/assets/realmadmin/show.html
pkg/database/realm.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1221
```release-note
Display user and external stats as tables
```

Display user and external stats as tables

---

cmd/server/assets/admin/events/index.html
cmd/server/assets/codes/index.html
cmd/server/assets/realmadmin/events.html
cmd/server/assets/static/js/application.js

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1237
```release-note
Fix local time display helper edge cases (noon and midnight).
```

Let the browser do date math

---

internal/i18n/README.md

```release-note
Add docs on how to i18n
```

Add docs on how to i18n

---

cmd/apiserver/main.go
cmd/server/assets/realmadmin/show.html
docs/api.md
pkg/controller/middleware/chaff.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_stats.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1222
```release-note
Capture and display daily active user stats
```

Capture and display daily active user stats

---

terraform/service_appsync.tf
terraform/service_cleanup.tf
terraform/services.tf

Fixes #https://github.com/google/exposure-notifications-verification-server/issues/1092
* Add terraform config for the appsync service
* Looks a lot like the cleanup service. Another option would to be to make this a route of cleanup.
* Adds the appropriate URL for json
```release-note
Add terraform for setting up the mobile-app-sync cloud run service, scheduling, and URL config
```

Terraform for appsync

---

pkg/clients/responses.go
pkg/controller/appsync/appsync.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1242
* @flagxor added an app_name field today (although it does not yet exist in the export file). Take that as optional and prefer using that field to generating one.

accept app_name for mobile app sync

---

internal/i18n/locales/es/default.po

* Recreates Spanish i18n file with updated strings.
* Some translation comments 
* Verified `Exposure Notifications` translation by switching iPhone to Spanish.
* Translated `signing keys` as `llaves firmantes` this time, after plenty of feedback in a Spanish-speaking technology forum.
* Spanish uses the same word for `realm` and `kingdom`, which is probably not a good translation. `Ámbito` is frequently used as a translation for realm in Spain, other possibilities could be `dominio` or `universo`, but each one has its own ambiguity problems.
* `Short backup code` is a bit hard to translate; I focused more on the backup part (`código de respaldo`)
```release-note
NONE
```

Recreates Spanish i18n language file

---

pkg/controller/appsync/appsync.go

This can happen if apps aren't using our server, or in integration and test environments where not all regions are registered.
```release-note
Only warn on missing regions for appsync.
```

Only warn on missing regions

---

terraform/alerting/probers.tf

This probing is used in HostDown alert.

Adjust probe timeout to 10s.

---

Makefile

This is required because the incoming language files fail spellcheck.
```release-note
NONE
```

Only check spelling in Go and HTML files

---

internal/i18n/locales/fr/default.po

* Adding fr (French) i18n file
* Used "Notifications d'exposition au COVID-19" as a translation of "Exposure Notification" for consistency. This is what an Android phone set to French shows but this should really be "Notifications d'exposition à la COVID-19" (feminine vs. masculine)
* Used properly accentuated capital letters which. On some rare but poorly-configured devices these may show as weird characters instead.
```release-note
NONE
```

Adding fr i18n file

---

internal/project/datetime.go
internal/project/random.go
pkg/clients/e2e.go
pkg/controller/admin/events_test.go
pkg/controller/codes/issue.go
pkg/controller/codes/issue_test.go
pkg/controller/issueapi/issue_test.go
pkg/controller/issueapi/logic.go
pkg/controller/realmadmin/show.go
pkg/database/external_issuer_stats.go
pkg/database/realm_stats.go
pkg/database/realm_user_stats.go
pkg/database/token.go
pkg/database/token_test.go
pkg/database/vercode.go
pkg/database/vercode_test.go
pkg/integration/integration_test.go

Note that this does NOT do anything with dates in HTML, since those
dates tend to be formatted for style, not because of an API dependency.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1201
```release-note
Unify common date types into project helpers
```

Unify common date types into project

---

cmd/server/assets/codes/bulk-issue.html

* Uses the new batch-issue API for bulk code issaunce
* Batch size is 10 which should 10x the throttle on requests
* Start at 1 instead of 0 for line - non CS people probably start there.
```release-note
Move the Bulk Issue Codes UI to use the batch API
```

Use the new batch API for the bulk uploader

---

internal/i18n/locales/pt/default.po

* Adding Portuguese language translations.
* Small concern - ISO 639-1 doesn't differentiate between Brazilian and European Portuguese. I did Brazilian Portuguese, but I suspect there would be some differences in these phrases.
```release-note
Added Portuguese translations.
```

Add portuguese language translations

---

pkg/controller/context.go
pkg/database/database.go
pkg/observability/observability.go

* Fixes CodeQL isse: https://github.com/google/exposure-notifications-verification-server/security/code-scanning/8?query=ref%3Arefs%2Fheads%2Fmain
* Instead of converting a parsed uint64 to uint, just keep it around as uint64. No overflow logic needed

Keep uint as uint64 for observability

---

internal/i18n/README.md

Add clarity around terms
```release-note
Add clarity around terms for internationalization
```

Add clarity around terms

---

cmd/server/assets/realmadmin/stats.html
cmd/server/assets/static/js/application.js
cmd/server/assets/users/show.html
internal/routes/server.go
internal/routes/server_test.go
pkg/controller/user/controller.go
pkg/controller/user/create.go
pkg/controller/user/show.go
pkg/controller/user/stats.go
pkg/database/migrations.go
pkg/database/realm_test.go
pkg/database/user.go
pkg/database/user_stats.go
pkg/database/vercode_test.go

This moves to the pattern the realm has where stats are exposed via JSON and the chart just consumes that JSON. I also added help text and clarity to describe what the chart does (and does not) show.
```release-note
Add CSV and JSON exports for user stats
```

Add CSV and JSON exports for user stats

---

terraform/alerting/alerts.tf

Fixes #
* added second condition to fast error budget burn policy to improve reset time
* added second condition to slow error budget burn policy to improve reset time
```release-note
Improved SLO-based alerting reset time
```

Added conditions to error budget burn policies

---

cmd/server/assets/realmadmin/_form_codes.html
pkg/controller/realmadmin/settings.go
pkg/database/migrations.go
pkg/database/realm.go

* change SMS template to not be size constrained at the database
* up template max to 800 in software
* check expanded length
```release-note
The SMS Template max size is being doubled from 400 to 800.
```

change SMS max length

---

terraform/main.tf

This was already in the list...
```release-note
NONE
```

Don't enable cloudidentity twice

---

internal/i18n/locales/ja/default.po

* Add a Japanese (ja) translation
To make the service accessible to Japanese-speakers.
```release-note
- Japanese (ja) translation
```

Add Japanese (ja) locale

---

docs/link_handling.md
pkg/controller/associated/ios.go

Fixes #https://github.com/google/exposure-notifications-verification-server/issues/1299
* Use the older format for iOS Associated Domains
/hold to see if we can get confirmation from Apple on this (docs are confusing)
```release-note
Switch to older Associated Domains format for iOS
```

Switch to older associated domain format

---

pkg/controller/issueapi/logic.go

These are nearly always client errors
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1310
```release-note
Return 400 (instead of 500) on Twilio errors
```

Return 400 on Twilio errors

---

terraform/alerting/dashboards/verification-server.yaml

```release-note
Add SLO chart in Verificatoin Server dashboard.
```

Add an SLO chart in the Verification Server dashboard.

---

terraform/alerting/alerts.tf

It should alert on any export failure if it lasts more than 5min
(duration setting for this alert.)

Fix stackdriver export alert again.

---

cmd/server/assets/admin/sms/show.html
cmd/server/assets/realmadmin/_form_sms.html
pkg/controller/admin/sms.go
pkg/controller/admin/sms_test.go
pkg/controller/realmadmin/settings.go
pkg/controller/realmadmin/sms_test.go
pkg/database/database.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_test.go
pkg/database/sms_config.go
pkg/database/sms_from_number.go
pkg/database/sms_from_number_test.go
pkg/render/render.go
tools/seed/main.go

This gives system administrators the ability to define a list of available SMS phone numbers. When the system SMS configuration is shared with a realm, the realm can choose the phone number from which they want to send messages.
Not pictured: the 6 hours I spent fighting gorm.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1291
```release-note
Support multiple 'from' numbers for system SMS configs
```

Support multiple from numbers for system SMS configs

---

terraform/alerting/alerts.tf

The previous 5min of errors is too noisy.

Update StackdriverExportFailed alert duration to 15min.

---

cmd/server/assets/realmadmin/_form_codes.html
pkg/database/realm.go
pkg/database/realm_test.go

Fixes #1323 
Contributes towards #1296 
* Allow the short code and short expiration to appear in the ENX test message, still requires the long link though. This is a backup in case the link isn't clickable (improper universal link registration)
```release-note
Allow short code to be in the ENX SMS message.
```

allow short code to be in ENX SMS messages / link still required

---

pkg/controller/issueapi/issue_batch.go

This confused at least one developer...
```release-note
Return a more detailed error when bulk issue is not enabled
```

Return a more detailed error when bulk issue is not enabled

---

internal/routes/server.go

This route has been removed and a redirect for 2 major releases.
```release-note
Remove old /home route
```

Remove old /home route

---

terraform/alerting/alerts.tf

The rate window should be larger than the interval of the errors.
Currently we export to stackdriver every 2min, meaning if the export is
constantly failing, our calculated error rate with 1min window will have
the rate oscillating between 0 and 1, and thus we would never get an
alert with our alerting duration (each time the value reaches 0 the
timer to trigger the alert is reset).
Changing this to 5min window means the condition is "on" as soon as
there's a single export error and last at least 5min. The alert is
firing if the condition is "on" for >15min.

Change rate calculating window of StackdriverExportFailed alert.

---

cmd/server/assets/apikeys/show.html
cmd/server/assets/realmadmin/stats.html
cmd/server/assets/users/show.html

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1339
```release-note
Add more left padding to graphs for large y-axis numbers.
```

Add more padding to graphs

---

pkg/database/database_util.go
pkg/database/migrations.go
pkg/database/migrations_test.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1343
```release-note
Add test for ensuring database migration numbers are strictly increasing
```

Add test for ensuring migration numbers are up and to the right

---

terraform/alerting/slos.tf
terraform/alerting/variables.tf

SLO thresholds can be overriden using var.slo_thresholds_overrides
```release-note
Monitoring: Add Availability SLO alert to all Cloud Run services.
```

Add availability SLO alerts on all Cloud Run services.

---

pkg/controller/controller.go
pkg/controller/flash/flash.go
pkg/controller/login/signout.go
pkg/controller/middleware/auth.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1341
```release-note
Properly redirect to login page after session expiration. Previously the user would get an "Unauthorized" page.
```

Properly redirect to login when required

---

pkg/controller/middleware/firewall.go

* load realm correctly when using apikeys in the firewall module
```release-note
NONE
```

fix realm from firewall for apikeys

---

pkg/controller/codes/bulk_issue.go
pkg/controller/codes/bulk_issue_test.go

This is better than unauthorized since it probably means the user just picked the wrong realm from selection (or bookmarked the page).
```release-note
NONE
```

Redirect back if bulk upload is not enabled

---

pkg/controller/issueapi/logic.go
pkg/controller/issueapi/logic_test.go

Fixes #1358
* don't log phone numbers on SMS failure
```release-note
Don't log phone numbers on SMS failure.
```

scrub phone numbers

---

terraform/dos.tf

This rule seems to cause Content-Type:application/json requests to fail.

Exclude a rule in Cloud Armor.

---

cmd/server/assets/codes/issue.html
docs/api.md
internal/i18n/locales/de/default.po
internal/i18n/locales/en/default.po
internal/i18n/locales/es/default.po
internal/i18n/locales/fr/default.po
internal/i18n/locales/it/default.po
internal/i18n/locales/ja/default.po
internal/i18n/locales/pt/default.po
internal/i18n/locales/tr/default.po
pkg/api/api.go
pkg/controller/issueapi/logic.go
pkg/controller/middleware/csrf.go
pkg/database/realm.go
pkg/database/realm_test.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/1320
* If more than one SMS template is defined, allow the user to pick one
* Add a field to the issue API and compose with the given template
```release-note
Allow user to select an SMS template on code-issue. Add template label field to issueAPI.
```

Allow the issuer to select an SMS template

---

docs/api.md

Issue https://github.com/google/exposure-notifications-verification-server/issues/1350
* Adding additional docs about handling errors.
* This might be a moot point if we remove this API  
```release-note
Adding more docs
```

Add details about handling partial success

---

docs/api.md

* This shows the possible error codes for Issue. Many of them are shared with Verify, but they are slightly different
* We could dedup with a 'common error codes' table and then specific ones, but I suspect that would be confusing to readers who probably scroll to the specific API they are integrating.

Document error codes table for IssueResponse

---

docs/api.md
pkg/controller/issueapi/issue_batch.go

Issue https://github.com/google/exposure-notifications-verification-server/issues/1350
* Switch the outer error message of the batch-issue API to describe success/fail and how to view individual errors
* Should be clearer and guide developers to not trust the outer message and dive into individual failures. Especially if they don't see the docs.
```release-note
Clearer outer error message for batch issue API
```

Clearer outer error message for batch API

---

cmd/server/assets/realmadmin/_form_codes.html
pkg/database/audit_entry.go
pkg/database/audit_entry_test.go
pkg/database/authorized_app.go
pkg/database/authorized_app_stats_test.go
pkg/database/authorized_app_test.go
pkg/database/cleanup.go
pkg/database/cleanup_test.go
pkg/database/database_test.go
pkg/database/errors.go
pkg/database/external_issuer_stats_test.go
pkg/database/membership.go
pkg/database/membership_test.go
pkg/database/mobile_app.go
pkg/database/mobile_app_test.go
pkg/database/modeler_status_test.go
pkg/database/realm.go
pkg/database/realm_stats_test.go
pkg/database/realm_test.go
pkg/database/realm_user_stats_test.go
pkg/database/sms_config_test.go
pkg/database/sms_from_number_test.go
pkg/database/user.go
pkg/database/user_stats_test.go
pkg/database/user_test.go
pkg/database/vercode.go
pkg/database/vercode_test.go
pkg/otp/code_test.go

Fixes #1296
```release-note
Improve database test coverage
```

Improve test coverage for database package

---

cmd/enx-redirect/main.go
cmd/server/assets/400.html
cmd/server/main.go
go.sum
internal/routes/enx_redirect.go
pkg/controller/associated/android.go
pkg/controller/associated/android_test.go
pkg/controller/associated/associated_test.go
pkg/controller/associated/index.go
pkg/controller/associated/index_test.go
pkg/controller/associated/ios.go
pkg/controller/associated/ios_test.go
pkg/controller/redirect/helpers.go
pkg/controller/redirect/helpers_test.go
pkg/controller/redirect/index.go
pkg/controller/redirect/redirect.go
pkg/database/realm.go
pkg/render/json.go

Fixes #1380
```release-note
Do not return 500s from redirect service for missing realms
```
/assign @flagxor

Do not return 500s from redirect service for missing realms

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/server/assets/users/show.html
internal/routes/adminapi.go
internal/routes/apiserver.go
pkg/controller/user/update_test.go

No changes, just moving these around so we can use them more easily in tests
```release-note
NONE
```

Extract adminapi and apiserver routes into internal/

---

cmd/server/assets/realmadmin/_form_general.html
pkg/controller/middleware/chaff.go
pkg/controller/realmadmin/settings_modify.go
pkg/database/migrations.go
pkg/database/realm.go

Part of #1393
There's some HTML changes to the stats page that need to happen, but I'll do that in the next PR because it'll be a bunch of whitespace changes. This is the 🍖.
```release-note
Make daily active stats collection a realm configurable
```

Make daily active stats collection a realm configurable

---

cmd/server/assets/users/import.html
internal/auth/firebase.go
pkg/controller/user/create.go
pkg/controller/user/importbatch.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1394
* Only send the password-reset email if the firebase user does not exist
* Count users added to realm, not created in firebase
```release-note
Users added to realm don't get password reset email - only newly created firebase users do
```

Only send welcome email for new firebase user

---

docs/api.md

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1383
Issue https://github.com/google/exposure-notifications-verification-server/issues/1321
* Add a note about client-provided UUIDs to docs

Add a note about client-provided UUIDs

---

pkg/controller/issueapi/issue_batch.go
pkg/database/realm.go

* We currently perform this check on the bulk-issue page rendering, but we also need to check the API
```release-note
RBAC check for BulkIssue on the API
```

Add RBAC check to issue_batch api

---

cmd/server/assets/realmadmin/_stats_codes.html
cmd/server/assets/realmadmin/_stats_daily_active_users.html
cmd/server/assets/realmadmin/_stats_external_issuers.html
cmd/server/assets/realmadmin/_stats_users.html
docs/api.md
internal/routes/adminapi.go
internal/routes/server.go
internal/routes/server_test.go
pkg/controller/middleware/membership.go
pkg/controller/stats/realm.go
pkg/controller/stats/realm_external_issuer.go
pkg/controller/stats/realm_user.go
pkg/controller/stats/stats.go
pkg/database/realm.go
pkg/database/realm_test.go

Part of #1390
```release-note
Add statistics endpoints to adminapi
```

Add statistics endpoints to adminapi

---

cmd/server/assets/apikeys/index.html
cmd/server/assets/apikeys/new.html
cmd/server/assets/apikeys/show.html
docs/api.md
internal/routes/adminapi.go
pkg/controller/apikey/create.go
pkg/controller/middleware/apikey.go
pkg/database/authorized_app.go
pkg/database/authorized_app_test.go
tools/seed/main.go

Fixes #1390
```release-note
Introduce a new API key type for accessing statistics. The statistics endpoints of the admin API are currently in preview and are subject to change.
```

Add API key type for accessing statistics

---

terraform/alerting/module.availability-slo/main.tf

Services like enx-redirect responds a lot 3xx.

Also includes 3xx responses as part of the good SLI signal.

---

pkg/database/sms_config.go
pkg/sms/noop.go
pkg/sms/sms.go

* Create a no-op SMS provider that only throws an error
* This will be used later in unit test cases to assert what happens when an SMS fails
* (Pulling out easily reviewable pieces from a larger refactor)

Create a no-op failure SMS provider

---

pkg/controller/user/update_test.go
pkg/rbac/rbac.go
pkg/rbac/rbac_test.go

Fixes #1408 
* All write permissions automatically add required read permissions if they are not set.
```release-note
Setting write permissions automatically add required read permissions.
```

Add implied permissions - write permissions need read permissions to be useful

---

docs/api.md
internal/routes/adminapi.go

Don't allow admin API keys to read stats

---

terraform/alerting/variables.tf
terraform/mirror/variables.tf
terraform/variables.tf

This release contains https://github.com/hashicorp/terraform-provider-google/pull/8006 that fixed the linked issue.

Update google provider to 3.51

---

pkg/cache/config.go
pkg/cache/redis.go
pkg/redis/config.go

Configurable via an envvar. Default is 1s.
```release-note
Wait for Redis connections to become available
```

Wait for Redis connections to become available

---

scripts/ci-terraform.sh
terraform-e2e-ci/.terraform.lock.hcl

Prior to terraform0.14 this was fine, but now terraform destroy isn't happy that the database instance exists in terraform state but not physically exist in GCP

Terraform destroy first remove database from state

---

docs/api.md
pkg/api/api.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/issue_batch.go
pkg/controller/issueapi/issue_batch_test.go
pkg/controller/issueapi/issue_test.go
pkg/controller/issueapi/logic.go
pkg/controller/issueapi/parse_date_test.go
pkg/integration/integration_test.go
pkg/testsuite/clients.go

* Integration test for a few failures of issue-code
* Adds an error code for symptom/test dates that are parsable but rejected - too old
```release-note
added more test coverage of issue error cases
added error code 'invalid_date' for dates older the allowed for the realm
```

Test for single issue code

---

cmd/server/assets/users/_form.html
pkg/controller/user/update_test.go
pkg/database/membership.go

- Add help text that explains permissions and how they work
- Add membership.Cannot, which makes templates easier
- Checking a permission with implied permissions automatically checks
the implied ones and adds a little notice
- Don't allow the current user to select permissions that they lack
(this was already enforced server-side)
```release-note
Improve UX on permissions selection
```

Improve UX on permissions selection

---

cmd/e2e-runner/main.go
pkg/clients/apis.go
pkg/clients/e2e.go
terraform/service_e2e_runner.tf

* e2e runner is currently failing due to wrong path name in e2e client
* separate out batch-issue to separate handler w/ independent schedule so we can monitor separate
* ensure realm is set up correctly for bulk issue when e2e runner starts
```release-note
end to end test runner now tests bulk issue in a separate handler and scheduler
```

separate batch-issue from other e2e flows

---

pkg/controller/apikey/disable_test.go
pkg/controller/apikey/enable_test.go
pkg/controller/apikey/show_test.go
pkg/controller/apikey/update_test.go

This gives us more control over the response assertions.
```release-note
NONE
```

Use regular mux for testing not-found scenarios

---

pkg/controller/email.go
pkg/controller/login/reset_password.go
pkg/controller/login/verify_email_send.go
pkg/controller/user/create.go
pkg/controller/user/importbatch.go
pkg/controller/user/reset_password.go

* Use the current membership's realm for email templates
* Require UserWrite rbac for reset password
```release-note
require UserWrite for admin reset of another user's password
```

Use realm from current membership for emails

---

pkg/controller/login/reset_password.go
pkg/database/user.go

* Password reset occurs from a context that has no auth set and we allow realms to localize the email templates if using their own SMTP server
* Select the first available membership realm for password reset so the user can get a localized email.
* Not idea for members of many realms, but that is not expected for most users 
```release-note
Select a realm-localized template for reset password
```

Use first available membership for password reset

---

pkg/controller/associated/index.go
pkg/controller/redirect/index.go

* This should be less errorprone as net.SplitHostPort understands more complex combinations which include zone, less maintenance for us

Prefer net split over custom indexof

---

pkg/controller/certapi/certapi.go
pkg/controller/certapi/certificate.go

* Change unhandled unknown errors to StatusServerInternal 500
* Log at Info for 400 level errors
* de-duplicate some double logging
```release-note
Modify error message levels for CertAPI
Change unhandled errors to StatusServerInternal
```
/hold

Change some error levels for certificate api

---

cmd/server/assets/codes/bulk-issue.html

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1442
* Show first 50 success / error cases with uuid for bulk-issue
* After 50 we stop showing them in the card for (potentially) very large lists
* 50 was arbitrarily chosen, but we don't want the browser to be overwhelmed in large cases
* Update a file-download link with a full CSV formatted receipt of the issuance.
```release-note
Show first 50 success / error cases for bulk-issue with UUIDs
Allow download of log file for bulk-issue
```

Show success UUIDs and provide file receipt for bulk-issue

---

cmd/server/assets/codes/bulk-issue.html
cmd/server/assets/static/js/application.js
cmd/server/assets/users/import.html

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1459
* The code currently assumes each line is in-order and uses index to show line number. However we skip blank or empty lines of the file which results in off-by-one.
* This fixes that by keeping an array of line numbers.
* Also consolidates string calculation for the href download
```release-note
Fix off-by-one line numbers for bulk uploader
```

Fix potentially incorrect line numbers

---

.github/workflows/codereview.yaml
Makefile
cmd/e2e-runner/main.go
go.mod
go.sum
tools/tools.go

This leverages a static analysis tool I wrote to find and alert when we misuse the logger.
```release-note
Add zapw to detect misuse of logger
```
/hold

Add zapw to detect misuse of logger

---

pkg/controller/certapi/certapi.go

* example flake: https://oss-prow.knative.dev/view/gs/oss-prow/pr-logs/pull/google_exposure-notifications-verification-server/1464/pull-en-server-release-unit/1343646210786856960
* The standard ParseWithClaims fails if !claims.Valid() but we continue on and check for that ourselves too. This resulted in the test failing with the wrong error message.
* Why does this only fail sometimes? I am not sure.

An odd test flake in integration_e2e

---

cmd/server/assets/mobileapps/_app.html
cmd/server/assets/mobileapps/show.html
pkg/controller/mobileapps/create.go
pkg/controller/mobileapps/update.go
pkg/controller/mobileapps/update_test.go
pkg/controller/redirect/appstore.go
pkg/controller/redirect/helpers.go
pkg/controller/redirect/helpers_test.go
pkg/controller/redirect/index.go
pkg/controller/redirect/index_test.go
pkg/database/migrations.go
pkg/database/mobile_app.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1463
```release-note
Give admins the ability to disable AppStore redirects for apps
```
/cc @mikehelmick

Give admins the ability to disable AppStore redirects

---

cmd/adminapi/main.go
cmd/apiserver/main.go
cmd/appsync/main.go
cmd/cleanup/main.go
cmd/e2e-runner/main.go
cmd/enx-redirect/main.go
cmd/migrate/main.go
cmd/modeler/main.go
cmd/server/main.go

This commit adds panic recovery, logs the error, then exits non-zero. Note that the container still exits with logger.Fatal, we just ensure the log is captured first.
```release-note
Recover from panics in main
```

Recover from panics in main

---

cmd/server/assets/mobileapps/index.html
cmd/server/assets/mobileapps/show.html

*  Add the OS to the mobile_apps index table
* In real life folks seem to have the same name for their iOS app and Android. Eg. Covidwise.  It's impossible to tell which is which from the index page.
```release-note
Display OS on the mobile apps index table
```

Display OS on the mobile apps index table

---

pkg/controller/login/register.go
pkg/controller/middleware/mfa.go
pkg/database/membership.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/user.go

This changes the MFA grace period calculation to calculate against the date on which the user was added to the realm vs the date on which the user was created. All membership creation dates are backfilled to NOW().
```release-note
Calculate grace periods from membership date
```

Calculate grace periods from membership date

---

cmd/server/assets/login/login.html
cmd/server/assets/static/js/application.js

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1305
* Previously we protected the entire login flow with recaptcha, but it is only required for SMS send. Unfortunately the recaptcha reset-on-failure does not appear to work (on not-localhost).
Instead we load the recaptcha an only render it after successful sign-in with username/password for the SMS send.  
```release-note
Don't load captcha unless SMS factor needed
```

Late load recaptcha - only require for 2nd factor SMS

---

pkg/controller/certapi/certificate.go
pkg/controller/codes/issue_test.go
pkg/controller/verifyapi/verify.go
pkg/database/authorized_app_stats.go
pkg/database/migrations.go
pkg/database/realm_stats.go
pkg/database/token.go
pkg/database/token_test.go
pkg/database/vercode.go
tools/seed/main.go

This adds additional statistics collection for the following data:
- `codes_invalid` - a code is expired or doesn't exist in our database
- `token_claimed` - a token successfully exchanged with a cert
- `token_invalid` - a token failed to exchange with a cert (invalid claims, etc)
```release-note
Collect invalid codes and token statistics (backend only)
```

Collect invalid codes and all token statistics

---

pkg/database/token.go

The current stats are bound to the tx, which means they don't get incremented if the tx fails for any reason (including NotFound). This moves them out of the request path.
```release-note
Move stats calculations to be out-of-band
```

Move stats incrementing to be out-of-band

---

internal/routes/adminapi.go
internal/routes/apiserver.go
internal/routes/enx_redirect.go
internal/routes/server.go
pkg/controller/healthz.go
pkg/testsuite/integration.go
terraform/alerting/probers.tf

The previous logic relied on creating a new database connection. This would be a different database connection from the one the rest of the app is using, and could lead to false successes. This changes the health endpoint to use the same db that the other handlers use.
Additionally, since it's just a ping now (instead of a full config parsing), the limit is increased from 1/min to 1/sec. The response code when the limit is exceeded is now a 429 instead of silently falling through to 200.
Finally, the monitoring uptime checks are updated to use this endpoint instead of the generic /health. It's safe to say that the service is "down" if it cannot connect to the database.
```release-note
Ping db on /health instead of opening new connection
```
/assign @yegle 
/assign …

Ping db on health instead of opening new connection

---

terraform/alerting/probers.tf

This is required because Terraform configs are run from HEAD, but the previous tag (0.18.5) is not compatible with this change. We can re-add this after 0.19 is tagged and ready.
```release-note
Temporarily disable database service check due to incompatibility between releases
```

Temporarily don't check database connection

---

go.mod
pkg/controller/healthz.go

Since this is just a ping, rate limiting this is no longer required.
```release-note
Do not rate limit health checks
```

Do not limit health checks

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_appsync.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_modeler.tf
terraform/service_redirect.tf
terraform/service_server.tf
terraform/variables.tf

Part of https://github.com/google/exposure-notifications-verification-server/issues/895
```release-note
Breaking: To continue using the Terraform module, the following input variable is needed to avoid introducing a diff:
service_annotations = {                                                       
adminapi     = { "autoscaling.knative.dev/maxScale" : "1000" }
apiserver    = { "autoscaling.knative.dev/maxScale" : "1000" }
appsync      = { "autoscaling.knative.dev/maxScale" : "1000" }
cleanup      = { "autoscaling.knative.dev/maxScale" : "1000" }
e2e-runner   = { "autoscaling.knative.dev/maxScale" : "1000" }
enx-redirect = { "autoscaling.knative.dev/maxScale" : "1000" }
modeler      = { "autoscaling.knative.dev/maxScale" : "1000" }
} 
```

Refactor Cloud Run annotations in Terraform config.

---

terraform/alerting/module.latency-alert/main.tf
terraform/alerting/module.latency-alert/variables.tf
terraform/alerting/slos.tf

Fixes #
* loosened default latency SLO target
* added latency-alert module
* added per-service toggles for latency alerts
* added per-service toggles for latency SLOs
```release-note
Latency alerting done via threshold, rather than SLO
```

Simplify latency alerting

---

pkg/controller/codes/expire.go
pkg/controller/issueapi/issue_test.go
pkg/controller/issueapi/validate_code.go
pkg/database/duration.go

* A shadowed variable causes smsProvider to be nil and therefore LongCodeExpiry is set to the short expiry
* Added a test case to prevent regression
```release-note
Fix for long code expiry being set to short code expiry
```

Fix and test for regression for long code expiry

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_appsync.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_modeler.tf
terraform/service_redirect.tf
terraform/service_server.tf
terraform/variables.tf

There are two types of annotations per Knative spec. See the inline
comment on the difference.
Part of #895 
```release-note
Breaking: To continue using the Terraform module, the following input variable is needed to avoid introducing a diff:
revision_annotations = {                                                       
adminapi     = { "autoscaling.knative.dev/maxScale" : "1000" }
apiserver    = { "autoscaling.knative.dev/maxScale" : "1000" }
appsync      = { "autoscaling.knative.dev/maxScale" : "1000" }
cleanup      = { "autoscaling.knative.dev/maxScale" : "1000" }
e2e-runner   = { "autoscaling.knative.dev/maxScale" : "1000" }
enx-redirect = { "autoscaling.knative.dev/maxScale" : "1000" }
modeler      = { "autoscaling.knative.dev/maxScale" : "1000" }
} 
```

Separate Cloud Run Service & Revision annotations for terraform

---

cmd/server/assets/login/register-phone.html
cmd/server/assets/static/js/application.js

* We already reset the recaptcha on flows where we `catch` an error post-sms send. This adds it for the recaptcha callbacks that occur when it expires (if you leave the page sitting open for a long time).
I'm still trying to track down connection issues with recaptcha on not-localhost. Firebase automatically handles the recaptcha keys and I'm wondering how that works with the custom domain - I'll try to find more information there.

Reset recaptcha on expire

---

pkg/controller/cleanup/cleanup.go

Saw this in logs
```release-note
Only emit an error when shouldCleanup actually fails
```

Only emit an error when shouldCleanup actually fails

---

pkg/controller/modeler/modeler.go

These shouldn't be warnings
```release-note
Switch modeler logs to debug
```

Switch modeler logs to debug

---

pkg/database/realm.go
pkg/database/realm_test.go

If a user inputs an invalid UUID, postgres returns an error. This catches that by parsing the UUID in advance.
```release-note
Return NotFound for invalid UUIDs
```

Return NotFound for invalid UUIDs

---

internal/clients/clients.go

* If our e2e test receives an error that is not in the format of the expected response struct, we fail to decode it. This allows us to see the raw string within the error message.

Show raw error body if unmarshal fails

---

docs/playbooks/alerts/CloudSchedulerJobFailed.md
terraform/alerting/alerts.tf

```release-note
Monitoring: Add ClouldSchedulerJobFailed alert.
```

Add a CloudSchedulerJobFailed alert based on log metric.

---

.github/workflows/codereview.yaml
cmd/server/assets/static/js/application.js
cmd/server/assets/users/index.html
internal/routes/server.go
pkg/controller/user/bulk_permissions.go
pkg/controller/user/index.go
pkg/database/bulk_permission.go
pkg/database/bulk_permission_test.go
pkg/database/scopes.go
pkg/database/scopes_test.go
pkg/rbac/rbac.go

This change has two major parts: advanced searching and bulk permission management.
**Advanced searching**
Advanced searching is a new feature for user search that allows for more granular searching. It's backwards-compatible with the former search syntax, but now includes the ability to filter searches by fields. Specifically, you can now query like "name:foo" or "can:APIKeyWrite" to perform advanced queries. Advanced searching is useful for bulk permission management. For example, I can search for all users that have a particular permission, then click the checkboxes next to the names that should have said permission, then remove it in a single form.
**Bulk permission management**
Bulk permission management is a new feature that allows people with UserWrite permissions to modify other …

Introduce advanced search and bulk permissions

---

internal/clients/clients.go
pkg/database/migrations.go

* Never rollback the code and long_code fields to be shorter - this would lose data
* Check the content-type header when decoding JSON and give a more detailed response if unexpected type

Nits: never rollback code sql type, check content-type header

---

cmd/server/assets/static/js/application.js

* Show the error and line if we skip an entry with < 2 items or no phone number
* Skip reuploading conflicts (which will conflict again) and successes (which will now conflict). The user can still do so if they clear the error code, but if re-using the log CSV which keeps error columns we want to skip those. This will also make correcting errors and re-uploading faster.
```release-note
The bulk-uploader will skip conflict or already-succeeded lines when re-using a log csv from a previous attempt
```

Skip conflict and already succeeded lines of csv retries

---

cmd/server/assets/codes/bulk-issue.html
cmd/server/assets/static/js/application.js

* Currently `TestType` is hard-coded to "confirmed"
* Allows an optional field to provide another value, remains "confirmed" if omitted
```release-note
Support testType field as input for bulk-upload
```

Support testType field as input for bulk-upload

---

pkg/database/migrations.go

/cc @bschlaman 
```release-note
Drop foreignkey constraints if they already exist before creating
```

Drop FK constraints if they already exist before creating

---

terraform/alerting/module.availability-slo/main.tf
terraform/alerting/module.availability-slo/variables.tf
terraform/alerting/module.latency-slo/main.tf
terraform/alerting/module.latency-slo/variables.tf
terraform/alerting/slos.tf

Fixes #
* Availability SLO for apiserver only, only with fast burn alert
* Latency alerts for adminapi and server only
* Added toggles to separately enable fast and slow burn alerts
```release-note
Simplified alerting configuration to accommodate low-traffic services
```

Simplify alerts

---

pkg/api/api.go
pkg/controller/issueapi/handle_issue_batch.go

* Adds padding to the batch API request / repsonse
* Initializes padding of the inner IssueRequest
* Change the custom marshaller to ignore already-initialized padding
* We add `omitempty` to the standard IssueResponse (so the batch doesn't get it), but in practice all single-issue calls will have the padding

Pad batch requests and eliminate inner padding

---

Makefile
scripts/presubmit.sh

* fix lint / static check errors on test mains
* add test coverage output to presubmit script
```release-note
DEV: Overall test coverage displayed on presubmit.
```

fix lints. Add presubmit overall test coverage output

---

pkg/api/api.go
pkg/controller/issueapi/handle_issue_batch.go
pkg/integration/integration_test.go

* @mikehelmick was right and I should have tested this. **https://github.com/google/exposure-notifications-verification-server/pull/1539** added `omitempty` to the json response which causes MarshalJSON to never be called to begin with
* Corrected and added test
* The downside is we do get inner `padding:""` for batch, but that's not the worst thing
```release-note
correct padding
```

Fix padding

---

cmd/server/assets/static/js/application.js
docs/api.md

* Followup to https://github.com/google/exposure-notifications-verification-server/pull/1541
* Create the padding in the outer request for batch, not on each item
* Add field to docs
```release-note
Use outer padding for bulk-uploader client
```

Switch the batch uploader client to outer padding

---

internal/clients/clients.go
pkg/config/appsync_server_config.go

```release-note
Log URLs and response codes in appsync errors, increase max size to 64kb
```

Log URLs and response codes in appsync errors, increase max size to 64kb

---

internal/clients/clients.go

This is required so that ResolveReference resolves relative to the provided path.
```release-note
Remove leading slash in clients
```

Remove leading slash in clients

---

cmd/server/assets/login/register-phone.html
cmd/server/assets/login/verify-email.html
internal/routes/server.go
pkg/controller/login/change_password.go
pkg/controller/login/controller.go
pkg/controller/login/login.go
pkg/controller/login/login_test.go
pkg/controller/login/post_authenticate.go
pkg/controller/login/post_authenticate_test.go
pkg/controller/login/select_realm.go
pkg/controller/user/delete.go

This removes the assumption that users have permission to issue codes.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1548
```release-note
Add intelligence for redirecting post-login
```

Add intelligence for redirecting post-login

---

internal/project/random.go
internal/project/random_test.go

* Use hex encoding instead of crypto hash - this isn't really hashing anything meaningfully
* sha.sum256 meant this function doesn't really return a `len int` length string 
* Bring coverage numbers up

Cover random number gen

---

cmd/server/assets/realmadmin/_form_email.html
internal/project/context_test.go
pkg/controller/realmadmin/settings_modify.go

* Adds password-reset and email-verification email templates into the email realm settings
* We've got all the db fields wired up
* 
```release-note
Add password-reset and email-verification email templates to realm settings
```

Add other email templates to the realm settings UI

---

pkg/controller/jwks/jwks.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1554
* Give not-found or invalid-request for malformed or missing realm_id
```release-note
not-found and invalid for malformed realm_id in jwks request
```

Bad request for jwks invalid region

---

docs/playbooks/alerts/HumanAccessedSecret.md
docs/playbooks/alerts/HumanDecryptedValue.md
terraform/alerting/alerts.tf
terraform/alerting/monitoring.tf
terraform/alerting/variables.tf

Part of https://github.com/google/exposure-notifications-verification-server/issues/1389
We still need to figure out how to handle the situation where humans are running Terraform. 
```release-note
Fire alerts when humans do secret things
```

Fire alerts when humans do secret things

---

terraform/redirect-lb.tf
terraform/services.tf
terraform/variables.tf

* Allow for adding new enx-redirect domains through additive SSL certs rather than causing an outage
```release-note
ENX redirect, add new sub-domains without outage.
```
/hold

allow for redirect cert changes without outages

---

pkg/database/pagination.go
pkg/database/realm.go
pkg/database/realm_test.go
pkg/database/scopes.go

- Fixes https://github.com/google/exposure-notifications-verification-server/issues/1564
- Fixes https://github.com/google/exposure-notifications-verification-server/issues/1562
```release-note
Defensively check `deleted_at fields in realm/user join tables for memberships
```

Defensively check deleted_at fields in realm/user join tables for memberships

---

cmd/server/assets/static/js/application.js
pkg/api/api.go
pkg/controller/issueapi/send_sms.go
pkg/sms/twilio.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1568
* Adds a util method to sms to test if an error is a Twilio code
* Check for 21611 and give that a special response code
* Cancel bulk-uploader if we see `sms_queue_full`
```release-note
Stop bulk-issue client if the Twilio SMS queue is full
```

Stop issuing codes if the twilio SMS queue is full

---

builders/build.yaml
scripts/build
terraform/binary_authorization.tf
terraform/main.tf
terraform/variables.tf

This adds Binary Authorization enforcement for Cloud Run services. It requires services to be built and deployed by Cloud Build, reducing insider risk. This change will be inapplicable to projects that are not enrolled in the Cloud Run Binary Authorization preview (noop). You can request access at https://docs.google.com/forms/d/e/1FAIpQLSehF8FfPFtf6xlzIhPiN8jggZ2hn3SgOV8CGYWejSRAJYiBpA/viewform.
```release-note
Add Binary Authorization enforcement for Cloud Run
```

Add Binary Authorization for Cloud Run

---

pkg/api/android.go
pkg/api/ios.go
pkg/controller/associated/android.go
pkg/controller/associated/index.go
pkg/controller/associated/ios.go

This resolves a future circular dependency, but it's also probably the better place for this anyway. There's a slight renaming to prevent ambiguity.
```release-note
Move associated site data responses into api package
```

Move associated site data responses into api package

---

terraform/main.tf

```release-note
Add Binauthz envvars to Terraform builder
```

Add Binauthz envvars to Terraform builder

---

cmd/server/assets/codes/issue.html
pkg/api/api.go
pkg/controller/issueapi/handle_issue.go
pkg/controller/issueapi/send_sms.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1581
* Marshal json with ErrorReturn struct rather than the IssueResponse struct, although identical they differ in that ErrorReturn does not include `OmitEmpty`
* Add an error code `sms_failure` for generic Twilio errors

Marshal errors with *ErrorReturn type

---

cmd/e2e-runner/main.go
docs/production.md
internal/clients/clients.go
internal/clients/e2e.go
internal/clients/enx_redirect.go
internal/envstest/bootstrap.go
pkg/config/e2e_runner_server_config.go
terraform/service_e2e_runner.tf
tools/e2e-test/main.go

Part of https://github.com/google/exposure-notifications-verification-server/issues/1574
```release-note
Add optional enx-redirect tests to e2e-runner
```

Add optional enx-redirect tests to e2e-runner

---

internal/clients/adminapi.go
internal/clients/apiserver.go
internal/clients/appsync.go
internal/clients/clients.go
internal/clients/enx_redirect.go
terraform/main.tf

Also a small Terraform issue
```release-note
Don't return http.Response when unneeded
```

Don't return http.Response when unneeded

---

internal/envstest/bootstrap.go
internal/envstest/integration.go

If you look at any e2e realm, there's hundreds of API keys (and soon mobile apps). Even though we do mark them for deletion, it takes 14 days to cleanup. The e2e-runner executes every 15min.
To mitigate this, I propose actually deleting the API keys in the e2e runners. Since this is really specific to the e2e-runner, I intentionally did NOT add this to the core database package. I don't want anyone or anything else using it.
```release-note
Actually delete e2e API keys and mobile apps
```

Actually delete e2e API keys and mobile apps

---

terraform/variables.tf

The limit was set to low so it doesn't cause too much spending when
running as a dev env. Set it to 1 will cause brief downtime in some edge
cases.

Set maxScale to 2.

---

pkg/config/appsync_server_config.go
pkg/controller/appsync/appsync.go
pkg/controller/appsync/appsync_test.go
pkg/database/cleanup.go

* ensure app sync doesn't run too frequently
```release-note
App sync will run no more than once every 5 minutes, controlled via database.
```

add locking to appsync handler

---

pkg/config/certificate_signing_config.go
pkg/database/migrations.go
pkg/database/realm.go

forst towards: #1567
* Add DB column for realm auto verification certificate key rotation
* Add config feature flag that will control this - default to OFF at a system level
```release-note
Adds database column for realm level auto key rotation settings.
```

add database columns and config for feature flag

---

pkg/database/pagination.go
pkg/pagination/pagination.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1595
* Page 0 does funny things with a negative uint64 overflow

Pagination starts at page 1

---

builders/build.yaml
builders/deploy.yaml
builders/promote.yaml
cmd/rotation/main.go
pkg/config/cleanup_server_config.go
pkg/config/rotation_config.go
pkg/controller/cleanup/cleanup.go
pkg/controller/cleanup/cleanup_test.go
pkg/controller/rotation/handle_rotate.go
pkg/controller/rotation/handle_rotate_test.go
pkg/controller/rotation/metrics.go
pkg/controller/rotation/rotation.go
pkg/controller/rotation/rotation_test.go
pkg/controller/verifyapi/verify.go
pkg/database/migrations.go
pkg/database/token_signing_keys.go
pkg/database/token_signing_keys_test.go
terraform/service_rotation.tf

This adds a new service, rotation, which handles key and rotation events. It's designed to be invoked via Cloud Scheduler and has its own locking and time intervals. It's conceptually similar to the cleanup job.
This also adds the database schema and example rotation for token signing keys. Note that this code is NOT in use in main code paths yet.
There's some TODOs in the code assigned to me. I intend to do those in follow-up PRs where all of this will be wired together.
Part of https://github.com/google/exposure-notifications-verification-server/issues/1569
```release-note
Add rotation service and schema for rotating token signing keys
```

Add rotation harness and rotate token signing keys

---

pkg/database/token_signing_keys.go
pkg/database/token_signing_keys_test.go

```release-note
Add audits for saving a Token Signing Key
```

Add audits for saving a Token Signing Key

---

builders/build.yaml
builders/deploy.yaml
builders/promote.yaml
cmd/stats-puller/main.go
internal/routes/adminapi.go
internal/routes/server.go
pkg/config/stats_puller_config.go
pkg/controller/stats/stats.go
pkg/controller/statspuller/handle_pull.go
pkg/controller/statspuller/statspull.go
terraform/alerting/slos.tf
terraform/service-stats-puller.tf

* Adds all the boilerplate for a new service
* build, deploy, promo scripts
* main entry point
* config file
* controller which is currently a no-op
*  terraform script for accounts, service, and cloud-scheduler (hourly)
[see Seth's similar PR for rotation](https://github.com/google/exposure-notifications-verification-server/pull/1597)
```release-note
Adds the stats-puller service to run every hour.
```

Add stats-puller harness

---

pkg/controller/appsync/appsync.go
pkg/controller/cleanup/handle_cleanup.go
pkg/controller/rotation/handle_rotate.go

Cloud Scheduler considers a 429 to be a "failure" and thus sets off our alerting. I think it also makes sense for the background jobs to return a successful status response in this case, because the request was wholly processed.
```release-note
Return a success response on remote workers when no work is done
```

Return a success response on remote workers when no work is done

---

cmd/server/assets/admin/events/index.html

This isn't relevant in realm logs since all records are tied to that realm, but for system event logs, it's important to know upon which realm the action took place.
We can't lookup the actual realm here safely because the realm_id is "0" for system events. Also realm names can change but IDs are stable.
```release-note
Display realm_id in system admin event logs
```

Display realm_id in system admin event logs

---

pkg/config/appsync_server_config.go
pkg/config/cleanup_server_config.go
pkg/config/stats_puller_config.go
pkg/controller/appsync/appsync.go
pkg/controller/appsync/appsync_test.go
pkg/controller/appsync/controller.go
pkg/controller/cleanup/cleanup.go
pkg/controller/cleanup/handle_cleanup.go
pkg/controller/cleanup/handle_cleanup_test.go
pkg/controller/rotation/handle_rotate.go
pkg/controller/rotation/handle_rotate_test.go
pkg/controller/statspuller/handle_pull.go
pkg/database/cleanup.go
pkg/database/lock.go
pkg/database/lock_test.go
pkg/database/migrations.go

* Adds the db lock to the stats-puller service
* Shares the `SyncFoo` function each of these has defined
* Renames `Cleanup` to `Lock` except for CleanupStatus - that's in the db schema
```release-note
Add locking to stats-puller service. Refactor cleanup -> lock
```

Add db lock to stats-puller service. Share 'Should<servicename>' func

---

pkg/database/migrations.go

* This was a find/replace mistake in https://github.com/google/exposure-notifications-verification-server/pull/1608. We don't want to change already-run migration IDs

Put migration name back

---

cmd/cleanup/main.go
cmd/rotation/main.go
cmd/server/assets/admin/info.html
docs/production.md
internal/envstest/apiserver.go
internal/envstest/integration.go
internal/routes/apiserver.go
pkg/config/api_server_config.go
pkg/config/token_signing_config.go
pkg/controller/admin/caches.go
pkg/controller/admin/info.go
pkg/controller/certapi/certapi.go
pkg/controller/certapi/certificate.go
pkg/controller/rotation/handle_rotate.go
pkg/controller/rotation/handle_rotate_test.go
pkg/controller/verifyapi/verify.go
pkg/controller/verifyapi/verifyapi.go
pkg/database/migrations.go
pkg/database/token_signing_keys.go
pkg/database/token_signing_keys_test.go
terraform/alerting/slos.tf
terraform/service_rotation.tf
terraform/services.tf
tools/seed/main.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1569
```release-note
**Potentially breaking!** Source token signing keys from the database. This completes the move of system token signing keys from environment variables to the database. This change attempts to be backward compatible, but server are encouraged to test changes in an isolated environment before upgrading production systems.
```

Source token signing keys from the database

---

cmd/server/assets/realmadmin/_form_codes.html
cmd/server/assets/realmadmin/_form_general.html
pkg/config/token_signing_config.go
pkg/controller/realmadmin/express_disable.go
pkg/controller/realmadmin/express_enable.go
pkg/controller/realmadmin/settings_modify.go
pkg/controller/realmadmin/settings_show.go
pkg/database/key_server_stats.go
pkg/database/key_server_stats_test.go
pkg/database/migrations.go

*  Key Server Stats database model
* Realm settings UI to set or delete the value
```release-note
New tables for storing key-server statistics
```

DB model for storing key server stats

---

internal/project/errors.go
pkg/controller/cleanup/handle_cleanup.go
pkg/controller/rotation/handle_rotate.go

[]error does not actually marshal and you end up with an empty array
with no errors
```release-note
NONE
```

Make sure return results are []string

---

cmd/server/assets/realmadmin/_form_general.html
pkg/config/cleanup_server_config.go
pkg/controller/cleanup/handle_cleanup.go
pkg/controller/middleware/template.go
pkg/database/key_server_stats.go
pkg/database/key_server_stats_test.go

* Deletes old stats if > 30 days old
* Hide UI unless dev-mode. We can remove that later once finished.
```release-note
Cleanup for key-server stats
```

Cleanup old key-server stats

---

pkg/controller/cleanup/handle_cleanup.go
pkg/database/signing_key.go

Cleanup nits from https://github.com/google/exposure-notifications-verification-server/pull/1616
- Fix error and log output
- Exclude NULL from deleted_at search
```release-note
Fix nits from signing key cleanup
```

Fix nits from signing key cleanup

---

builders/build.yaml

This should dramatically improve our build times
```release-note
Build all cmd binaries at once in CI
```

Build all cmd binaries at once

---

terraform/database.tf
terraform/mirror/service.tf
terraform/service-stats-puller.tf
terraform/service_appsync.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_modeler.tf
terraform/service_rotation.tf

* Put all the service schedules in UTC timezone
* Have the daily task run around the same time
* appsync run at 11am instead of midnight is a better time for oncallers

Keep schedules all in UTC timezone

---

pkg/config/token_signing_config.go
pkg/controller/certapi/certapi.go
pkg/controller/verifyapi/verify.go
tools/get-certificate/main.go
tools/get-code/main.go
tools/get-token/main.go

Fixes #1623
* allow for tokens to be signed w/ legacy keys until DB one is present
* can be disabled by flag
* to be removed in v0.21
* fix bug where a not found on DB backed key lookup returned error instead of validating w/ legacy key
* debug logging by default in some tools - makes life easier
```release-note
Allow for legacy signing key config for tokens to be used during the upgrade to DB backed tokens.
```

legacy signing fixes

---

terraform/database.tf
terraform/mirror/service.tf
terraform/service-stats-puller.tf
terraform/service_appsync.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_modeler.tf
terraform/service_rotation.tf

* https://github.com/google/exposure-notifications-verification-server/pull/1622 is not what we want, despite UTC guidances for daylight savings time reasons
* Terraform apparently diffs with UTC badly

Keep Schedules in PST

---

cmd/server/assets/realmadmin/keys.html
pkg/controller/realmkeys/automatic_rotate.go
pkg/controller/realmkeys/automatic_rotate_test.go
pkg/controller/realmkeys/manual_rotate.go
pkg/controller/realmkeys/manual_rotate_test.go
pkg/controller/realmkeys/realmkeys_test.go
pkg/controller/rotation/handle_verification_rotate.go
pkg/controller/rotation/handle_verification_rotate_test.go
pkg/database/database_util.go
pkg/database/realm.go
pkg/database/scopes.go
pkg/pagination/pagination.go
terraform/service_rotation.tf

A few cleanup items from https://github.com/google/exposure-notifications-verification-server/pull/1614:
- Return proper response codes when enabling/disabling fails
- Add tests for manual/automatic rotation
- Move ListRealmsWithAutoKeyRotation() into a scope on ListRealms
- Add `pagination.UnlimitedResults`
- Remove testUser for auditing (use SystemTest instead)
- Add comment on why Cloud Scheduler schedule is weird
```release-note
Clean up nits from verification certification rotation
```

Clean up nits from verification certification rotation

---

pkg/controller/certapi/certificate.go
pkg/controller/codes/issue_test.go
pkg/controller/verifyapi/verify.go
pkg/database/token.go
pkg/database/token_test.go
tools/seed/main.go

This updates the seed script to produce a more probabilistic distribution of codes claimed, codes failed, tokens claimed, and tokens failed based on a random distribution. This can be an expensive operation, which is why it's guarded by the newly-added `-stats` flag.
As part of this change, the function signatures for verifying codes and claiming tokens were updated to accepted a time parameter. This is only used for testing and seeding. In production codepaths, the value of time is always `time.Now().UTC()`, which was the previously-hardcoded value in the function body.
```release-note
Make seed script also optionally verify codes and claim tokens
```

Make seed script also verify codes and claim tokens

---

docs/api.md
pkg/controller/apikey/stats.go
pkg/database/authorized_app.go
pkg/database/authorized_app_stats.go
pkg/database/authorized_app_stats_test.go
pkg/database/authorized_app_test.go
pkg/database/realm.go
pkg/database/realm_stats.go
pkg/database/realm_stats_test.go

These statistics already exist and are collected in 0.20. This adds them to the response payload.
Part of #1231 and #1232
```release-note
Add new stats for codes_invalid and tokens to responses
```

Add new stats for codes_invalid and tokens to responses

---

pkg/controller/issueapi/issue.go
pkg/database/vercode.go
pkg/database/vercode_test.go

* This is an alternative to https://github.com/google/exposure-notifications-verification-server/pull/1633
* Wait until the end of code issuance to increment stats - only increment for codes that are successful.
* Batch issuance can increment stats by N, so fewer queries
/hold 
```release-note
Increment code-issue stats at the end of issuance logic. This avoids recording [known] failures.
```

Increment stats at the end of successfully issuing codes

---

pkg/config/redirect_config.go
pkg/controller/redirect/helpers.go
pkg/controller/redirect/helpers_test.go
pkg/controller/redirect/index.go
pkg/controller/redirect/index_test.go
pkg/controller/redirect/redirect.go
terraform/redirect-lb.tf
terraform/services.tf
terraform/variables.tf

This adds the necessary configuration to support the ens://onboarding specification at the provided domain.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1634
```release-note
Add optional onboarding support to redirect service. If `ONBOARDING_DOMAIN` is configured, the redirector service will redirect to the device-specific appropriate location to trigger onboarding when the host matches the value. This value can be configured via Terraform, but care should be taken to avoid an outage due to SSL certificate provisioning for the new domain.
```

Add top-level onboarding domain to redirect service

---

terraform/redirect-lb.tf

These are create-before-destroy, so random is required to avoid a conflict.
```release-note
NONE
```

Add random string to end of certificates

---

builders/build.yaml

Adding this explicit dependency allows them to run in parallel
```release-note
NONE
```

Allow pushes to run in parallel too

---

pkg/controller/certapi/signers.go
pkg/database/managed_key.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_test.go
pkg/database/signing_key.go
pkg/database/sms_signing_key.go

towards #1640
* Add new SMSSiginingKey model
* Create ManagedKey interface
* Refactor realm key management to work on multiple type of managed keys
```release-note
Add database model for managed keys for signing SMS messages.
```

add SMS signing keys at the DB layer

---

terraform/main.tf

```release-note
Make sure attestor is provisioned before building
```

Make sure attestor is provisioned before building

---

internal/routes/adminapi_test.go
internal/routes/apiserver_test.go
internal/routes/enx_redirect_test.go
internal/routes/server_test.go

Part of https://github.com/google/exposure-notifications-verification-server/issues/1399
```release-note
Add more tests for routes
```

Add more tests for routes

---

pkg/cache/cacher.go
pkg/cache/cacher_test.go
pkg/cache/config_test.go
pkg/cache/noop_test.go

Part of https://github.com/google/exposure-notifications-verification-server/issues/1399
```release-note
Add more tests for cacher package
```

Add more tests for cacher

---

docs/api.md

Issue https://github.com/google/exposure-notifications-verification-server/issues/1663
* Clarify documentation to show that error responses are separate from success responses
```release-note
Carify error responses in documentation
```

Split out error response in docs

---

pkg/jwthelper/jwthelper.go
pkg/signatures/signatures.go
pkg/signatures/sms.go
pkg/signatures/sms_test.go

I expect this to change over time as we reach consensus with Apple, but this is good to review and merge for now.
Part of https://github.com/google/exposure-notifications-verification-server/issues/1640
```release-note
Implement first pass at SMS signature algorithm package
```

Implement first pass at SMS signature algorithm

---

cmd/server/assets/header.html
cmd/server/assets/realmadmin/smskeys.html
internal/routes/server.go
pkg/config/feature_config.go
pkg/config/server_config.go
pkg/controller/middleware/enabled.go
pkg/controller/middleware/template.go
pkg/controller/realmkeys/automatic_rotate_test.go
pkg/controller/realmkeys/manual_rotate_test.go
pkg/controller/realmkeys/realmkeys.go
pkg/controller/smskeys/activate.go
pkg/controller/smskeys/create.go
pkg/controller/smskeys/create_test.go
pkg/controller/smskeys/destroy.go
pkg/controller/smskeys/destroy_test.go
pkg/controller/smskeys/disable.go
pkg/controller/smskeys/enable.go
pkg/controller/smskeys/index.go
pkg/controller/smskeys/index_test.go
pkg/controller/smskeys/render.go
pkg/controller/smskeys/smskeys.go
pkg/controller/smskeys/smskeys_test.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/sms_signing_key.go

towards #1640 
* Add realm setting for enabling Authenticated SMS
* Add key management
```release-note
Realm admins can create/rotate SMS signing keys and enable authenticated SMS.
```

add UI for managing SMS signing keys

---

pkg/controller/issueapi/controller.go
pkg/controller/issueapi/handle_issue_test.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/send_sms.go
pkg/controller/issueapi/send_sms_test.go

For batch, this creates N providers (and N TCP connections) unnecessarily. This also adds a local in-memory cache of the provider for 5 minutes to alleviate lookups during heavy load. This is a local in-memory cache, since we can't serialize TCP connections into Redis.
This will become more important for SMS signing keys, since creating the signer is expensive.
```release-note
Use the same SMS provider for all messages, cache locally for 5 minutes to improve performance
```

Move and cache SMS provider up one level

---

cmd/server/assets/header.html
cmd/server/assets/realmadmin/smskeys.html
internal/i18n/locales/de/default.po
internal/i18n/locales/en/default.po
internal/i18n/locales/es/default.po
internal/i18n/locales/fr/default.po
internal/i18n/locales/it/default.po
internal/i18n/locales/ja/default.po
internal/i18n/locales/ph/default.po
internal/i18n/locales/pt/default.po
internal/i18n/locales/tr/default.po
internal/routes/server.go
internal/routes/server_test.go
pkg/config/feature_config.go
pkg/controller/realmkeys/automatic_rotate_test.go
pkg/controller/realmkeys/realmkeys.go
pkg/controller/smskeys/activate.go
pkg/controller/smskeys/activate_test.go
pkg/controller/smskeys/create.go
pkg/controller/smskeys/create_test.go
pkg/controller/smskeys/destroy.go
pkg/controller/smskeys/destroy_test.go
pkg/controller/smskeys/disable_test.go
pkg/controller/smskeys/enable_test.go
pkg/controller/smskeys/index_test.go
pkg/controller/smskeys/smskeys.go
pkg/database/realm.go
pkg/database/sms_signing_key.go
pkg/database/sms_signing_key_test.go

This cleans up a few nits from the introduction of sms signing keys.
- Make "features" a top-level struct available in all templates instead of passing in specific features
- Update some language and HTML on actual sms keys page
- Rename page and nav to "Authenticated SMS"
- Check user-error vs server-error and return appropriate response codes
- Add more tests, including tests for database failures
```release-note
Standardize response codes and add tests to SMS keys
```

Standardize response codes and add tests to SMS keys

---

pkg/controller/appsync/appsync.go
pkg/controller/cleanup/handle_cleanup.go
pkg/controller/rotation/handle_token_rotate.go
pkg/controller/rotation/handle_verification_rotate.go
pkg/controller/statspuller/handle_pull.go

Also remove unused o11y.
```release-note
Add debug logging for when distributed tasks are skipped
```

Add debug logging for when distributed tasks are skipped

---

pkg/config/stats_puller_config.go
pkg/controller/statspuller/handle_pull.go

* The key-server audience default value is `keyserver` so we want this value to match

Different default audience for stats-puller

---

builders/enx-redirect.dockerfile
builders/server.dockerfile

* My docker builds fail to retrieve assets. This gives them all owner as they copy
* Caveat: I have no idea what I'm doing
/hold

My dockerfiles work with this change

---

cmd/e2e-runner/main.go
cmd/server/assets/apikeys/show.html
cmd/server/assets/realmadmin/_stats_codes.html
cmd/server/assets/realmadmin/_stats_external_issuers.html
cmd/server/assets/realmadmin/_stats_keyserver.html
cmd/server/assets/realmadmin/_stats_tokens.html
cmd/server/assets/realmadmin/_stats_users.html
cmd/server/assets/users/show.html

* https://github.com/google/exposure-notifications-verification-server/pull/1691 created the routes to do CSV marshal and this sticks the link into the UI
* (sorry for the absurdly small PRs - I missed a spot here)
* `target="_blank"` for new tab when downloading as a file

csv link in the ui

---

docs/development.md
pkg/controller/realmkeys/render.go
pkg/controller/smskeys/render.go
pkg/database/config.go
pkg/database/database.go
pkg/database/database_util.go
pkg/database/realm.go
pkg/database/realm_test.go
terraform/services.tf
tools/gen-keys/main.go

This keyring is no longer specific to certificate signing, and some of the documentation is now out of date and misleading. This changes the name of the field and envvars to make it explicit that this is the keyring where database-managed keys reside.
```release-note
Rename certificate signing keyring to database keyring. **Upgrade note!** Rename the
environment variable `CERTIFICATE_SIGNING_KEYRING` to `DB_KEYRING` in your
configurations. If you are using the Terraform configurations bundled with the project, this
will happen automatically.
```

Rename certificate signing keyring to database keyring

---

cmd/e2e-runner/main.go

* We added onboarding redirect with https://github.com/google/exposure-notifications-verification-server/pull/1635
* Fixes the e2e test to expect this
```release-note
Fix e2e test to expect redirect onboarding for unknown user-agent header
```

expect generic onboarding redirect

---

cmd/e2e-runner/main.go
cmd/server/assets/realmadmin/_stats_keyserver.html

* The distribution tables now sum the last 7 days from that slider stat date
* This should provide smoother charts esp if there is day-of-the-week variance in user behavior
```release-note
Show distributions as 7 day sums
```

Seven day totals

---

cmd/server/assets/apikeys/show.html
cmd/server/assets/realmadmin/_stats_codes.html
cmd/server/assets/realmadmin/_stats_keyserver.html
cmd/server/assets/realmadmin/_stats_tokens.html
cmd/server/assets/realmadmin/stats.html
cmd/server/assets/static/js/application.js
cmd/server/assets/users/show.html

* Moves the redraw charts function to static js so it'll be cached. I think we can do a lot more of that with some of these charts as things settle down
* Apply redraw to the users and keys charts too
```release-note
Redraw all charts with window resize. Move some js to application.js
```

Move redrawer to static js. Apply to the remaining charts

---

docs/api.md

```release-note
Clarify chaff should be on both endpoints
```

Clarify chaff should be on both endpoints

---

terraform/service_admin_apiserver.tf

Fixes #1703 
* give admin api correct permissions
```release-note
Give Admin API signer verifier permissions on the for the keyring containing SMS singing keys.
```

give adminapi signer/verifier on signing keyring

---

cmd/server/assets/realmadmin/_stats_keyserver.html
cmd/server/assets/realmadmin/stats.html
cmd/server/assets/static/js/application.js

* The user can modify the amount of distribution smoothing we show
```release-note
Adjustable data smoothing
```

Lets user adjust the amount of smoothing on distribution charts

---

pkg/controller/admin/realms.go
pkg/controller/realmkeys/activate.go
pkg/controller/realmkeys/create.go
pkg/controller/realmkeys/destroy.go
pkg/controller/rotation/handle_verification_rotate.go
pkg/controller/rotation/handle_verification_rotate_test.go
pkg/controller/smskeys/activate.go
pkg/controller/smskeys/activate_test.go
pkg/controller/smskeys/create.go
pkg/controller/smskeys/destroy.go
pkg/controller/smskeys/destroy_test.go
pkg/database/managed_key.go
pkg/database/realm.go
pkg/database/realm_test.go
pkg/database/signing_key.go
pkg/database/sms_signing_key.go
pkg/database/sms_signing_key_test.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1702
```release-note
Add audits for signing keys
```

Add audits for signing keys

---

go.mod
go.sum

* Knock out the stackdriver replace (was tracking a specific commit) with the official one
* Followup to https://github.com/google/exposure-notifications-server/pull/1311 which knocked out this hack-y dep to the official stackdriver version

Update stackdriver dep

---

cmd/server/assets/realmadmin/_stats_codes.html
cmd/server/assets/realmadmin/_stats_keyserver.html
cmd/server/assets/realmadmin/stats.html
pkg/database/migrations.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1231
* Shows a line chart of average issue-claim age
```release-note
Average issue-claim chart
```

Mean issue-claim age chart

---

terraform/binary_authorization.tf
terraform/build.tf
terraform/database.tf
terraform/main.tf
terraform/observability.tf
terraform/redis.tf
terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_appsync.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_modeler.tf
terraform/service_redirect.tf
terraform/service_rotation.tf
terraform/service_server.tf
terraform/service_stats_puller.tf
terraform/sessions.tf

This simplifies our key and secret management management at the Terraform level. We've had a few partial outages when deploying new features because it was previously very easy to mess up. This refactors things to make it clearer which secrets a service needs and to depend on the service's service account having the permission as a dependency.
It also fixes a continuous diff we've been getting with Cloud Run.
```release-note
Simplify key and secret management in Terraform. Note: this will cause a _very_ large Terraform diff when applying, including deleting IAM bindings. We recommend running `terraform apply` twice to ensure convergence.
```

Refactor Terraform secrets and key management

---

docs/api.md

```release-note
Promote statistics APIs to Generally Available (GA)
```

Make stats APIs GA

---

terraform/alerting/alerts.tf

Fixes #
* Updated Cloud Scheduler job failed alert
* Set every to 1m
* set duration to 0s
```release-note
```

Updating Scheduler job failed alert

---

cmd/server/assets/realmadmin/_stats_keyserver.html
cmd/server/assets/realmadmin/stats.html

* Add tickmarks to histogram sliders
* Fix the vertical axis height so that the whole graph doesn't redraw as you use slider
* TODO - make this work after changing smoothing
```release-note
Key server histograms have better controls and don't resize as days change
```

Add graph controls and fix axes

---

cmd/server/assets/realmadmin/_stats_codes.html
cmd/server/assets/realmadmin/_stats_keyserver.html
cmd/server/assets/realmadmin/stats.html

* This is https://github.com/google/exposure-notifications-verification-server/pull/1718/ pasted for one more chart
```release-note
Slider tick marks for issue-claim age chart
```

Add ticks and cache for age chart slider

---

cmd/server/assets/realmadmin/_stats_codes.html

* don't resize claim age distribution on slider change
```release-note
Stats - Claim age distribution chart isn't resized when the scope is changed.
```

don't resize age chart on slider change

---

tools/verify-sms-signature/main.go

This adds a small utility for verifying a message's SMS signature. You need to pull the appropriate public key and need to know the date and target phone number. It mimics how a client would compute the signature given a full message body.
```release-note
Add utility for verifying SMS signatures
```

Add utility for verifying SMS signatures

---

pkg/signatures/sms.go
pkg/signatures/sms_test.go

```release-note
Switch to short date with less base64-encoding in returned SMS signature
```
/hold for final sign-off from Apple

Switch to short date, less b64 in returned SMS signature

---

tools/seed/main.go

* Randomizes the issue to claim time in the seed script for more interesting stats
```release-note
Dev seed script randomizes the issue to claim time
```

Randomize issue-claim time in the seed script

---

cmd/e2e-runner/main.go
internal/clients/clients.go
internal/clients/enx_redirect.go
internal/envstest/enx_redirect.go
internal/envstest/integration.go
pkg/integration/enx_redirect_test.go
pkg/integration/integration_test.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1699
```release-note
Run e2e enx-redirector tests as part of CI
```

Run enx-redirect tests in CI

---

docs/architecture.md
internal/clients/enx_redirect.go
pkg/config/redirect_config.go
pkg/controller/redirect/helpers_test.go
pkg/controller/redirect/index.go
pkg/controller/redirect/index_test.go
terraform/redirect-lb.tf
terraform/services.tf
terraform/variables.tf

This was never included in a release, so I'm marking the release notes as `NONE`. Similarly, I'm going to update the release notes on the PR in which this feature was added.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1727
"Reverts" https://github.com/google/exposure-notifications-verification-server/pull/1635
Note that this isn't a true revert becase:
1. It doesn't revert cleanly
2. There is some functionality in that PR (namely the fallback to redirect to g.co/ens in the event someone hits the URL from their browser) which I think is valuable
```release-note
NONE
```

Remove onboarding functionality

---

cmd/server/assets/realmadmin/_stats_keyserver.html
pkg/controller/realmadmin/stats.go

* Displays the key-server override URL on the stats page
* if one is set
* if Can SettingsRead

Display key-server override on the stats page if one is set

---

pkg/controller/user/export_test.go

```release-note
Use UTC time in stats-puller test
```

UTC time for test

---

terraform/redis.tf
terraform/variables.tf

```release-note
Make redis_auth optional, default to false for backwards compatibility
```

Make redis_auth optional

---

terraform/alerting/alerts.tf

This should only notify once for every time the cloud scheduler job fails.

Set align rate to 1min

---

cmd/server/assets/realmadmin/_stats_codes.html
cmd/server/assets/realmadmin/_stats_keyserver.html
cmd/server/assets/realmadmin/_stats_tokens.html
cmd/server/assets/realmadmin/stats.html

* Fixes and unclosed h5 tag
* Relocate the download link back to every chart footer (how it was before)

Unclosed h5 tag. All json/csv as footers

---

cmd/server/assets/login/account.html
cmd/server/assets/login/change-password.html
cmd/server/assets/login/reset-password.html
cmd/server/assets/login/select-password.html
cmd/server/assets/login/select-realm.html
cmd/server/assets/login/verify-email-check.html
cmd/server/assets/login/verify-email.html
pkg/controller/login/account_test.go
pkg/controller/login/change_password_test.go
pkg/controller/login/reauth_test.go
pkg/controller/login/register_phone_test.go
pkg/controller/login/reset_password_test.go
pkg/controller/login/select_password_test.go
pkg/controller/login/select_realm_test.go
pkg/controller/login/signout_test.go
pkg/controller/login/verify_email_receive_test.go
pkg/controller/login/verify_email_send_test.go

* Cover rendering for all of the login pages
* Takes 6% to 42% coverage of the package. Need to exercise the writes next.

Cover rendering all of the login pages

---

terraform/main.tf
terraform/redis.tf
terraform/services.tf

* Ensures that redis PW isn't passed when auth disabled
```release-note
Allow for redis auth to be disabled and terraform to apply successfully
```

don't pass redis password when auth disabled

---

internal/auth/local.go
pkg/controller/codes/expire_test.go
pkg/controller/login/change_password_test.go
pkg/controller/login/reauth_test.go
pkg/controller/login/reset_password_test.go
pkg/controller/login/select_password_test.go
pkg/controller/login/select_realm_test.go
pkg/controller/login/verify_email_send_test.go

* Adds coverage for the submit actions for login

Add test coverage for /login submit actions

---

pkg/rbac/rbac_test.go

Refs https://github.com/google/exposure-notifications-verification-server/issues/1399
```release-note
Add more tests for rbac
```

Add tests for rbac

---

pkg/controller/rotation/handle_token_rotate_test.go
pkg/controller/rotation/handle_verification_rotate_test.go

Refs https://github.com/google/exposure-notifications-verification-server/issues/1399
```release-note
Add more rotation tests
```

Add more rotation tests

---

pkg/sms/noop_test.go

* This one is probably not that useful, but bumps the coverage # for the package. These noops are mainly used... by other tests
* Test for noop and noopfail

Simple test for noop SMS

---

terraform/service_stats_puller.tf

* These are very low-cost calls, but could keep things up-to-date if a call fails
* Key-server only updates this once per hour, most of our distributions show daily

Double frequency for stats

---

pkg/controller/appsync/controller.go
pkg/controller/appsync/controller_test.go
pkg/controller/appsync/handle_sync.go
pkg/controller/appsync/handle_sync_test.go
pkg/controller/appsync/helpers.go
pkg/controller/appsync/helpers_test.go

Refs https://github.com/google/exposure-notifications-verification-server/issues/1399
```release-note
Add more tests for appsync
```

Add more tests for appsync

---

go.mod
go.sum

To pull in https://github.com/google/exposure-notifications-server/pull/1338
```release-note
NONE
```

Upgrade key server to main to pull in KMS fix

---

internal/routes/server.go
pkg/controller/middleware/sessions.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1771
* Checks the session for idleness even if auth is not required. This is important because requireSession defers a bump to session freshness (so the login page currently refreshes the session).
```release-note
Ensure the login page doesn't refresh session freshness
```

Check session idleness in login

---

terraform/alerting/probers.tf

This cannot go in until 0.22 or later.
```release-note
Update probers to check database for uptime
```
/hold

Update probers to check database for uptime

---

terraform/variables.tf

This is required for the google_redis_instance auth_enabled feature.

Update google provider version.

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_modeler.tf
terraform/service_redirect.tf
terraform/service_server.tf

It looks like setting sample_rate while enabled = false is causing some
API error:

Set sample_rate to null if lb logging is not enabled.

---

cmd/server/assets/realmadmin/_stats_keyserver.html
cmd/server/assets/static/css/application.css

* Custom tooltips for the key-server stats charts
* Specifically shows the % of total for each bar
```release-note
Custom chart tooltips with % of total
```

Add custom tooltips for key-server stats

---

cmd/server/assets/realmadmin/_stats_codes.html
cmd/server/assets/realmadmin/_stats_keyserver.html

* Make it clear that each bar is up-to that amount
* Alternatively we could number from 0, but that may still be ambiguous
```release-note
Clarify numbering of ticks on stats charts
```

Clarify what the graph ticks mean

---

terraform/variables.tf

This is required due to our use of sandbox annotation.

Add BETA launch stage annotation.

---

cmd/server/assets/realmadmin/_stats_codes.html

* Remove the word 'age' from chart titles.
* Feedback from a user was that word is too similar to 'age' as used to describe a person
* Now `Days from issue to claim`

Chart titles - remove 'age'

---

pkg/controller/issueapi/gen_code.go

I think `err` being shadowed here causes it to be swallowed to the parent. Even if it isn't, we need to check the return value from `retry.Do`.
```release-note
Ensure error from retry is bubbled to the caller when generating a code
```

Ensure error from retry is bubbled to the caller

---

.github/workflows/codereview.yaml

We have a limit on the number of parallel jobs, and it also doesn't make sense to install reviewdog 3 times.
```release-note
NONE
```

Run more checkers in the same job

---

.github/workflows/codereview.yaml
Makefile
scripts/presubmit.sh

```release-note
Move tabcheck into GitHub Actions
```

Move tabcheck into GitHub Actions

---

pkg/controller/issueapi/issue.go
pkg/controller/issueapi/send_sms.go
pkg/controller/issueapi/send_sms_test.go

* Seth found that this function attempts to [both handle an error and return it](https://github.com/google/exposure-notifications-verification-server/pull/1801#discussion_r574837896) which is ambiguous as to what the caller should do.
* The new code might swallow the `api.ErrSMSQueueFull` errorReturn and needs the `.WithCode(api.ErrSMSFailure)` to give the proper enum error code
* Instead we fully handle the errors inside sendSMS and don't return the error.
* Move the anonymous function to a fully named `doSend` for readability

Handle sms errors in the function

---

cmd/server/assets/realmadmin/keys.html
pkg/controller/codes/expire_test.go
pkg/controller/issueapi/send_sms_test.go
pkg/controller/login/change_password_test.go
pkg/controller/login/reset_password_test.go
pkg/controller/login/select_password_test.go
pkg/controller/login/verify_email_send.go
pkg/controller/login/verify_email_send_test.go
pkg/controller/realmkeys/activate.go
pkg/controller/realmkeys/activate_test.go
pkg/controller/realmkeys/create.go
pkg/controller/realmkeys/create_test.go
pkg/controller/realmkeys/destroy.go
pkg/controller/realmkeys/destroy_test.go
pkg/controller/realmkeys/index.go
pkg/controller/realmkeys/index_test.go
pkg/controller/realmkeys/save.go
pkg/controller/realmkeys/save_test.go
pkg/controller/realmkeys/upgrade.go
pkg/controller/realmkeys/upgrade_test.go
pkg/controller/user/bulk_permisisons_test.go
pkg/controller/user/import_batch_test.go
pkg/database/realm.go

* Add new tests for `/realm/keys` endpoints
* 36.5% -> 84.6% coverage. Still a few more to write 
* Fix up some other tests with some common checks for session
* Once I discovered these common test methods I added em to some old ones I wrote
```release-note
Add test coverage to activate keys and keys index
```

Add test for realmkeys endpoints

---

terraform/service_admin_apiserver.tf

* add signing config to admin api
* 
```release-note
Admin API gets signing config in terraform
```

admin API needs signing config to get key manager settings

---

cmd/appsync/main.go
cmd/cleanup/main.go
cmd/e2e-runner/main.go
cmd/modeler/main.go
cmd/rotation/main.go
cmd/stats-puller/main.go
internal/routes/adminapi.go
internal/routes/apiserver.go
internal/routes/enx_redirect.go
internal/routes/server.go
pkg/controller/middleware/recovery.go
pkg/controller/middleware/recovery_test.go

This comes higher in the stack that Gorilla's default recovery middleware (which cannot be turned off). It uses our logger and desired logging levels.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1825
```release-note
Add and connect recovery middleware
```

Add and connect recovery middleware

---

docs/playbooks/alerts/AuthenticatedSMSFailure.md
pkg/config/admin_server_config.go
pkg/config/issue.go
pkg/config/server_config.go
pkg/config/sms_signing_config.go
pkg/controller/issueapi/metrics.go
pkg/controller/issueapi/send_sms.go
pkg/controller/issueapi/send_sms_test.go
terraform/alerting/alerts.tf
terraform/services.tf

This introduces a runtime configurable to control how the system behaves when signing an authenticated SMS fails. The default behavior is to "fail open" (continue on error), meaning if the signing fails for any reason, the system still continues and delivers the SMS. Operators can also configure the system to "fail closed" (fail on error) to halt and NOT send SMS unless signing succeeds. To control the behavior, operators must set the `SMS_FAIL_CLOSED` environment variable on the `server` and `adminapi` services. Set the value to `true` to fail closed. The default value is false (fail open).
Regardless of the configuration, an error is logged and a metric is incremented when an SMS fails to sign. There is also a new alerting policy for when more than 5 SMS messages fail to sign in a 60s …

Introduce configurable Authenticated SMS failure modes

---

docs/playbooks/alerts/HumanAccessedSecret.md
docs/playbooks/alerts/HumanDecryptedValue.md
terraform/alerting/alerts.tf
terraform/alerting/monitoring.tf

```release-note
Update accuracy for security alerts for HumanAccessSecret and HumanDecryptedValue
```
/assign @mariliamelo

Update security alerts for HumanAccessSecret and HumanDecryptedValue

---

cmd/server/assets/realmadmin/_form_sms.html

Apparently `.on` expects a string selector.
```release-note
Only update SMS preview when the textarea is updated
```

Only update SMS preview when the textarea updates

---

builders/migrate.dockerfile

The old one went away :(
```release-note
Get Cloud SQL Proxy from new link for migrate
```

Get Cloud SQL Proxy from new link

---

internal/envstest/adminapi.go
internal/envstest/apiserver.go
internal/envstest/enx_redirect.go
internal/envstest/server.go
pkg/config/admin_server_config.go
pkg/config/issue.go
pkg/config/server_config.go
pkg/controller/issueapi/issue.go

This handles an edge case where the feature was enabled but then disabled, but a realm has it enabled.
```release-note
Only return a signer if Authenticated SMS is enabled
```

Only return a signer if Authenticated SMS is enabled

---

pkg/database/database.go
pkg/database/database_logger.go
pkg/database/database_logger_test.go

Looking at logs to debug an issue this morning, they are littered with gorm output that has ANSI color sequences embedded (that don't render well). I wrote a custom logger that makes the data structured. 
The existing logger has a bunch of type assertions and things than can panic. I tried to handle more edge cases in this one.
```release-note
Add structured logger for gorm
```

Add structured logger for gorm

---

terraform/alerting/alerts.tf

Part of #1777. This will temporarily improve the alerts before we break it in different alerts with different thresholds.

Improve cloud scheduler job alerts

---

cmd/e2e-runner/main.go
internal/clients/e2e.go
internal/clients/key_server.go
terraform/services.tf

This gives us all the JSON parsing + automatic fallback and nice error messages when something fails. This commit changes the required configuration for `KEY_SERVER` from the full URL to the /publish endpoint to *just* the URL to the key server. Where previously you may have configured `KEY_SERVER=https://foo.bar/v1/publish`, please re-configure with `KEY_SERVER=https://foo.bar`. The system attempts to maintain backwards compatibility by parsing the URL, but this may be removed at a later date.
```release-note
Upgrade e2e-runner's HTTP client. This changes the required configuration for `KEY_SERVER` from the full URL to the `/publish` endpoint to _just_ the URL to the key server. Where previously you may have configured `KEY_SERVER=https://foo.bar/v1/publish`, please …
```

Make e2e-runner publish a real client

---

pkg/controller/flash.go

This can't happen in real life - only in tests
```release-note
NONE
```

Create session.Values if empty

---

.github/workflows/ci.yaml
.github/workflows/stale.yml
.github/workflows/terraform.yml

This is important if we're moving to GitHub Actions because:
1. We can't easily force PRs to ff-merge and re-test
2. We want the cache to build
```release-note
Also run tests on pushes to the main branch
```

Also run tests on main

---

internal/envstest/integration.go

This fixes an issue where the tests get really sad if you don't set the Twilio creds. There's still a bit more work to be done to unify the integration test and e2e-runner, which will fix the other issue.
```release-note
Disable authenticated sms in tests when the creds are missing
```

Disable authenticated sms in tests when the creds are missing

---

.github/workflows/ci.yaml
internal/envstest/integration.go
pkg/integration/integration_test.go

This runs the same e2e tests as the e2e-runner as integration tests. Turns out, there was a _ton_ of duplication we got to remove.
This also fixes an edge case where GitHub secrets are not exposed in runs on PR foks. If the secrets aren't available, the tests skip testing SMS in the integration tests.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1824
```release-note
Merge e2e tests and integration tests
```

Merge e2e tests and integration tests

---

pkg/controller/apikey/create_test.go
pkg/controller/apikey/disable_test.go
pkg/controller/apikey/enable_test.go
pkg/controller/apikey/index_test.go
pkg/controller/apikey/show_test.go
pkg/controller/apikey/update_test.go

```release-note
Use less chromedp and less database churn in API key tests
```

Use less chromedp and less database churn in API key tests

---

cmd/server/assets/realmadmin/_form_sms.html

This is important for international where PHAs may want to use characters that aren't in GSM-7. I don't want to replicate the Twilio calculator in our system, so let's link out to it.
```release-note
Link out to Twilio splits calculator for advanced calculations
```

Link out to Twilio splits calculator for advanced calculations

---

pkg/ratelimit/config.go

This doubles the default rate limiting from 60/min to 120/min.
```release-note
Change rate limiting defaults from 60/min to 120/min
```

Change rate limiting defaults to 120/min

---

pkg/keyutils/public_keys.go

The system only uses ecdsa keys, so this should not affect anyone.
```release-note
Drop support for crypto/dsa in public key parsing. The EN system only supports ecdsa keys, so this will not affect the system.
```

Drop support for crypto/dsa in public key parsing

---

cmd/server/assets/realmadmin/_stats_codes.html

* Change titles on claim latency charts
* Change units on mean claim from seconds to minutes
```release-note
Clarify naming on code claim charts. Change units on mean claim graph from seconds to minutes.
```

Clarify claim latency charts

---

builders/build.yaml

Cache 1.5G -> 148 MB
```release-note
Set service names and fix build cache
```

Set service names and fix build cache

---

terraform/service_server.tf
terraform/services.tf

This will cause services to fail before the new ones are deployed. We can remove this configuration later. It doesn't hurt to have it, it just isn't used anymore.
```release-note
Do not remove ASSETS_PATH and LOCALES_PATH from Terraform just yet.
```

Do not remove ASSETS_PATH and LOCALES_PATH from Terraform yet

---

internal/envstest/apiserver.go
pkg/config/token_signing_config.go
pkg/controller/certapi/certapi.go
pkg/controller/cleanup/handle_cleanup_test.go
pkg/controller/rotation/handle_token_rotate.go
pkg/controller/rotation/handle_token_rotate_test.go
pkg/controller/verifyapi/verify.go
terraform/services.tf
tools/seed/main.go

⚠️ 🛑 Please review with caution 🛑 ⚠️ 
The new value is TOKEN_SIGNING_KEY and it must point to the parent key. Token signing keys have moved into the database since v0.22.
You MUST upgrade to v0.22 for at least 24 hours before applying this release.
```release-note
Remove backwards-compatibility for `TOKEN_SIGNING_KEY`. Specifying multiple values has been deprecated since 0.21 and token signing keys have moved into the database. If you are on an older version, you **MUST upgrade to v0.22 for at least 24h before applying this update.** You should ensure that the value of `TOKEN_SIGNING_KEY` points to a key (not a key version) in the service environment before applying this upgrade. Since v0.22, `TOKEN_SIGNING_KEY` accepted a key version or a parent key. This release only …
```

Remove deprecated TOKEN_SIGNING_KEYS

---

builders/build.yaml
pkg/controller/mobileapps/create_test.go
pkg/controller/mobileapps/disable_test.go
pkg/controller/mobileapps/enable_test.go
pkg/controller/mobileapps/index_test.go
pkg/controller/mobileapps/show_test.go
pkg/controller/mobileapps/update_test.go
pkg/controller/realmadmin/events_test.go
pkg/controller/realmadmin/express_disable_test.go
pkg/controller/realmadmin/express_enable_test.go
pkg/controller/realmadmin/settings_modify_test.go
pkg/controller/realmadmin/sms_test.go
pkg/controller/realmadmin/smtp_test.go
pkg/controller/realmadmin/stats_test.go
pkg/controller/realmkeys/activate_test.go
pkg/controller/realmkeys/index_test.go
pkg/database/mobile_app.go

```release-note
Remove unneeded chromedp from realmadmin and realmkeys
```

Remove unneeded chromedp from realmadmin and realmkeys

---

assets/server/firebase.html

[Changes to auth since 8.2.1](https://firebase.google.com/support/release-notes/js):
- API update for an internal package. There is no change in the public API.
- Fixed a bug where UTF-8 encoded strings were not decoded in getIdTokenResult. See https://github.com/firebase/firebase-js-sdk/issues/4174.
- Added the useEmulator() function and emulatorConfig to the firebase package externs.
```release-note
Upgrade to Firebase Auth version 8.2.9.
```

Upgrade to Firebase auth 8.2.9

---

Makefile

Upgrade golangci-lint to v0.37.1
```release-note
Change to tmpdir when installing linters
```

Change to tmpdir when installing linters

---

.github/workflows/ci.yaml

We do this manually
```release-note
NONE
```

Skip golang-ci restoring the cache

---

pkg/controller/codes/issue_test.go

Not sure _why_ it sporadically fails, but this will print out the html source of the page and give us a better idea about at which stage it is failing.
```release-note
NONE
```

Add more debug output when chromedp fails

---

assets/server/realmadmin/_stats_codes.html
assets/server/realmadmin/_stats_keyserver.html
assets/server/realmadmin/stats.html
docs/api.md
go.mod
go.sum
internal/routes/server.go
pkg/controller/realmadmin/events_test.go
pkg/controller/realmadmin/express_disable_test.go
pkg/controller/realmadmin/express_enable_test.go
pkg/controller/realmadmin/realmadmin.go
pkg/controller/realmadmin/settings_modify_test.go
pkg/controller/realmadmin/sms_test.go
pkg/controller/realmadmin/smtp_test.go
pkg/controller/realmadmin/stats.go
pkg/controller/realmadmin/stats_test.go
pkg/controller/stats/composite.go
pkg/database/database.go
pkg/database/key_server_stats.go
pkg/database/realm_stats.go

Update stats visualizations based on user input
* remove tokens claimed/tokens invalid - that chart has been confusing
* add tokens claimed and publish requests to make code chart (top of page) -- IF key server metrics are enabled
* separate out revisions and missing onset from TEKs published (different units)
* don't show revisions at all (to our knowledge, nobody is using that functionality)
* add total publish requests and missing onset as overlays on the publish bar chart
```release-note
* The tokens claimed/invalid chart has been removed (data is still in exports)
* Add total publish requests to the codes/issued claim chart (if key server stats are enabled)
* Separate out revisions and missing onset from TEKs published
* Add total publish requests and missing onset …
```

change chart combos

---

internal/i18n/locales/id/default.po

Fixes #
* Add Indonesia (id) language
```release-note
- Indonesia (id) language translation
```

Add Indonesia (id) locale

---

terraform/main.tf
terraform/variables.tf

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1901
Not marking auto-merge because I want to test manually.
```release-note
Allow customizing global log retention period for all services in the project. The default value is 14 days. **Note: this differs from the unconfigured value of 30 days!**. To retain the existing behavior, set `log_retention_period` to `30` in the Terraform configuration. However, we strongly recommend using a 14-day retention period instead.
```

Allow customizing log retention period

---

assets/server/admin/realms/edit.html
assets/server/admin/realms/index.html
pkg/config/cleanup_server_config.go
pkg/controller/admin/realms.go
pkg/controller/cleanup/handle_cleanup.go
pkg/controller/cleanup/handle_cleanup_test.go
pkg/controller/middleware/chaff.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_chaff_event.go
pkg/database/realm_chaff_events_test.go
pkg/database/realm_test.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1899
```release-note
Add chaff reporting to system admin page. This will show whether a realm has issue _any_ chaff requests in the past 7 days.
```

Add chaff reporting

---

pkg/controller/middleware/apikey_test.go
pkg/controller/middleware/email_verified_test.go
pkg/controller/middleware/firewall_test.go
pkg/controller/middleware/header_test.go
pkg/controller/middleware/membership_test.go
pkg/controller/middleware/mfa_test.go
pkg/controller/middleware/recovery_test.go
pkg/render/json.go
pkg/render/renderer.go
pkg/sms/twilio.go

🧹 
I think I've covered most of the status codes that were left as constants around the code.
It's 99% `sed`, so somethings might be amiss :-)

Next wave of status code changes

---

go.mod
pkg/config/stats_puller_config.go
pkg/controller/statspuller/handle_pull.go

This updates the stats-puller to retry the HTTP request 3 times. This will make us more resilient to temporary network blips. It also parallelizes pulling (default 5).
```release-note
Add client-side retry logic and parallelize stats puller. The default parallelize is 5, but it can be customized with `STATS_PULLER_MAX_WORKERS`. There is also a **behavior change**. The stats-puller previously always returned success (but logged errors on failure). This changes the puller to return a non-200 response code if there are still failures after all retries have executed.
```

Retry and parallelize stats puller

---

terraform/alerting/alerts.tf

This will create a cloud scheduler job failed alert if there have been errors in the last 10 minutes.

Set alert interval to 10 mins

---

.github/workflows/terraform.yml

This restricts Terraform to running on CI against PRs to main and the main branch
```release-note
NONE
```

Only run Terraform checks once

---

terraform/variables.tf

```release-note
Set Binary Authorization service annotations on Cloud Run services.
```

Set binauth annotation

---

pkg/controller/statspuller/handle_pull.go

* Fix nil ptr error
```release-note
Fixes nilptr error in stats puller (not in a previous labeled release)
```

fix nil ptr in stats puller

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_modeler.tf
terraform/service_redirect.tf
terraform/service_server.tf
terraform/variables.tf

Also change the default values to 60s for both (down 300s for draining and up from 30s for connect).
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1829
```release-note
Add new Terraform configurations for `connection_draining_timeout` (default: 60s) and `connection_timeout` (default: 60s).
```

Make connect and drain timeout configuration

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_modeler.tf
terraform/service_redirect.tf
terraform/service_server.tf
terraform/variables.tf

Reverts google/exposure-notifications-verification-server#1912
Serverless NEGs don't support timeouts

Revert "Make connect and drain timeout configuration"

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_appsync.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_modeler.tf
terraform/service_redirect.tf
terraform/service_rotation.tf
terraform/service_server.tf
terraform/service_stats_puller.tf

In-request services have a timeout of 10 seconds while background jobs have a timeout of 900s. The Cloud Scheduler timeout (which invokes the background jobs) has a 60s buffer to reduce timeout races.
```release-note
Improve service timeouts. In-request services have a timeout of 10 seconds while background jobs have a timeout of 900s. The Cloud Scheduler timeout (which invokes the background jobs) has a 60s buffer to reduce timeout races.
```

Improve service timeouts

---

pkg/controller/user/bulk_permisisons_test.go

Apparently CI doesn't run on security advisories
```release-note
NONE
```

Fix failing test

---

.github/workflows/ci.yaml

I think this coincidentally works today because of our package name lengths. NF will always work.
```release-note
NONE
```

Use last column instead of 3 for coverage

---

pkg/controller/issueapi/controller.go
pkg/controller/realmadmin/settings_modify.go
pkg/database/database.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1924
```release-note
Lower in-memory cache time and return a warning about cached values
```

Lower in-memory cache time and return a warning about cached values

---

pkg/config/redirect_config.go
pkg/config/server_config.go
terraform/services.tf

These were kept to make the transition from fs to embed easier. It's been a full release cycle, so let's remove these values now.
```release-note
Remove warnings about unused environment variables.
```

Remove warnings about unused environment variables

---

internal/routes/adminapi.go

Fixes #
* Adds composite.csv/json routes to admin api server, these were left off when composite stats were added
```release-note
composite stats are now available on the adminapi, `realm/composite.csv` and `realm/composite.json`
```

add composite stats handler to adminapi server

---

terraform/alerting/alerts.tf
terraform/alerting/variables.tf

```release-note
Allow overriding default fp alerts in Terraform
```

Allow overriding default fp alerts

---

terraform/alerting/alerts.tf

The UI accepts this, but the API rejects it
```release-note
Re-add delta aligner
```

Re-add delta aligner

---

pkg/api/api.go
pkg/controller/issueapi/handle_user_report_test.go
tools/user-report/main.go

Towards #1928 
* remove platform flag, android is not going to handle SMS differently in this case
```release-note
NONE
```

remove platform for user report API

---

assets/server/realmadmin/_form_codes.html
assets/server/realmadmin/_stats_codes.html
go.mod
go.sum
pkg/database/composite_stats.go
pkg/database/composite_stats_test.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_stats.go
pkg/database/realm_stats_test.go
pkg/database/token.go
pkg/database/vercode.go
tools/seed/main.go

Towards #1928 
* Add 2 new charts for user-reported codes
* Improve seed script so make the numbers normalized across different types + add user-report generation
```release-note
Add charts for user-reported codes and claim stats.
```

add self report charts

---

assets/server/realmadmin/_form_sms.html
pkg/database/realm.go

Towards #1928
* Fix deletion of SMS template bug
* remove length restriction on user report, allow user report template to use ENX deep links
```release-note
User report can use signed SMS and relax template restrictions.
```

change restrictions on user report SMS template

---

assets/server/realmadmin/_stats_keyserver.html

Towards #1928
* add revisions back to key sever chart
```release-note
Number of revision request are shown on key server stats if user initiated reporting is enabled. This is the only EN Express scenario where key revision could occurr.
```

add key revisions back to key server chart iff user report is enabled

---

terraform/service_admin_apiserver.tf
terraform/service_apiserver.tf
terraform/service_appsync.tf
terraform/service_backup.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_modeler.tf
terraform/service_redirect.tf
terraform/service_rotation.tf
terraform/service_server.tf
terraform/service_stats_puller.tf
terraform/variables.tf

This makes it easier (and less error-prone) to set a common configuration like `LOG_LEVEL` on all services at once.
```release-note
Add special "_all" key to apply to all service environments. The special key `_all` will apply to all services. This is useful for common configuration like log-levels. A service-specific configuration overrides a value in `_all`. There are no default values for `_all`, so the default behavior is unchanged.
```

Add special "_all" key to apply to all service environments

---

pkg/controller/user/create.go
pkg/controller/user/create_test.go

```release-note
Ensure users retain system admin when being added to a realm
```

Ensure users retain system admin when being added to a realm

---

assets/server/realmadmin/_form_codes.html
pkg/controller/issueapi/handle_issue.go
pkg/controller/issueapi/handle_user_report.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/validate_code.go
pkg/controller/issueapi/validate_code_test.go
pkg/controller/realmadmin/settings_modify.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/token.go
pkg/database/token_test.go
pkg/database/user_report.go
pkg/database/user_report_test.go
pkg/database/vercode.go
pkg/database/vercode_test.go
tools/seed/main.go

Towards #1928 
* Add realm setting to enable "admin" API user-reports
* these don't require a nonce
* do require a phone number and still de-dupe against the HMAC user_report phone index
```release-note
All admin actions to issue user-report level verification codes, that can result in SELF_REPORT
```

allow admin /api/issue to issue user-report codes

---

cmd/e2e-runner/main.go

* bootstrap e2e runner on first run
```release-note
e2e-runner will bootstrap the e2e test realm on first invocation instead of on startup. This prevents deploy failures when new columns are added to the realm table during an upgrade. 
```

bootstrap e2e runner on first run instead of startup

---

pkg/database/config.go
pkg/database/user_report.go

This is guarded by a feature flag, so it should not be required. Furthermore, there's already a runtime check that at least one key is provided to the helper.
```release-note
Do not mark PhoneNumberHMAC as required
```

Do not mark PhoneNumberHMAC as required

---

pkg/controller/middleware/secure.go

This is deprecated by most modern browsers and can cause client-side security issues.
```release-note
Remove XSS header. This is deprecated by most modern browsers and can cause client-side security issues.
```

Remove XSS header

---

pkg/config/backup_config.go
pkg/config/cleanup_server_config.go
pkg/config/rotation_config.go
pkg/config/stats_puller_config.go

We currently have two TTLs on many services: the minTTL that is enforced via the database lock, and a minTTL that is enforced by the service being invoked by Cloud Scheduler. There were some mismatches over which was the "authorative" schedule. This commit lowers the minTTLs on most services to 5min. This will prevent concurrent runs and crazy DOsing. However, the _intended_ execution schedule's source of truth is Cloud Scheduler.
I believe this is the root cause of the recent alert, because the "4 hour" windows between the backup job's minTTL and Cloud Scheduler's 4 hours misaligned.
Lowering to 5min also gives us flexibility to invoke jobs manually without hitting the data-layer TTLs.
```release-note
Lower data-layer TTLs on background jobs
```

Lower data-layer TTLs

---

pkg/config/cleanup_server_config.go
terraform/service_cleanup.tf

* Fix env var being same for both user-report cleanups
* Run cleanup more frequently
```release-note
Cleanup job will run every 15 minutes
```

fix env var

---

pkg/controller/middleware/firewall.go
pkg/controller/middleware/firewall_test.go
pkg/ratelimit/limitware/middleware.go
pkg/realip/realip.go
pkg/realip/realip_test.go

```release-note
Centralize X-Forwarded-For processing to get real client IPs
```

Centralize X-Forwarded-For processing to get real client IPs

---

pkg/database/migrations.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/1948
```release-note
Drop UPDATE privileges on audits table. This makes audit entries immutable (but still deletable).
```

Drop UPDATE privileges on audits table

---

assets/server/codes/issue.html
assets/server/login/_loginscripts.html
assets/server/login/register-phone.html
assets/server/static/js/application.js
assets/server/users/import.html
docs/development.md
docs/production.md
go.mod
go.sum
internal/envstest/server.go
internal/routes/server.go
pkg/api/api.go
pkg/config/server_config.go
pkg/controller/middleware/csrf.go
pkg/controller/middleware/csrf_test.go
pkg/controller/session.go
terraform/main.tf
terraform/services.tf
terraform/sessions.tf

This drops the need for two separate cookies to maintain CSRF and removes a few layers of indirection for CSRF handling. CSRF values are now also tied to session duration.
This intentionally leaves the configuration and secret in place until the _next_ release to provide a seamless transition.
```release-note
Move CSRF implementation into session.
```

Move CSRF implementation into session

---

assets/server/realmadmin/_form_sms.html
pkg/controller/issueapi/send_sms.go
pkg/signatures/sms.go

Towards: #1928
* Add guidance for user report template
* Use `User Report` in the preamble only for User Report types.
```release-note
Add guidance for user report SMS template 
```

user report messaging and signing

---

internal/routes/apiserver.go
pkg/controller/context.go
pkg/controller/middleware/operating_system.go
pkg/controller/middleware/operating_system_test.go

Towards #1972
* Middleware to capture OS by user agent
* install in apiserver:/api/verify path
```release-note
Middleware to make OS present in request context
```

capture OS in request context from user agent

---

internal/clients/clients.go
pkg/controller/context.go
pkg/controller/middleware/operating_system.go
pkg/controller/middleware/operating_system_test.go
pkg/controller/verifyapi/verify.go
pkg/database/migrations.go
pkg/database/mobile_app.go
pkg/database/realm_stats.go
pkg/database/token.go
tools/get-token/main.go

Towards #1972
* capture the OS in ream_stats when an invalid code is attempted to be used
```release-note
When invalid codes are attempted to be used, the OS is captured in the realm stats [unknown, ios, android]
```

capture invalid codes by os in realm_stats

---

assets/server/realmadmin/_stats_codes.html
assets/server/static/js/application.js
pkg/database/composite_stats.go
pkg/database/composite_stats_test.go
pkg/database/realm.go
pkg/database/realm_stats.go
pkg/database/realm_stats_test.go
tools/seed/main.go

Fixes #1972
* Add display of invalid codes by OS
* Fix CSRF bug for JS submitted links
```release-note
New chart on the realm admin stats page showing the invalid codes entered by operating system.
```

chart of invalid codes by OS

---

assets/assets.go
assets/server/login/_loginscripts.html
assets/server/login/change-password.html
assets/server/static/js/application.js

Check password validity on page load to reduce code duplication
```release-note
Check password validity on page load to reduce code duplication.
```

Update change password javascript and styles

---

pkg/config/feature_config.go

```release-note
Enable Authenticated SMS by default. To disable this functionality, set `ENABLE_AUTHENTICATED_SMS` to `false`. The ability to disable this feature may be removed in a future release.
```

authenticated SMS to default on

---

terraform/verification-lb.tf

* only redirect for known host headers
```release-note
Change load balancer https redirect rules to only match known host names, otherwise redirect to UI server.
```

only redirect for known host headers

---

internal/routes/server.go
pkg/controller/middleware/static.go
pkg/controller/middleware/static_test.go

It's fine to cache these for a year because we embed the build ID in the actual request as a query param.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1985
```release-note
Set cache headers on static assets, do not apply middlewares.
```

Set cache headers on static assets, do not apply middlewares

---

assets/server/realmadmin/_form_codes.html
assets/server/realmadmin/smskeys.html

* add warning on settings page
```release-note
Add a warning on realm settings page that when user report is enabled, authenticated SMS should be enabled too.
```

add warning about UR and auth SMS

---

pkg/controller/realmadmin/express_enable.go
pkg/controller/realmadmin/settings_modify.go
pkg/controller/realmkeys/save.go
pkg/controller/realmkeys/save_test.go
pkg/controller/user/create.go

* don't let greyed out fields be changed
* alert if user exists
```release-note
Don't let greyed out fields be changed in signing keys.
Alert when creating a user that already exists.
Fix ENX upgrade SMS template text when user-report is enabled.
```

add some UX fixes

---

assets/server/login/_loginscripts.html
assets/server/login/change-password.html
assets/server/login/select-password.html
internal/i18n/locales/ar/default.po
internal/i18n/locales/de/default.po
internal/i18n/locales/en/default.po
internal/i18n/locales/es/default.po
internal/i18n/locales/fil/default.po
internal/i18n/locales/fr/default.po
internal/i18n/locales/id/default.po
internal/i18n/locales/it/default.po
internal/i18n/locales/ja/default.po
internal/i18n/locales/mn/default.po
internal/i18n/locales/pt/default.po
internal/i18n/locales/tr/default.po
pkg/controller/login/select_password.go

Part of https://github.com/google/exposure-notifications-verification-server/issues/1970
```release-note
Add translations to change/select password pages.
```

Add translations to change/select password pages

---

assets/server/login/select-realm.html
assets/server/login/signout.html
internal/i18n/locales/ar/default.po
internal/i18n/locales/de/default.po
internal/i18n/locales/en/default.po
internal/i18n/locales/es/default.po
internal/i18n/locales/fil/default.po
internal/i18n/locales/fr/default.po
internal/i18n/locales/id/default.po
internal/i18n/locales/it/default.po
internal/i18n/locales/ja/default.po
internal/i18n/locales/mn/default.po
internal/i18n/locales/pt/default.po
internal/i18n/locales/tr/default.po
pkg/controller/login/select_realm_test.go

Part of https://github.com/google/exposure-notifications-verification-server/issues/1970
```release-note
Add translations for signout and realm selection pages.
```

Add translations for signout and realm selection pages

---

assets/server/login/verify-email-check.html
assets/server/login/verify-email.html
assets/server/static/js/application.js
internal/i18n/locales/ar/default.po
internal/i18n/locales/de/default.po
internal/i18n/locales/en/default.po
internal/i18n/locales/es/default.po
internal/i18n/locales/fil/default.po
internal/i18n/locales/fr/default.po
internal/i18n/locales/id/default.po
internal/i18n/locales/it/default.po
internal/i18n/locales/ja/default.po
internal/i18n/locales/mn/default.po
internal/i18n/locales/pt/default.po
internal/i18n/locales/tr/default.po

I think this is the last "login" page that needs translations.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1970
```release-note
Add translations for email verify pages.
```

Add translations for email verify pages

---

go.mod
go.sum
internal/routes/server.go
pkg/controller/middleware/gzip.go

Most browsers will accept gzip, so this can dramatically reduce load times, esp on mobile
```release-note
Return gzipped responses if the client supports gzipped responses.
```

Return gzipped responses if the client requests

---

pkg/controller/cleanup/handle_cleanup.go
pkg/controller/cleanup/handle_cleanup_test.go
pkg/database/authorized_app.go
pkg/database/authorized_app_test.go
pkg/database/realm.go
pkg/database/realm_test.go

The e2e-runner does self cleanup, but sometimes the job times out or fails. In those cases, there's no opportunity for cleanup and we gradually leak API keys over time.
This introduces a function for getting the e2e-realm (if one exists), and adds a new task to the cleanup job to delete e2e keys that have existed for more than 24 hours.
```release-note
Cleanup e2e API keys that have existed for > 24 hours.
```

Cleanup e2e API keys that have existed for > 24 hours

---

pkg/controller/cleanup/handle_cleanup.go
pkg/database/realm.go
pkg/database/realm_test.go

This removes the purging bits but keeps the e2e realm lookup helper function.
```release-note
Introduce function for getting the e2e-realm (if one exists).
```

Introduce function for getting the e2e-realm (if one exists)

---

assets/server/apikeys/index.html
assets/server/apikeys/show.html
go.mod
go.sum
pkg/config/feature_config.go
pkg/controller/apikey/create_test.go
pkg/controller/apikey/disable_test.go
pkg/controller/apikey/enable_test.go
pkg/controller/apikey/index_test.go
pkg/controller/apikey/show_test.go
pkg/controller/apikey/update_test.go
pkg/controller/middleware/apikey.go
pkg/database/authorized_app.go
pkg/database/migrations.go
pkg/render/renderer.go

This isn't an exact timestamp tracker, since we use some pretty aggressive caching to avoid a write on every read. However, this will give realm admins a very clear signal of whether an API key is still being used.
The UI is hidden behind a feature flag because I want to capture this data for a full release until displaying it in the UI. Otherwise it could lead to misleading information about an API having "never" been used.
```release-note
Track API key "last used"
```

Track API key "last used"

---

pkg/database/database_logger.go
pkg/database/database_logger_test.go

```release-note
Handle gorm log at debug level instead of error.
```

Handle gorm log at debug level

---

terraform/service_apiserver.tf
terraform/service_appsync.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_server.tf
terraform/services.tf
terraform/sessions.tf

This needed to stay in for the 0.26 release, but it is safe to remove now.
```release-note
Remove unused csrf token from Terraform.
```

Remove unused csrf token from Terraform

---

assets/server/firebase.html
internal/auth/firebase.go

I believe this will address the issue where a user is logged out and then quickly logged back in. We're using server-side sessions, but Firebase is still setting a cookie. So even when the session expires, Firebase re-authenticates automatically. This follows the instructions at https://firebase.google.com/docs/auth/admin/manage-cookies to disable persisting the Firebase cookie. There's also a server-side check that the auth token was created within the past 5 minutes for any Firebase cookies that might already be out in the wild.
```release-note
Do not store firebase cookie and verify ID token is < 5min old.
```

Do not store firebase cookie and verify ID token is < 5min old

---

assets/server/apikeys/index.html
assets/server/apikeys/show.html

```release-note
Note that last_used_time has 15m granularity in the UI.
```

Note that last_used_time has 15m granularity

---

terraform/redirect-lb.tf

There's a limit of 50 path_matchers on a url map. Fortunately it supports wildcards :). This properly allows any subdomain to redirect to the https version. It doesn't 100% prevent host-header injection, but it does prevent an attacker from redirecting to an arbitrary host; it's only possible to redirect to another host on the same domain (which we control and does not serve user content).
This also changes redirects from 301 -> 302. In testing, my browser cached the redirect, which was somewhat annoying. Given that we may change these, 302 feels more appropriate.
```release-note
Use a wildcard for redirect domains. This fixes an issue for installations with more than 50 realms exceeding the limit on the URL map.
```

Use a wildcard for redirect domains

---

assets/server/admin/info.html
go.mod
go.sum
pkg/config/feature_config.go
pkg/controller/admin/info.go
pkg/controller/middleware/apikey_test.go
pkg/database/migrations.go
pkg/database/scopes.go
pkg/database/secret.go
pkg/database/secret_test.go

This is just the models; trying to split this up to make it easier to review.
Note that there won't be any secrets in the info page for now, since nothing is actually connected.
```release-note
Add secret models and structure to info page.
```

Add secret models and structure to info page

---

cmd/rotation/main.go
pkg/config/rotation_config.go
pkg/controller/rotation/handle_token_rotate.go
pkg/controller/rotation/handle_token_rotate_test.go
pkg/controller/rotation/handle_verification_rotate.go
pkg/controller/rotation/handle_verification_rotate_test.go
pkg/controller/rotation/metrics.go
pkg/controller/rotation/rotation.go
terraform/service_rotation.tf
tools/seed/main.go

This also adds the secrets.SecretVersionManager on the rotation controller but does not use it yet.
```release-note
Extract key/secret bootstrapping from rotation controller into functions for seeding.
```

Extract key/secret bootstrapping into functions for seeding

---

pkg/cookiestore/codec.go
pkg/cookiestore/cookiestore.go

This leverages the same securecookie implementation we already have, but allows for a dynamic codec that sources entropy on _each_ invocation. This will be required for when cookie keys are automatically rotated so apps pick up the new cookie keys without needing a restart.
```release-note
Add custom cookiestore codec for dynamically resolving secrets.
```

Add custom cookiestore codec

---

pkg/database/secretresolver.go
pkg/database/secretresolver_test.go

Not yet used, but this is the centralization of secret resolution. I had a lot of internal debate about whether to hang this off the database, but it ended up being the best place and avoids some otherwise ugly circular dependencies.
Inline comments should explain what it does and why.
```release-note
Add secret resolver.
```

Add secretresolver

---

pkg/config/rotation_config.go
pkg/controller/rotation/handle_secrets_rotate.go
pkg/controller/rotation/handle_secrets_rotate_test.go
pkg/controller/rotation/rotation.go
pkg/database/user_report_test.go
terraform/alerting/alerts.tf
terraform/service_rotation.tf
terraform/services.tf
terraform/sessions.tf
tools/seed/main.go

This adds the rotation handlers and required Terraform configuration. It does not actually mount the path to be invoked, nor does it set up the Cloud Scheduler job. This is the core rotation logic, so please review closely.
```release-note
Add rotation handling logic.
```

Add rotation handlers

---

internal/routes/adminapi.go

This fixes an issue where metrics don't include the realm id. Originally the rate limiter existed before requiring an API key to limit database load, but we've since introduced multiple layers of caching that mitigate this.
```release-note
Fix an issue where adminapi metrics were not tagged with the realm ID.
```

Move ratelimit middleware after API key

---

cmd/e2e-runner/main.go
cmd/e2e-runner/metrics.go
internal/clients/e2e.go
internal/envstest/bootstrap.go
pkg/config/e2e_runner_server_config.go
pkg/controller/issueapi/gen_code.go
pkg/controller/issueapi/handle_issue.go
pkg/database/user_report.go
pkg/database/user_report_test.go
pkg/database/vercode.go
pkg/integration/enx_redirect_test.go
terraform/alerting/alerts.tf
terraform/service_e2e_runner.tf
tools/get-code/main.go

Last non web UI thing for  #1928
* add end to end test for user-report
* ensure that user report SMS template is used for admin API requests codes (as a default)
```release-note
Adds end to end test runner for user-report if that feature is enabled.
```

add end to end runner for user-report test type

---

pkg/api/util.go

* user-report is not part of the default (empty) accept list
```release-note
User-report types are part of the default accept list on the verify API now.
```

add user report to default accept

---

cmd/rotation/main.go
docs/development.md
docs/production.md
internal/envstest/enx_redirect.go
internal/envstest/harness.go
internal/envstest/server.go
internal/project/context.go
internal/routes/enx_redirect.go
internal/routes/server.go
pkg/config/redirect_config.go
pkg/config/server_config.go
pkg/controller/middleware/apikey_test.go
pkg/controller/rotation/handle_secrets_rotate.go
pkg/controller/rotation/handle_secrets_rotate_test.go
pkg/cookiestore/codec.go
pkg/database/authorized_app.go
pkg/database/config.go
pkg/database/database.go
pkg/database/database_util.go
pkg/database/secret.go
pkg/database/secretresolver.go
pkg/database/user_report.go
pkg/database/vercode.go
terraform/alerting/alerts.tf
terraform/database.tf
terraform/main.tf
terraform/service_rotation.tf
terraform/sessions.tf

```release-note
**Add automated secrets rotation.** This introduces automated rotation for most application-level secrets. Whereas previously it was the responsibility of server administrators to rotate secrets, the application will now rotate a variety of secrets on regular intervals for improved security.
```

Add automated secrets rotation

---

pkg/config/certificate_signing_config.go
pkg/controller/certapi/certificate.go

```release-note
The not before (nbf) time on certificates is no configurable to account for clock skew between verification and key servers.
```

make certificate NBF duration configurable

---

pkg/controller/certapi/certificate.go

```release-note
The configurable timing for NBF is also applied to IAT, accounting for clock skew between key and verification servers.
```

also apply clock skew to IAT

---

pkg/controller/rotation/handle_secrets_rotate.go
pkg/controller/rotation/handle_secrets_rotate_test.go

This fixes an issue where a secret would be created even if another one already existed but was waiting to be activated.
Also fixes an issue where tests would panic under failure conditions.
```release-note
NONE
```

Check inactive secrets when comparing TTLs

---

pkg/config/rotation_config.go

This explains why verification codes weren't rotating. I'll look at making this an error in envconfig.
```release-note
NONE
```

Fix syntax on envconfig

---

pkg/config/feature_config.go

```release-note
The UI elements for displaying when an API key was last used is now **ON** by default. To disable this, set `ENABLE_API_KEY_LAST_USED_AT` to false.
```

Enable viewing API key usage by default

---

assets/enx-redirect/report/header.html
assets/enx-redirect/report/index.html
assets/server/realmadmin/_form_codes.html
assets/server/realmadmin/_form_sms.html
internal/clients/app_sync.go
pkg/controller/appsync/handle_sync_test.go
pkg/controller/appsync/helpers.go
pkg/controller/appsync/helpers_test.go
pkg/controller/userreport/index.go
pkg/controller/userreport/send.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_test.go
pkg/database/token_test.go
pkg/integration/enx_redirect_test.go

Fixes #2061
Towards #1928
* Sync agency image from appsync feed
* Display agency image on appropriate background color for user report
* Change `User Report` templates and guidance/restriction to require short codes `[code]`
```release-note
Appsync service will pull agency images if available.
Agency images will show up on the user-report webview
Changed rules on user-report SMS text template
```

user report improvements

---

go.mod
go.sum
pkg/api/api.go
pkg/controller/issueapi/gen_code.go
pkg/controller/issueapi/phone.go
pkg/controller/issueapi/phone_test.go
pkg/controller/issueapi/validate_code.go
pkg/controller/userreport/send.go
pkg/database/realm.go
pkg/database/token_test.go
pkg/database/vercode_test.go

Towards #1928 
* Add phonenumber lib
* Canonicalize phone numbers (E164) before calculation of HMAC for user-report
* Require realm to have default SMS country when user report enabled
```release-note
Always store HMAC of E164 version of a phone number so that different formats and presence/absence of country code are treated the same.
```

Always use HMAC os E164 format phone number

---

assets/server/admin/realms/edit.html
docs/api.md
pkg/api/api.go
pkg/controller/admin/realms.go
pkg/controller/issueapi/handle_issue_test.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/issueapi_test.go
pkg/controller/issueapi/send_sms.go
pkg/controller/issueapi/validate_code.go
pkg/database/migrations.go
pkg/database/realm.go

This introduces new optional fields to the issue API request and response fields. If `onlyGenerateSMS` is specified in the request, the response will returned the compiled (and signed) SMS message. This feature must be enabled by a system admin on a per-realm basis.
```release-note
Introduce new optional fields to the `/issue` API for requesting the generated SMS message. This feature must be enabled on a per-realm basis.
```

Add support for returning generated SMS via the admin API

---

.github/workflows/ci.yaml
.golangci.yaml
assets/server/admin/realms/edit.html
assets/server/realmadmin/_form_codes.html
docs/api.md
pkg/api/api.go
pkg/controller/issueapi/handle_issue_test.go
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/issueapi_test.go
pkg/controller/issueapi/phone.go
pkg/controller/issueapi/validate_code.go
pkg/controller/issueapi/validate_code_test.go
pkg/controller/realmadmin/settings_modify.go
pkg/controller/userreport/controller.go
pkg/controller/userreport/index.go
pkg/controller/userreport/metrics.go
pkg/controller/userreport/send.go
pkg/controller/userreport/send_test.go
pkg/database/database.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_test.go
tools/seed/main.go

```release-note
Add functionality for PHAs to use custom SMS gateways for user report via webhooks. This feature requires a system admin to enable generated SMS on the realm first. If enabled, PHAs will be able to configure a Webhook URL for user report. When a user submits their diagnoses, the verification server will send a request to the PHAs server, and the PHA can issue the SMS. For more information, please see the [documentation](https://github.com/google/exposure-notifications-verification-server/blob/main/docs/api.md#user-report-webhooks).
```

Add webhook functionality for user report

---

docs/playbooks/alerts/UserReportWebhookError.md
terraform/alerting/alerts.tf

Add alert for user-report webhook errors

---

internal/i18n/locales/es/default.po

```release-note
Fix error in Spanish translations for user-report
```

fix trailing . in ES translations

---

assets/server/admin/realms/edit.html
assets/server/admin/realms/index.html
assets/server/realmadmin/smskeys.html

* Add more at-a-glance info to system admin overview
```release-note
Add additional info to system admin realm overview including if abuse prevention is enabled and if authenticated SMS is enabled.
```

add more to admin display

---

internal/envstest/enx_redirect.go
internal/routes/enx_redirect.go
pkg/config/feature_config.go
pkg/controller/userreport/index.go
pkg/controller/userreport/index_test.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/2101
```release-note
Add system-level feature configuration `ENABLE_USER_REPORT_WEB` to enable user report webview. This was previously always enabled, but **this changes the default behavior** to be disabled by default. System admins should set `ENABLE_USER_REPORT_WEB` to `true` to continue to support the webview on their system.
```

Re-add system-level feature configuration to disable user report webview

---

internal/i18n/i18n.go
internal/i18n/i18n_test.go
internal/i18n/locales/ja/default.po
pkg/controller/userreport/controller.go
pkg/controller/userreport/index.go
pkg/controller/userreport/send.go

* Fixes bug where the matcher didn't allow a realm to have a wider language set than the system language set.
* Adds test coverage
* Fixes syntax issue in JA translations
```release-note
Synced realm translations can be a wider set than the system translations (EN Express only)
```

allow different language matchers for static and dynamic translations

---

assets/server/mobileapps/show.html
internal/appsync/app_sync.go
pkg/controller/appsync/helpers.go
pkg/controller/appsync/helpers_test.go
pkg/controller/redirect/appstore.go
pkg/controller/redirect/helpers.go
pkg/controller/redirect/helpers_test.go
pkg/controller/redirect/index.go
pkg/controller/redirect/index_test.go
pkg/controller/redirect/redirect.go
pkg/database/migrations.go
pkg/database/mobile_app.go

* introduce headless android from the apps.json feed
* display that status
* change default redirect for android devices to the built in picker
```release-note
Adds support for Android Headles ENX picker protcol. By default redirect to OS pickers when nothing else is known.
```

change redirect defaults, include headless android ENX

---

pkg/controller/userreport/send.go

* scrub phone number in log line from user report
* this function is not in use in production yet 
```release-note
Scrub phone numbers from user report log lines
```

scrub phone number from failed SMS log line

---

pkg/config/cleanup_server_config.go
pkg/controller/cleanup/handle_cleanup.go
pkg/database/authorized_app_stats.go
pkg/database/authorized_app_stats_test.go
pkg/database/external_issuer_stats.go
pkg/database/external_issuer_stats_test.go
pkg/database/realm_stats.go
pkg/database/realm_stats_test.go
pkg/database/user_stats.go
pkg/database/user_stats_test.go

```release-note
Delete statistics that are more than 30 days old. This retention period can be configured by setting `STATS_MAX_AGE` on the cleanup service. The minimum value is 7 days and the maximum retention period is 60 days. This replaces the existing `KEY_SERVER_STATS_MAX_AGE` variable.
```

Expire all stats after 30 days

---

pkg/config/cleanup_server_config.go

Change stats retention bounds

---

docs/api.md

Signed-off-by: Mike Helmick <helmick@google.com>
* clarify API docs for user report verify calls
```release-note
None
```

clarify API docs for user report verify call and nonce mismatch

---

assets/server/static/js/application.js

```release-note
Fixes a bug where some successfully issued codes on bulk upload wouldn't appear in results CSV file.
```

ensure successful requests end up in download

---

assets/assets.go
assets/server/header.html
builders/build.yaml
pkg/render/assets.go
pkg/render/renderer.go

In dev, they'll remain separate. In prod, they'll be combined and minified into a single file. This also adds SRI integrity hashes.
This doesn't _actually_ separate any of the files. It just adds the ability to do so in the future.
```release-note
Add SRI integrity hashes to custom css and javascript. SRI was already present for external assets, but this includes the check on internal assets as well.
```

Allow separating css/js assets into multiple files

---

docs/playbooks/alerts/CloudRunBreakglass.md
terraform/alerting/alerts.tf
terraform/alerting/monitoring.tf
terraform/alerting/variables.tf

```release-note
Add alerts for when a Cloud Run service is deployed using breakglass (without Binary Authorization). Like the `HumanAccessedSecret` alert, there may be legitimate reasons for a human to perform this operation, but it should be carefully checked and audited. Due to eventual consistency, the initial Terraform apply may fail due to missing metric. After 5 minutes, you can run the Terraform apply again to converge.
```

Alert for Cloud Run deployments that bypass Binary Authorization

---

assets/enx-redirect/report/index.html
assets/server/codes/bulk-issue.html
assets/server/login/login.html
assets/server/mobileapps/show.html
assets/server/realmadmin/_form_security.html
assets/server/realmadmin/_form_sms.html
assets/server/realmadmin/_stats_external_issuers.html
assets/server/realmadmin/keys.html

HTML links that open in a new tab or window allow the target page to access the DOM of the origin page using `window.opener`. These are mostly trusted sources, but the introduction of user-supplied "learn-more" links necessitates this now.
Note that internal (relative) links do not require this rel.
```release-note
Ensure all external links specify noopener and noreferrer.
```

Ensure external links specify noopener and noreferrer

---

scripts/dev

This is an old artifact since it's set in .env now, but it messes up your environment if you run init after sourcing env, since it overwrites the value.
```release-note
NONE
```

Don't set DB_ENCRYPTION_KEY in init script

---

assets/server/realmadmin/_form_sms.html
pkg/controller/realmadmin/express_disable.go
pkg/controller/realmadmin/express_enable.go
pkg/database/realm.go
pkg/integration/enx_redirect_test.go

Fixes #2152 
* Uniformity in default templates
* adds dynamic / live validation of SMS templates on the page
* Makes "user report" validation rules non-special (same as other templates)
ENX Enabled Example
Non-ENX example
Too long
```release-note
Fixes default SMS template and SMS template validation issues. SMS Template validation is now also done in the live preview on the settings page.
```

improve sms template validation

---

assets/server/admin/mobileapps/index.html
assets/server/admin/mobileapps/show.html
internal/routes/server.go
pkg/controller/admin/mobile_apps.go
pkg/controller/admin/mobile_apps_test.go
pkg/database/mobile_app.go
pkg/database/mobile_app_test.go
pkg/database/scopes.go

This was previously broken because it links to the mobile app ID of the currently-selected realm instead of a system-wide view.
```release-note
Add a page for system administrators to view information about a realm's mobile apps. This is useful for diagnosing syncing issues without needing to join the realm.
```

Add admin mobileapps show page

---

pkg/controller/appsync/helpers.go
pkg/controller/redirect/helpers.go
pkg/controller/redirect/helpers_test.go
pkg/controller/redirect/index_test.go

```release-note
For Android redirects, always hint to the region where possible when redirecting to the picker.
```

android picker region redirects when possible

---

assets/server/static/js/_flash.js

Despite all documentation saying otherwise, Firefox does not support private fields.
```release-note
NONE
```

Javascript is the best language and totally widely supported

---

assets/enx-redirect/report/header.html
assets/enx-redirect/report/index.html
assets/enx-redirect/report/issue.html
internal/i18n/locales/ar/default.po
internal/i18n/locales/bn/default.po
internal/i18n/locales/de/default.po
internal/i18n/locales/en/default.po
internal/i18n/locales/es/default.po
internal/i18n/locales/fil/default.po
internal/i18n/locales/fr/default.po
internal/i18n/locales/id/default.po
internal/i18n/locales/it/default.po
internal/i18n/locales/ja/default.po
internal/i18n/locales/mn/default.po
internal/i18n/locales/pt/default.po
internal/i18n/locales/th/default.po
internal/i18n/locales/tr/default.po

* UI changes for user report web view - rounded corners, floating form fields, label reorder.
* agreement text will not be PHA customizable
(just using CA logo as demonstration, it does not imply endorsement of this feature in any way)
```release-note
User report web view redesign and refresh of default strings and translations.
```

user report redesign + additional translations

---

assets/enx-redirect/header.html
assets/enx-redirect/report/header.html
assets/server/header.html

```release-note
Update logo colors and purge favicon caches on release.
```

Use correct EN logo color, cache bust assets on release

---

internal/project/util.go
pkg/config/cleanup_server_config.go
pkg/database/authorized_app.go
pkg/database/realm.go
pkg/database/user.go
tools/seed/main.go

I've verified our charts and sliding windows work appropriately. There's no noticeable UI lag.
```release-note
Extend statistics retention to 90 days.
```

Extend stats retention to 90 days

---

pkg/database/composite_stats.go
pkg/database/composite_stats_test.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/2185
```release-note
Fix an error that could occur when statistics for a realm are missing or incomplete.
```

Fix stats NPE exception when realmstats are not present

---

internal/routes/adminapi.go

Fixes lack of route supporting `/api/stats/realm/api-keys/:id.{csv,json}` path from api doc:
[https://github.com/google/exposure-notifications-verification-server/blob/5de1965a9d735895067be6f8b69a421fa639ec3b/docs/api.md](url)
```release-note
Add route for api-key stats to adminapi
```

adding routes for realm api-key stats

---

go.mod
go.sum
pkg/controller/stats/composite.go
pkg/database/composite_stats.go
pkg/database/realm_stats.go

```release-note
Trim leading empty days from stats charts and exports. This has become more frequent with longer retention and display period.
```

trim leading empty days from composite stats

---

pkg/database/user_report.go
pkg/database/user_report_test.go

Fixes #2196
* fix bug where deletion time was not obeyed
```release-note
IMPORTANT BUG: Fix bug where user-report phone de-duplication records would be purged too early.
```

correctly purge claimed user reports

---

cmd/e2e-runner/main.go
pkg/controller/e2erunner/e2erunner.go
pkg/controller/e2erunner/handlers.go
pkg/controller/e2erunner/metrics.go

This is so metrics registration is outside of a main package (and thus importable by other packages).
```release-note
NONE
```

Move e2e-runner into a controller package

---

pkg/controller/cleanup/handle_cleanup.go
pkg/controller/cleanup/handle_cleanup_test.go
pkg/database/membership.go

Clean up stale membership entries with no permissions

---

pkg/sms/twilio.go

There are a few failed errors in our logs indicating that sometimes Twilio responds with an EOF. According to a few threads I found online and in GitHub issues, this can occur when the client Keep-Alive isn't honored by the server, but the server doesn't communicate this properly. To mitigate this, this commit does two things:
1. Set req.Close = true. This disables the client from requesting a Keep-Alive.
2. Retry on network-level connectivity issues. Note that we explicitly do NOT retry on HTTP responses, even if they are a non-200. http.Do only returns an error when the underlying transport failed at the network layer, which is explicitly what we want to retry.
```release-note
Add resiliency against temporary network connectivity issues when sending SMS. 
```

Retry Twilio communication on transient network errors

---

.github/workflows/terraform.yml
terraform/alerting/variables.tf
terraform/variables.tf

This bumps providers to their latest versions, which support Apple Silicon.
Fixes https://github.com/google/exposure-notifications-verification-server/issues/2211
```release-note
Update required Terraform and Terraform provider versions to the latest available to support Apple Silicon (M1).
```

Upgrade Terraform and provider versions

---

scripts/build
scripts/deploy
scripts/migrate

* Force git commands in build scripts to run inside root project directory.  Fixes an issue where git commands are run in another repository (for example, when this repository is pulled as a terraform module in a separate repo)
```release-note
Force git commands in build scripts to run inside root project directory
```

run git validation commands from inside the root folder

---

pkg/signatures/sms.go

* Workaround a bug in Android SMS intercept where if the last piece of the SMS template is a link, the `\nAuthenticated` doesn't allow the link to get parsed correctly. Inserting a space reliably solves this problem.
```release-note
Fix an issue where SMS templates that end in a link might cause SMS intercept to not fire on Android.
```

add space between message and signature

---

internal/routes/adminapi.go
internal/routes/apiserver.go
internal/routes/enx_redirect.go
internal/routes/server.go
pkg/controller/healthz.go

Fixes #2215
```release-note
Add "maintenance_mode" field to /health endpoints for adminapi, apiserver, server, and enx_redirect
```

add maintenance_mode field to health endpoint

---

docs/user-report-webview.md
internal/clients/enx_web.go
internal/routes/enx_redirect.go
pkg/config/redirect_config.go
pkg/controller/userreport/index_test.go
tools/user-report-web/main.go

```release-note
Allows HTTP GET request method (in addition to POST) for initiating the user report webview. The API key and nonce must still be passed as HTTP headers (unless dev mode is also enabled). dev mode should NOT be enabled in production to avoid logging the API key query params.
```

support GET when launching user report webview

---

terraform/service_appsync.tf
terraform/service_backup.tf
terraform/service_cleanup.tf
terraform/service_e2e_runner.tf
terraform/service_modeler.tf
terraform/service_rotation.tf
terraform/service_stats_puller.tf
terraform/variables.tf

```release-note
Make Cloud Scheduler timezone configurable in Terraform via `var.cloud_scheduler_timezone` and update the default value to UTC time.
```

Make scheduler timezone configurable, default to UTC

---

terraform/alerting/alerts.tf

* Change `alignment_period` for the CodesClaimedRatioAnomaly alert so that counts can be added up over the full duration of the alerting period.  Otherwise, the alert will never fire, since the modeler runs every 4 hrs
* Fix `group_by_fields` to match correct field
* Change `alignment_period` for ElevatedSMSErrors to 5 min
```release-note
Fix parameters for the CodesClaimedRatioAnomaly and ElevatedSMSErrors alerts
```

Fix splitting for new alerts and aggregate over full modeler interval for CodesClaimedRatioAnomaly

---

assets/server/static/js/stats-codes.js
assets/server/static/js/stats-keyserver.js
assets/server/static/js/stats-sms-errors.js
pkg/database/key_server_stats.go
pkg/database/key_server_stats_test.go

Also be more defensive about having less data when rendering charts.
```release-note
Fix an issue with rendering charts when realms had less than 30 days worth of key server statistics.
```

Ensure minimum number of key server stats

---

assets/server/header.html
assets/server/realmadmin/_form_sms.html
assets/server/realmadmin/stats.html
internal/routes/server.go
pkg/config/feature_config.go
pkg/controller/flash/flash.go
pkg/controller/flash/flash_test.go

This removes the TODOs in prep for the next release.
```release-note
NotifyAnomalies and EnableSMSErrorWebhook are now enabled by default and cannot be disabled.
```

Remove code and update defaults for next release

---

.github/workflows/ci.yaml

This is a native feature now.
```release-note
NONE
```

Automatically cancel existing runs when a new commit is pushed

---

pkg/controller/admin/email.go
pkg/controller/admin/realms.go
pkg/controller/admin/sms.go
pkg/controller/apikey/disable.go
pkg/controller/apikey/enable.go
pkg/controller/login/reset_password.go
pkg/controller/login/select_password.go
pkg/controller/login/select_realm.go
pkg/controller/login/verify_email_send.go
pkg/controller/realmkeys/activate.go
pkg/controller/realmkeys/create.go
pkg/controller/realmkeys/save.go
pkg/controller/realmkeys/upgrade.go
pkg/controller/userreport/send.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/2274
```release-note
Ensure validation errors always return an HTTP 422 response code for the web interface.
```

Ensure BindForm failures render as 422

---

go.mod
go.sum
internal/routes/apiserver.go
pkg/config/api_server_config.go

```release-note
Allows for a max latency injected for chaff requests, default is set to 1000 ms and is configurable.
```

upgrade chaff library, add max latency

---

pkg/database/realm.go
terraform/service_modeler.tf
terraform/service_server.tf
terraform/services.tf

```release-note
Add a global configuration option (applies to all realms) to configure the number of standard deviations away from the norm before behavior is consider an anomaly. You can configure this value by setting `ANOMALY_ALLOWED_STDEVS` on the `server` and `modeler` components to any positive float value. The default value is 2.0.
```

Add configuration for number of stdevs to be considered anomaly

---

pkg/controller/modeler/modeler.go
pkg/database/realm.go

Alternatively, I could inline this in `realm.CodesClaimedRatioAnomalous` so the e2e realm would never be considered anomalous. Open to either.
```release-note
Ignore e2e realm in anomaly notifications.
```

Ignore e2e realm in anomaly detection notifications

---

internal/envstest/bootstrap.go
pkg/controller/modeler/modeler.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/realm_test.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/2285
```release-note
Ensure there is only one E2E realm and prohibit naming realms similarly to avoid confusion.
```

Ensure there's exactly one E2E realm

---

pkg/pagination/pagination.go

```release-note
Change default pagination to be 24 elements per page.
```

Change default pagination to be 24 elements

---

internal/clients/admin_api.go
internal/clients/api_server.go
internal/clients/app_sync.go
internal/clients/e2e.go
internal/clients/enx_redirect.go
internal/clients/enx_web.go
internal/clients/key_server.go

This will help debug issues, especially with the e2e runners
```release-note
Set a custom user-agent header when running e2e tests to make log identification easier
```

Set custom user-agent headers for clients

---

internal/clients/clients.go
internal/project/transport.go
pkg/controller/backup/handle_backup.go
pkg/controller/userreport/controller.go
pkg/controller/userreport/send_test.go
pkg/sms/twilio.go

Even if this doesn't _fix_ the issue, I think it's a reasonable change. My suspicion is that, since `http.DefaultTransport` is a global variable, another package is modifying the value of the dial timeout to be very low, and we are inheriting it everywhere. I haven't been able to _prove_ that, but that's my theory as to why we're seeing timeouts for such small times. 
This introduces a new project-level helper, `DefaultHTTPTransport` which returns a pointer to a new allocation of an `http.Transport` on each invocation with no shared state. Even if this doesn't end up being the root cause, it will prevent the situation I described above from ever arising.
```release-note
NONE
```

Use a custom transport on all clients

---

internal/clients/clients.go
internal/project/util.go

@yegle 
```release-note
NONE
```

Add a way to request debug response headers from the GFE

---

cmd/appsync/main.go
cmd/backup/main.go
cmd/cleanup/main.go
cmd/e2e-runner/main.go
cmd/metrics-registrar/main.go
cmd/modeler/main.go
cmd/rotation/main.go
cmd/stats-puller/main.go
internal/clients/clients.go
internal/envstest/server.go
internal/project/transport.go
internal/routes/adminapi.go
internal/routes/apiserver.go
internal/routes/enx_redirect.go
internal/routes/server.go
pkg/controller/backup/handle_backup.go
pkg/controller/context.go
pkg/controller/controller.go
pkg/controller/middleware/logger.go
pkg/controller/middleware/trace_id.go
pkg/controller/middleware/trace_id_test.go
pkg/controller/userreport/controller.go
pkg/controller/userreport/send_test.go

```release-note
Improve tracing of requests that span multiple services (like the e2e runer)
```

Extract GCP trace ID onto context and inject in clients

---

internal/appsync/app_sync.go
pkg/controller/appsync/helpers.go
pkg/controller/appsync/helpers_test.go

```release-note
For user-report webview, use agency background color instead of agency color.
```

read header color instead of agency color

---

internal/appsync/app_sync.go
pkg/controller/appsync/helpers.go
pkg/controller/appsync/helpers_test.go

Reverts google/exposure-notifications-verification-server#2303
This is unnecessary - the source of the drift was found somewhere else

Revert "read header color instead of agency color"

---

docs/playbooks/alerts/ElevatedSMSErrors.md
terraform/alerting/alerts.tf
terraform/alerting/variables.tf

```release-note
Allow server operators to ignore specific Twilio error codes in SMS alerts. Server operators can set the `ignored_twilio_error_codes` variable in the alerting module to a string list of error codes that should be ignored when determined if there are elevated SMS errors for a realm. This can be helpful for Twilio errors that are non-actionable, such as "30006" which means a message was sent to a landline phone number. This is a global configuration that applies to all realms on the server; there is no realm-specific configuration. This change affects the monitoring and alerting policy, not the data collection. Realms will still see all SMS errors in their statistics dashboard, even if that error code is excluded from the alerting policy.
```

Allow ignoring Twilio codes from alerts

---

pkg/controller/issueapi/send_sms.go
pkg/controller/issueapi/send_sms_test.go

```release-note
Fix an issue where the server might crash when a large number of codes were submitted to the SMS provider and the SMS provider rejects the request due to a queueing issue.
```

Fix NPE when queue is full

---

pkg/controller/metricsregistrar/create_metrics.go

Fixes https://github.com/google/exposure-notifications-verification-server/issues/2310
```release-note
Only register metric descriptors that have not yet been registered.
```

Only register unregistered metric descriptors

---

assets/server/realmadmin/_form_sms.html
pkg/controller/issueapi/issue.go
pkg/controller/issueapi/send_sms_test.go
pkg/controller/issueapi/validate_code.go
pkg/controller/realmadmin/settings_modify.go
pkg/database/migrations.go
pkg/database/realm.go
pkg/database/sms_config.go
pkg/database/sms_config_test.go
pkg/database/vercode.go

* Address queuing issues we've seen as case #s have risen
* Allow for user report to use a different phone number
```release-note
Allow user report to utilize a different "from" number for SMS sending. This can help reduce queuing and self report codes being blocked by a large bulk issue in a jurisdiction.
```

allow user report to use different SMS queue

---

pkg/database/vercode.go

* Use common constants from public API package instead of re-defining private versions.
```release-note
NONE
```

use common API constants instead of redefining

---

assets/server/admin/realms/index.html
assets/server/email/anomalies.txt
assets/server/email/sms_errors.txt
assets/server/header.html
docs/production.md
pkg/config/emailer_config.go
pkg/controller/emailer/handle_anomalies.go
pkg/controller/emailer/handle_anomalies_test.go
pkg/controller/emailer/handle_sms_errors.go
pkg/controller/emailer/handle_sms_errors_test.go

```release-note
Add support for setting CC and BCC on all system-sent emails. To configure this, see the production guide for sending system emails.
```

Add support for cc and bcc on system emails

---

assets/server/email/anomalies.txt
assets/server/email/sms_errors.txt
pkg/controller/emailer/handle_anomalies.go
pkg/controller/emailer/handle_anomalies_test.go
pkg/controller/emailer/handle_sms_errors.go
pkg/controller/emailer/handle_sms_errors_test.go

```release-note
Fix an issue where BCCed addresses would incorrectly appear on the email envelope, defeating the purpose of BCC.
```

Handle bcc addresses correctly

---

internal/project/time.go
internal/project/time_test.go

Add helper for truncating times to the hour

---

assets/server/realmadmin/_form_codes.html

```release-note
realm admin label for short code expiration now includes user report (if enabled) for clarity
```

add optional label for short code expr

---

assets/server/apikeys/show.html
pkg/controller/apikey/create.go
pkg/controller/apikey/create_test.go
pkg/controller/apikey/show.go
pkg/controller/session.go

```release-note
Centralize logic on how API keys are injected into the session.
```

Move API key session storage into a helper, add log statement

---

assets/server/admin/realms/edit.html
assets/server/admin/realms/index.html
pkg/controller/admin/realms.go
pkg/controller/codes/bulk_issue.go
pkg/controller/codes/controller.go
pkg/controller/codes/index.go
pkg/controller/codes/issue.go
pkg/controller/issueapi/handle_issue.go
pkg/controller/issueapi/handle_issue_test.go
pkg/controller/issueapi/issue.go
pkg/database/migrations.go
pkg/database/realm.go

Fixes #2338
* system admin realm overview displays quick status
* Per-realm settings to change
* Warming on realm code issue page
```release-note
Allows for server admins to place individual realms in maintenance mode to facilitate EN turndown in a region.
```

Add realm level maintenance mode

---

pkg/controller/redirect/helpers.go
pkg/controller/redirect/helpers_test.go

* accept macintosh desktop user agents for redirect
```release-note
Accept desktop user agents from Macs. iPhone where the browser is set to "always request desktop" mode enabled, currently get an error if they tap on the link in the SMS.
```

Secret agent man

---

pkg/database/composite_stats.go
pkg/database/composite_stats_test.go
pkg/database/migrations.go
pkg/database/realm_stats.go
pkg/database/realm_stats_test.go
pkg/database/token.go

* Add a new realm stat for user_codes_invalid, incremented when a valid code is presented, but the nonce doesn't match. This is an indicator of people sending codes to someone else's phone number.
```release-note
Adds new statistic for user report invalid codes. This if effectively a measure for when a user report is sent do a different device than the one requesting it.
```

[WIP] increment stats for bad nonce

---

assets/server/realmadmin/_form_sms.html
pkg/database/realm.go
pkg/database/realm_test.go

* disallow newlines and repeated spaces in SMS template, many newlines can cause messages to be flagged and not delivered.
```release-note
Disallow newlines and repeated spaces in SMS template, many newlines can cause messages to be flagged and not delivered. Existing SMS templates are not impacted, but will be automatically changed on the next realm edit and errors will appear in the settings page when editing.
```

disallow newlines and repeated whitespace in SMS templates

---

assets/server/realmadmin/_stats_codes.html
assets/server/static/js/stats-codes.js
pkg/database/realm.go
pkg/database/token.go
pkg/database/token_test.go
tools/seed/main.go

* Adds chart for bad nonce / device mismatch
* Adds corresponding help
* Fixes bug introduced in previous commit
Added line to chart
Added help text
```release-note
Adds a chart on the realm statistics page that indicates when a user-report code was requested from one device, but sent to another (and therefore not able to be claimed).
```

add charting for bad nonce / device mismatch

---

assets/enx-redirect/header.html
assets/enx-redirect/report/header.html
assets/server/codes/bulk-issue.html
assets/server/firebase.html
assets/server/header.html
pkg/render/assets.go

The new version of firebase and firebase-auth require a significant refactoring of our Javascript code; we would need to migrate to modules and use a bundler like Webpack. Fortunately there's a compat layer we can use for now to minimize code changes, but this is something we'll need to think about long term.
Fixes GH-2357
```release-note
Update Javascript and CSS elements to bootstrap to 5.2.0 and Firebase to 9.9.0.
```

Update CSS/JS elements to their latest versions

---

go.mod
go.sum
pkg/controller/modeler/modeler.go
pkg/controller/modeler/modeler_test.go

Due to floating point math differences between Intel and Arm, we want to round the modeler result before storing it. This is mostly for tests, since in practice the value is +-0.000000000001.
Fixes GH-2358
```release-note
Update modeler code to handle floating point math differences between Intel and Arm processors.
```

Round modeler results

---

pkg/config/cleanup_server_config.go

```release-note
Change the default minimum self-report interval from 90 days to 30 days.
```

Change self-report interval from 90d to 30d

---

pkg/config/cleanup_server_config.go
pkg/controller/cleanup/handle_cleanup.go
pkg/database/realm.go
pkg/database/realm_test.go

* Fix user report cleanup
```release-note
Fix a potential race condition where the system could be configured to clean up user report records (delete nonce) while the user report code is still valid. This ensures that user reports across all realms are not cleaned up sooner than the realm with the longest short code timeout AND user report enabled.
```

User report cleanup

---

assets/server/realmadmin/_form_sms.html
pkg/database/realm.go
pkg/database/realm_test.go

Fixes #2369
* don't allow `[longexpires]` in the `User Report` sms template (since it always uses the short expires)
* add visual feedback to the UI for this.
```release-note
Stop allowing `longexpires` in the User Report SMS template since it always uses the `expires` value.
```

Don't allow longexpires in user report

---

assets/server/admin/realms/index.html
assets/server/static/js/admin-stats.js
internal/routes/server.go
pkg/config/server_config.go
pkg/controller/admin/code_stats.go
pkg/controller/admin/realms.go
pkg/database/realm.go
tools/seed/main.go

* Show system wide code issue/claim chart
```release-note
System admin: display a chart code global codes issued / code claimed
```

show system wide code issue/claim chart

---

pkg/config/server_config.go
pkg/controller/admin/code_stats.go
pkg/database/realm.go

* Exclude E2E-TEST realm from system code issue stats
```release-note
Note to operators, this will exclude a realm with a region code of E2E-TEST from system wide code issue/code claimed stats. If you have named this realm something else, you will need to override the EXCLUDE_FROM_SYSTEM_STATS environment variable.
```

No e2 e stats

---

assets/server/realmadmin/_stats_codes.html

```release-note
Removes advisory message on realm stats about device mismatch being a new stat with no history.
```

remove message that has aged out

---

docs/system-admin-guide.md

* Add instructions for server operators to turn down a realm.
```release-note
Add instructions for server operators to turn down a realm.
```

Add realm turndown instructions

---

pkg/controller/middleware/firewall_test.go
pkg/ratelimit/limitware/middleware.go
pkg/realip/realip.go
pkg/realip/realip_test.go

Also add a debug log for when we fall back to rate limiting by IP address.
```release-note
Fix an issue where rate limiting would be improperly applied to the entire system.
```

Look for client IP as the second-to-last entry in the IP list

---

pkg/database/realm.go

Fixes #2388
```release-note
Fixes a bug introduced in 1.16.2 that caused the system wide code usage chart to fail to render.
```

select empty nonce by OS so JSON will encode
