google/exposure-notifications-verification-server

terraform/service_apiserver.tf, terraform/service_cleanup.tf
This is necessary until GH-71 is fixed. Fixes GH-79.
=> Give all services access to the token

cmd/apiserver/main.go, cmd/cleanup/main.go, cmd/server/main.go, pkg/config/api_server_config.go, pkg/config/cleanup_server_config.go, pkg/config/config.go, pkg/config/server_config.go, pkg/controller/apikey/apikey.go, pkg/controller/apikey/savekey.go, pkg/controller/certapi/certificate.go, pkg/controller/cleanup/cleanup.go, pkg/controller/home/home.go, pkg/controller/index/index.go, pkg/controller/issueapi/issue.go, pkg/controller/middleware/html/html.go, pkg/controller/session/session.go, pkg/controller/signout/signout.go, pkg/controller/user/deleteuser.go, pkg/controller/user/saveuser.go, pkg/controller/user/user.go, pkg/controller/verifyapi/verify.go, terraform/service_apiserver.tf, terraform/service_cleanup.tf
* Change terraform to not grant cleanup/apiserver access to the CSRF secret.
Fixes #71
=> Refactor mono config to non-mono config

terraform/keys.tf, terraform/service_apiserver.tf, terraform/service_server.tf, terraform/services.tf
* correct crypto key version env vars for apiserver
* add firebaseauth.admin to the web server permissions
Fixes #86 
Fixes #89 
/cc @zssz @madhavajay
=> fix terraform issues

cmd/server/assets/home.html, pkg/api/api.go, pkg/controller/issueapi/issue.go
* Validate test type
* fix link to renamed default branch
=> Fix negative test being reported as likely.

terraform/service_apiserver.tf, terraform/service_cleanup.tf, terraform/service_server.tf, terraform/services.tf
=> Set PROJECT_ID on services

terraform/service_apiserver.tf, terraform/service_cleanup.tf, terraform/service_server.tf
=> Grant observability IAM permissions

cmd/server/assets/home.html, go.mod, go.sum, pkg/api/api.go, pkg/config/server_config.go, pkg/controller/certapi/certificate.go, pkg/controller/home/home.go, pkg/controller/issueapi/issue.go, pkg/controller/verifyapi/verify.go, pkg/database/migrations.go, pkg/database/token.go, pkg/database/token_test.go, pkg/database/vercode.go, pkg/database/vercode_test.go, pkg/otp/code.go
* replace test date with symptom onset date
* populate new claims from the exposure notification server claim set
=> Update verification protocol for v1.5

cmd/apiserver/main.go, cmd/server/assets/apikeys.html, pkg/controller/apikey/apikey.go, pkg/controller/apikey/savekey.go, pkg/controller/middleware/apikey.go, pkg/database/authorized_app.go, pkg/database/authorized_app_test.go, pkg/database/migrations.go
* Introduce Admin API keys, that will be used for issuing diagnosis codes
* Existing keys auto migrated to be device keys
* UI for creating these
=> Admin API Keys

cmd/apiserver/main.go, cmd/cleanup/main.go, cmd/server/main.go, go.mod, go.sum, pkg/config/api_server_config.go, pkg/config/server_config.go, pkg/ratelimit/config.go, terraform/main.tf, terraform/redis.tf, terraform/service_apiserver.tf, terraform/service_server.tf, terraform/services.tf, terraform/variables.tf
=> Switch to redis-based rate limiting

cmd/adminapi/main.go, cmd/get-code/main.go, pkg/api/api.go, pkg/config/admin_server_config.go, pkg/config/issue.go, pkg/config/server_config.go, pkg/controller/cover/cover.go, pkg/controller/issueapi/issue.go
Initial action is to issue verification codes. Uses same API shape as the Web version.
For #95
=> Add new API server for admin actions.

scripts/build, scripts/deploy, scripts/promote, terraform/service_admin_apiserver.tf
=> update terraform/build for adminapi

pkg/controller/issueapi/issue.go, pkg/controller/middleware/apikey.go, pkg/database/migrations.go, pkg/database/vercode.go, pkg/otp/code.go
=> Adds Tracking Information to Codes to allow auditing

cmd/server/main.go
Followup to https://github.com/google/exposure-notifications-verification-server/pull/113#discussion_r456794037
=> Move ipKeyFunc to allocate once

terraform/keys.tf, terraform/redis.tf, terraform/variables.tf
=> Make KMS and Redis regions configurable

cmd/server/main.go, pkg/render/html.go
=> Support reloading templates in dev

cmd/add-sms-config/main.go, cmd/add-users/main.go, cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/cleanup/main.go, cmd/migrate/main.go, cmd/server/main.go, go.mod, pkg/controller/home/home.go, pkg/controller/issueapi/issue.go, pkg/database/config.go, pkg/database/database.go, pkg/database/database_util.go, pkg/database/sms_config.go, pkg/database/sms_config_test.go
=> Allow pulling secrets in the database layer

cmd/add-realm/main.go, pkg/controller/user.go, pkg/database/sms_config.go
=> Followup PR comments

cmd/server/assets/selectrealm.html, pkg/controller/realm/select.go
=> Make realm changing nicer by defaulting to currently selected.

cmd/server/assets/header.html, cmd/server/assets/realm.html, cmd/server/main.go, pkg/controller/realmadmin/index.go, pkg/controller/realmadmin/save.go
only lets you change the realm name
next will be SMS settings things
Towards #143
=> Add basic realm admin page.

pkg/database/migrations.go
=> Fix PK constraint on users table on realm upgrade.

cmd/get-certificate/main.go, cmd/get-code/main.go, cmd/get-token/main.go, go.mod, go.sum, pkg/clients/apis.go, tools/e2e-test/main.go
* uses admin API to issue verification code
* uses api server to verify the code and exchange token for cert
* generates TEKs an publishes them to the key server
THIS REQUIRES SETUP
Must have a verificaiton server running with trust established to a key server.
Can be run 100% local if you start servers on different ports (default config).
=> Add command line tool to run the whole flow

terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_server.tf, terraform/variables.tf
=> Support custom domain mappings

.gitignore, cmd/get-certificate/main.go, cmd/get-code/main.go, cmd/get-token/main.go, pkg/clients/apis.go, pkg/jsonclient/client.go, tools/e2e-test/main.go
This will make it easier to send tracing information, also it helped me debug a typo when using the e2e test.
=> Add contexts to clients packages

cmd/add-users/main.go, pkg/config/cleanup_server_config.go, pkg/controller/cleanup/cleanup.go, pkg/controller/middleware/auth.go, pkg/controller/user/create.go, pkg/database/migrations.go, pkg/database/user.go, pkg/database/user_test.go
We can use soft deletes with gorm to "delete" users. Fixes GH-153.
=> Drop disabled users

pkg/database/config.go
* change DB_DEBUG to default false, prevent crash when DEV_MODE env var isn't set
```release-note
NONE
```
=> update db debug flag default

OWNERS
* Adding natwelch@google.com (me) to owners to improve number of people who can do reviews.
```release-note
NONE
```
=> Add icco to owners

pkg/controller/certapi/certificate.go
Bring fix for #187 back to v0.2 release branch, will tag v0.2.1 release
=> Cherrypick bug fix back to release2 branch

builders/migrate.yaml, pkg/database/migrations.go, scripts/migrate, terraform/database.tf, terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_cleanup.tf, terraform/service_server.tf
=> Update Terraform and migration scripts

pkg/config/server_config.go, pkg/database/config.go
=> Switch to built-in base64-bytes helper

scripts/dev
Makes dev easier
```release-note
NONE
```
=> Update dev script with new default variables

builders/migrate.yaml, cmd/migrate/main.go, pkg/config/config.go, pkg/database/migrations.go, scripts/migrate, terraform/database.tf
I ran into a few issues while trying to deploy:
1. Some mis-documentation about secrets
2. The migrate server didn't resolve secrets
3. The UUID addition would fail because SET DEFAULT and NOT NULL runs in the same transaction
```release-note
Update migrations to resolve secrets and fix broken migration for UUIDs on verification tokens
```
=> Update deployment/release with fixes

cmd/adminapi/main.go, cmd/server/main.go, pkg/api/api.go, pkg/clients/apis.go, pkg/controller/issueapi/codestatus.go, pkg/controller/issueapi/issue.go, pkg/database/vercode.go, pkg/database/vercode_test.go, tools/e2e-test/main.go
Issue https://github.com/google/exposure-notifications-verification-server/issues/109
* Create a query for codes by UUID
* Create a request/response for new check status API
* Logic for retrieval
* User/realm must match issuing user/realm
* expired/no result is notfound
* E2E test asserts code is 'claimed'
TODO: html interface
```release-note
CheckCodeStatus API allows user to check the status of an OTP code
```
=> CheckCodeStatus API

cmd/adminapi/main.go, cmd/apiserver/main.go
=> Update package descriptions

OWNERS
He's transitioning off the project
```release-note
NONE
```
=> Remove Chris from owners

pkg/api/api.go
```release-note
Fix inconsistency in ErrorReturn JSON structure
```
=> fix inconssitency w/ errorCode vs error_code

pkg/api/api.go, pkg/controller/issueapi/codestatus.go, tools/e2e-test/main.go
* Add the error fields to the CheckCodeStatusResponse struct
* Minor logging statement and a nil check
```release-note
Include errors in CheckCodeStatusResponse
```
=> Include error in codestatus response

pkg/controller/middleware/apikey.go, pkg/controller/middleware/auth.go, pkg/controller/middleware/csrf.go, pkg/controller/middleware/header.go, pkg/controller/middleware/method.go, pkg/controller/middleware/realm.go, pkg/controller/middleware/sessions.go, pkg/controller/middleware/template.go
Add middleware for requiring headers be present
```release-note
NONE
```
Release note is none because it's not used anywhere.
/assign @icco
=> Add header middlware

cmd/server/assets/header.html, cmd/server/assets/home.html, pkg/api/api.go, pkg/controller/home/home.go, pkg/controller/issueapi/issue.go
Fixes GH-224
```release-note
Support symptom date and test date in the UI
```
=> Support symptom date and test date

cmd/get-code/main.go, cmd/server/assets/home.html, cmd/server/assets/realm.html, pkg/clients/apis.go, pkg/controller/index/index.go, pkg/controller/issueapi/issue.go, pkg/controller/realmadmin/index.go, pkg/controller/realmadmin/save.go, pkg/database/migrations.go, pkg/database/realm.go, tools/e2e-test/main.go, tools/seed/main.go
Fixes GH-223
```release-note
Support per-realm config of allowed test types
```
=> Support per-realm config of allowed test types

pkg/database/migrations.go, pkg/database/user.go
```release-note
Use case-insensitive columns on unique fields
```
=> Use case-insensitive uniqueness

README.md, cmd/server/assets/index.html, pkg/config/server_config.go
Fixes GH-39
```release-note
Make Firebase TOS and Privacy URLs configurable
```
=> Make Firebase URLs configurable

pkg/ratelimit/limitware/middleware.go
Minor followups from GH-226
```release-note
NONE
```
/assign @icco
=> Add metric when rate limited, log errors, log scope

cmd/server/assets/header.html, tools/seed/main.go
Things were getting crowded for long names.
```release-note
Update to latest CSS framework version, make current realm more prominent
```
=> Move realm into another header

pkg/controller/middleware/auth.go
```release-note
Fix redirect loop when logging in with a non-existent user
```
=> Fix redirect loop with valid Firebase user, but non-database user

pkg/controller/codestatus/logic.go, pkg/controller/codestatus/show.go
* Fixing a few nits from: https://github.com/google/exposure-notifications-verification-server/pull/227
=> Followup on some nits

pkg/database/migrations.go
=> fix long code db migration

pkg/database/token.go
Fixes panic seemingly introduced by GORM update.
```release-note
NONE
```
=> fix gorm panic

cmd/add-users/main.go, cmd/get-certificate/main.go, cmd/get-code/main.go, cmd/get-token/main.go
=> Log info in commands

cmd/add-realm/main.go, cmd/add-users/main.go
* command line tools didn't previously support some items as secret refs
```release-note
NONE
```
=> change command line config processing so it can resolve secret://

cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/server/main.go, go.mod, go.sum, pkg/ratelimit/config.go, pkg/ratelimit/limitware/middleware.go
```release-note
Update ratelimiter package, add more logging
```
/assign @icco
=> Update rate limiter, add more logging

README.md
Fixes the verification flow chart in README.
```release-note
Fixes the verfication flow chart in README.
```
=> Fixes the verification flow chart.

cmd/server/assets/login.html
* This is just a div table, no need for the form / csrf token. Login action happens from javascript on click, not a form submission
=> Nit: remove form element

README.md, builders/migrate.yaml, pkg/database/config.go, pkg/database/database.go, pkg/database/migrations.go, pkg/database/token.go, pkg/database/vercode.go, pkg/database/vercode_test.go, scripts/dev, scripts/migrate, terraform/database.tf, terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_cleanup.tf, terraform/service_server.tf, terraform/services.tf
```release-note
HMAC verification codes in the database - this prevents someone with access to the database from (easily) retrieving the plaintext tokens
```
=> HMAC verification codes in the database

Dockerfile, builders/migrate.yaml
Fixes GH-220
```release-note
Upgrade to Go 1.15
```
/assign @icco
=> Upgrade to Go 1.15

cmd/server/assets/login/login.html
I added a permanent alert header to this page while I was making it to display state.
Now removing it and only adding the element as needed.
=> Add error flash in as needed

cmd/server/assets/login/login.html, tools/seed/main.go
This fixes a few nits with requiring email verification.
1. In the seed script, we use "example.com", so we can't actually verify that email. The seed script is now updated to verify the seed users via the SDK.
1. There was a bug where firebase could be fully loaded but jquery was not, leading to some fun races around form submission.
1. This makes the login form a form so you can submit it via enter and other assistive technologies. It also adds client-side validation. The form is still submitted via jquery - we hijack submit instead of button press.
```release-note
NONE
```
=> Handle verified emails

cmd/server/assets/realm.html
=> Fix form formatting on SMS template

cmd/server/assets/header.html, cmd/server/assets/login/login.html, cmd/server/assets/login/registerphone.html
* Move the error flash insertion to a javascript function
=> Move the error flash insertion to a javascript function

terraform/database.tf
=> Add an output with environment variables to run psql.

cmd/server/assets/login/login.html
```release-note
Update login screen layout
```
=> Center login form to match mocks

cmd/server/assets/firebase.html, cmd/server/assets/login/legacylogin.html, cmd/server/assets/login/login.html, cmd/server/main.go, pkg/controller/login/login.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/296
* Bring back the Firebase UI for creating new users.
* I still want to make a custom new-user flow, but this is faster for now
It will still work for non-2-factor auth users for full log-in.
Also studying this much better UX experience.
Currently this is broken because the new login ux expects a username/password to be already assigned.
=> Bring back the firebaseui login for new user flow

cmd/cleanup/main.go, pkg/controller/cleanup/cleanup.go, pkg/database/cleanup.go
```release-note
Fix data race in cleanup
```
=> Fix race in creating cleanup status

cmd/server/assets/login/registerphone.html, cmd/server/assets/login/signout.html
* Switched the signout success/fail to use our flash for UX consistency
* Added a 3 second redirect back to login
* Ensure the register-phone button enables on error
```release-note
Added a signout redirect back to login
```
=> Signout to use flash and redirect

cmd/server/assets/header.html, cmd/server/assets/login/_loginscripts.html, cmd/server/assets/login/create.html, cmd/server/assets/login/login.html
* Move the login auth watcher to its own file
* Pull it in for login and create
* Don't pull it in for other things
=> Nit: only need to load login script for login

pkg/controller/flash/flash.go
* Nit: clear should clear everything
* Don't think this code is used
=> Clear() should clear warnings

tools/e2e-test/main.go
=> Fix e2e test logging messages.

.gitignore
=> Ignore locally built binary files.

cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/cleanup/main.go, cmd/server/main.go, pkg/controller/apikey/show.go, pkg/controller/healthz.go
* /healthz was returning 404s, this makes it 200 by moving to /health and fix the call to RenderJSON
* Move /health from cleanup to server, where it should have been
```release-note
NONE
```
=> Healthz tweaks

cmd/server/assets/home.html
Fixes GH-350
```release-note
NONE
```
=> Clear countdown timers

terraform/README.md, terraform/variables.tf, terraform/versions.tf
```release-note
NONE
```
/cc @chaodaiG
=> Document production setup as a module

cmd/add-realm/main.go, cmd/add-users/main.go, cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/server/assets/codestatus/index.html, cmd/server/main.go, pkg/config/admin_server_config.go, pkg/config/api_server_config.go, pkg/controller/apikey/update.go, pkg/controller/context.go, pkg/controller/login/session.go, pkg/controller/middleware/apikey.go, pkg/controller/middleware/auth.go, pkg/controller/middleware/realm.go, pkg/controller/realmadmin/realmadmin.go, pkg/controller/realmadmin/save.go, pkg/controller/user/update.go, pkg/controller/user/user.go, pkg/database/authorized_app.go, pkg/database/realm.go, pkg/database/sms_config_test.go, pkg/database/user.go, terraform/README.md, terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_cleanup.tf
```release-note
Add caching layer for users, API keys, and realms
```
=> Cache users, api keys, and realms for 30s

pkg/database/migrations.go
Fixes #356
```release-note
NONE
```
=> need to upgrade realm in migrations that cause realm to be addressed

terraform/README.md
/assign @sethvargo 
/cc @yegle
=> Troubleshooting firebase ToS not accepted

cmd/server/assets/header.html
```release-note
Move realm settings under admin menu
```
=> Move realm settings under user dropdown

cmd/server/assets/home.html
Discourage copy-paste
```release-note
NONE
```
=> Disable text selection on short code

cmd/server/assets/home.html
* Expired time in < 1 second shows "Expires in false"
* Ensure we show expired
=> Nit: remove blip when showing expired time

terraform/service_server.tf
Give server permission to read keys
```release-note
NONE
```
=> Give server permission to read keys

cmd/server/assets/codestatus/_codescripts.html, cmd/server/assets/codestatus/show.html, cmd/server/assets/home.html, pkg/controller/codestatus/show.go
* Show the countdown when rendering code status
```release-note
Show countdown for code status. Format as list.
```
=> show code with countdown expiry

cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/server/main.go, pkg/controller/apikey/update.go, pkg/controller/healthz.go, pkg/controller/middleware/apikey.go, pkg/controller/middleware/auth.go, pkg/controller/middleware/realm.go, pkg/controller/realmadmin/realmadmin.go, pkg/controller/realmadmin/save.go, pkg/controller/user/update.go, pkg/database/database.go
=> Automatically clear caches on save

pkg/database/realm.go
Sort users and API keys
```release-note
Sort users and API keys
```
=> Sort things

pkg/database/realm.go
This code is unused
```release-note
NONE
```
=> Remove unused signing key code

cmd/add-realm/main.go, cmd/server/assets/realmkeys.html, go.mod, go.sum, pkg/controller/realmkeys/activate.go, pkg/controller/realmkeys/new.go, pkg/database/database.go, pkg/database/realm.go
Part of https://github.com/google/exposure-notifications-server/issues/913
:warning This requires https://github.com/google/exposure-notifications-server/pull/921 be merged first.
```release-note
NONE
```
=> Use new key manager interface

cmd/server/assets/codestatus/index.html
* Remove the maxwidth from the code-status form
* Formatting
=> Remove maxwidth from index

pkg/config/api_server_config.go, pkg/config/token_signing_config.go
* Token rotation code improvements
```release-note
NONE
```
/assign @jeremyfaller @sethvargo
=> make the code more better

pkg/controller/certapi/certificate.go
=> Fix err message

pkg/database/realm.go
Fixes #397
```release-note
CRITICAL FIX: Select correct realm's signing keys for multi-tenant signing. 
```
=> scope signing key read to selected realm

go.mod, go.sum
```release-note
Bump main server version to v0.5.1
```
=> Bump to main server v0.5.1

cmd/server/assets/realmkeys.html, cmd/server/main.go, go.mod, go.sum, pkg/controller/jwks/jwks.go, pkg/database/realm.go
Fixes #93
* Add /jwks/XX/XX endpoint for key collection.
* Fix typo
*
```release-note
NONE
```
=> Add jwks endpoint for return realm/key JSON encoded keys

builders/build.yaml
=> Push runner

terraform/service_e2e_runner.tf
Fixes #265 
Follow up of #417 
```release-note
Set up Cloud Scheduler to probe the e2e runner service handlers every 10min.
```
=> Set up CloudScheduler to probe every 10min.

cmd/server/assets/realmkeys.html
* Make the link to the jwks discovery more discoverable
```release-note
NONE
```
=> highlight public key discovery doc

builders/deploy.yaml
Fixes #430
```release-note
NONE
```
=> Fix image used by e2e-runner service.

pkg/render/render.go
* register 412 response code
```release-note
NONE
```
=> register 412 response code

go.mod, go.sum
* Bump ens dependency to v0.6.0
```release-note
NONE
```
=> pin to exposuer-notification-server v0.6.0

terraform/lb.tf, terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_server.tf, terraform/variables.tf
LB should be optional for dev clusters.
```release-note
NONE
```
=> Make load balancer configs optional.

cmd/server/assets/realm.html, pkg/database/realm.go
=> Small realm changes

.gitignore, terraform-e2e/README.md, terraform-e2e/main.tf, terraform/redis.tf, terraform/services.tf, terraform/variables.tf
=> Redis name configurable in terraform

cmd/server/assets/admin/realms.html
=> Change spacing on realms index

terraform/lb.tf
* Fixes issue where forwarding rules couldn't be created, as documented at https://github.com/hashicorp/terraform-provider-google/issues/7176
```release-note
NONE
```
=> Fix bug in GCLB terraform

cmd/server/assets/login/login.html, cmd/server/assets/login/resetpassword.html, cmd/server/main.go, pkg/controller/login/resetpassword.go
* User can enter email and get a password-reset email sent
```release-note
Include a password-reset page
```
=> Create reset password page

terraform/README.md, terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_cleanup.tf, terraform/service_server.tf
Fixes #
Update Terraform Readme
bump terraform version mention from 0.12 to 0.13.1
Fix terraform variable reference in deployment steps
=> Update Terraform Readme

terraform/README.md
=> Add migration docs for quick -> production

terraform/lb.tf
* Changes unmapped domains to show website.
```release-note
NONE
```
=> Change default service for GCLB

scripts/build, scripts/deploy, scripts/promote
* Adds nice echo messages so you know what you're doing
```release-note
NONE
```
=> Echo project id in scripts

cmd/server/assets/realmkeys.html, pkg/render/render.go
```release-note
Trim whitespace around public keys in the UI
```
=> Trim space around public keys

.gitignore, README.md, docs/production.md
=> Fix some docs inconsistencies

docs/api.md
=> Clarify that padding is b64-encoded

builders/promote.yaml
Cosmetic
```release-note
NONE
```
=> Fix build step names for promote

pkg/jsonclient/client.go, tools/e2e-test/main.go
=> Remove some unnecessary logs

terraform/README.md, terraform/alerting/notifications.tf, terraform/alerting/probers.tf, terraform/alerting/workspace.tf
Fixes #477 
```release-note
NONE
```
=> Update Terraform README re using alerting rules

cmd/server/assets/header.html, cmd/server/assets/users/_form.html, cmd/server/assets/users/new.html
* Makes a fix to CSS so chrome-autocomplete doesn't skew the placeholder location
* Uses the floating labels for new user / update user form
=> Floating labels for new user

terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_cleanup.tf, terraform/service_e2e_runner.tf, terraform/service_server.tf
=> Grant perms to HMAC keys

cmd/server/assets/header.html
* Ensures a dismiss X button is shown for success flash
=> Ensure success flash can be dismissed

docs/realm_guide.md
* Add some guidelines for user account protection
```release-note
NONE
```
=> add user account guidelines

terraform/database.tf
Fixes GH-498
```release-note
NONE
```
=> Build before migrating

cmd/server/assets/login/registerphone.html, cmd/server/assets/realm.html, cmd/server/main.go, pkg/controller/login/register.go, pkg/controller/login/signout.go, pkg/controller/middleware/mfa.go, pkg/controller/middleware/realm.go, pkg/controller/realm/index.go, pkg/controller/session.go, pkg/database/realm.go
Fixes #506
*  Enforces realm MFA with middleware, sets a  session bit so users are never prompted twice.
* Disable skip link for realms where MFA is required
=> Enforce realm MFA  as middleware

OWNERS
* Add @yegle to owners
```release-note
NONE
```
=> Add yegle to owners

terraform/alerting/dashboards/verification-server.yaml
=> Code issue attempt chart should also group by the issuing realm.

terraform/alerting/dashboards/verification-server.yaml
This was incorrectly removed in #494.
```release-note
NONE
```
=> Add rate_limited_count chart.

pkg/controller/user/index.go
* I made a dumb mistake. This fails for empty string with internal error, need to ignore that case
=> Check for empty string

builders/cloud-sql-exec, builders/migrate.dockerfile
Same as https://github.com/google/exposure-notifications-server/pull/996
```release-note
NONE
```
=> Fix migrate

cmd/server/assets/users/index.html, pkg/controller/user/index.go
* Adds a footer to the pagination to show the user where they are at in the total list
=> Add a pagination footer

pkg/config/redirect_config.go, pkg/controller/redirect/index.go
* ensure hostnames are always lowercased for comparision
```release-note
NONE
```
=> ensure we're comparing lowercase to lowercase

cmd/enx-redirect/main.go, pkg/config/redirect_config.go, pkg/controller/redirect/index.go, pkg/controller/redirect/redirect.go
* change to map based config for redirect service
* match wildcard
```release-note
NONE
```
/assign @icco 
/assign @sethvargo
=> change to map based config, match wildcard path

cmd/server/assets/users/_form.html, cmd/server/assets/users/index.html, pkg/controller/user/create.go, pkg/controller/user/delete.go, pkg/database/user.go
Fixes GH-518
```release-note
Allow system admins to remove themselves from realms
```
=> Allow system admins to remove themselves from a realm

scripts/e2e-test.sh
Previous PR https://github.com/google/exposure-notifications-verification-server/pull/524 was closed by stale and accidentally deleted original branch, creating a new one
=> Terraform smoke test use dynamic GCP projects

cmd/server/assets/_flash.html, cmd/server/assets/header.html, cmd/server/assets/login/login.html, cmd/server/assets/login/register-phone.html, cmd/server/assets/login/reset-password.html, cmd/server/assets/login/signout.html, cmd/server/assets/login/verify-email.html, cmd/server/assets/users/new.html
=> Fix javascript as toasts

pkg/controller/issueapi/issue.go
```release-note
Update stats to group by realm **id** instead of realm **name**
```
=> Use realmid

terraform/lb.tf
Continues  #549
```release-note
Iff redirect_domain_map is specified in terraform, we will setup a second IP and LB for it.
```
=> Add Redirect Loadbalancer

cmd/server/assets/home.html, cmd/server/assets/realm.html, go.mod, go.sum, pkg/controller/home/home.go, pkg/controller/realmadmin/save.go, pkg/controller/session.go, pkg/database/migrations.go, pkg/database/realm.go
Fixes GH-576
```release-note
Add customizable realm welcome banner
```
=> Add customizable realm welcome banner

cmd/server/assets/login/select-password.html, cmd/server/main.go, pkg/config/server_config.go, pkg/controller/login/login.go, pkg/controller/login/select_password.go, pkg/database/migrations.go, pkg/database/user.go, pkg/database/user_test.go
Issue https://github.com/google/exposure-notifications-verification-server/issues/575
* Record the time of password change. This will be used to enforce password rotation
```release-note
Record password reset time
```
=> Record password reset time

terraform/service_redirect.tf
* Fix a typo from #558
```release-note
NONE
```
=> Typo in image name

builders/build.yaml, builders/enx-redirect.dockerfile, builders/server.dockerfile, terraform/services.tf
/cc @icco 
```release-note
Fix missing assets on redirect service
```
=> Fix missing assets for redirect service

pkg/controller/middleware/emailverified.go
=> Handle nil realm in logic

terraform/service_redirect.tf, terraform/services.tf
```release-note
NONE
```
/assign @icco
=> Service name should be enx-redirect

terraform/lb.tf, terraform/service_redirect.tf, terraform/services.tf, terraform/variables.tf
=> More fixes for enx redirect config

cmd/server/assets/realmadmin/_form_codes.html
* fix list item duplicate
```release-note
NONE
```
=> remove double li

cmd/enx-redirect/main.go, pkg/controller/healthz.go
* Add /health so we can health check redirect server domains as well.
```release-note
NONE
```
=> Add /health to redirect server

terraform/lb.tf
* Not sure how I missed this, but copy pasta error... we really should have put this in a separate file.
```release-note
NONE
```
=> Fix lb.tf typos in redirect LB

terraform/services.tf
* Config map needs colons not equal signs
```release-note
NONE
```
=> Colons not equal signs

go.mod, go.sum
* Upgrade key server dep to 0.9.1
```release-note
NONE
```
=> Upgrade key server dep to 0.9.1

cmd/server/assets/realmadmin/_form_sms.html, pkg/controller/realmadmin/settings.go
Fixes #620
```release-note
NONE
```
=> Only save SMS on the SMS form

cmd/server/assets/login/_loginscripts.html, cmd/server/assets/login/account.html, cmd/server/assets/login/login.html, cmd/server/assets/login/register-phone.html, cmd/server/assets/users/import.html
Issue https://github.com/google/exposure-notifications-verification-server/issues/608
* If there are enrolled factors, show them in a list
* Delete link for removing an enrolled factor
* Minor fix to make pin-confirm div hide on success
```release-note
Allow users to delete enrolled factor for MFA
```
=> Allow deletion of factors

cmd/server/assets/login/register-phone.html
* Clear the text from the register fields after success (so you can register again)
* Redirect to /signout if auth becomes invalid
* Show/hide factors as they are added
=> Minor fixes to MFA page

cmd/server/assets/realmadmin/edit.html
```release-note
Fix inability to visit ENX tab
```
=> Fix ID on express tab

pkg/database/realm.go, pkg/database/user.go
```release-note
Use more consistent ordering on realm selection and lists pages
```
=> Use more consistent ordering on realm selection and lists pages

cmd/server/assets/login/_loginscripts.html, cmd/server/assets/login/login.html, cmd/server/assets/login/register-phone.html
Fixes https://github.com/google/exposure-notifications-verification-server/issues/608
* Show a selection of multi-factors if > 1 is registered
```release-note
Select MFA factor at login
```
=> Multi-factor selection at login

cmd/server/assets/login/login.html, cmd/server/assets/login/register-phone.html, cmd/server/assets/login/signout.html
Fixes https://github.com/google/exposure-notifications-verification-server/issues/629
* For now, keep the 3 second wait on signout redirect but only if there are children in the flash container
* Minor formatting
=> Wait for signout redirect if there is an error

cmd/server/assets/admin/_nav.html, pkg/controller/middleware/currentpath.go
* Fix paths to paths instead of files for the admin pills
=> Fix paths for nav

cmd/server/assets/home.html
* The #errors div doesn't exist any more
=> Switch to flash from error div

cmd/server/assets/admin/_nav.html, cmd/server/assets/admin/realms/edit.html, cmd/server/assets/admin/realms/index.html, cmd/server/assets/admin/realms/new.html, cmd/server/assets/admin/sms/show.html, cmd/server/assets/header.html, cmd/server/assets/realmadmin/_form_sms.html, cmd/server/main.go, pkg/controller/admin/realms.go, pkg/controller/admin/sms.go, pkg/database/realm.go, pkg/database/sms_config.go
Fixes GH-432
```release-note
Add forms for system SMS configs and sharing logic
```
=> Add forms for system SMS configs and sharing logic

pkg/config/modeler.go, pkg/controller/modeler/modeler.go, pkg/controller/modeler/modeler_test.go
```release-note
Add upper max and lower min to modeler
```
=> Add hard max and min to modeler

go.mod, internal/firebase/firebase.go, internal/firebase/password_reset_email.go, internal/firebase/verify_password_reset_code.go
=> Add mini firebase auth SDK

terraform/redirect-lb.tf
* Duplicate resource is identical, could use old one but this makes it cleaner.
```release-note
NONE
```
=> Fix duplicate resource name

cmd/server/assets/users/import.html, cmd/server/assets/users/new.html, cmd/server/assets/users/show.html, cmd/server/main.go, internal/firebase/verify_password_reset_code.go, pkg/controller/user/create.go, pkg/controller/user/importbatch.go, pkg/controller/user/update.go, pkg/controller/user/user.go
* Uses Seths internal FB client to send the password reset on user create
* Eliminates a fail-in-the-middle scenario
=> Use the internal Firebase client to send password reset

terraform/redirect-lb.tf
```release-note
NONE
```
/assign @icco
=> Fix string concat

terraform/redirect-lb.tf, terraform/verification-lb.tf
* This is an oversight from #654
```release-note
NONE
```
=> Fix Redirect Name Conflict

terraform/verification-lb.tf
* Can't rename URLMaps without downtime, revert name change
```release-note
NONE
```
=> Undo https-redirect name change

pkg/database/database.go
=> Handle realField as nil in callbacks

pkg/database/migrations.go, pkg/database/realm.go, pkg/database/sms_config.go
=> Give gorm the column stats so previous auto-migrates don't fail

pkg/database/migrations.go
=> Some final updates to the migration

terraform/alerting/monitoring.tf
Update to a valid aligner for DELTA metric.
=> Change aligner to delta

docs/development.md, scripts/dev
=> Improve dev docs, make it possible to run both servers locally

cmd/server/assets/users/index.html, cmd/server/main.go, pkg/controller/user/index.go, pkg/database/realm.go
* Allow for filtering the Users page by email address
=> User search by email

cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/cleanup/main.go, cmd/modeler/main.go, cmd/server/main.go
=> Rename config->cfg for all servers.

cmd/server/assets/realm.html, cmd/server/assets/realmadmin/_form_codes.html, cmd/server/assets/realmkeys.html
=> Br consistency

cmd/server/assets/realmadmin/edit.html, pkg/controller/realmadmin/settings.go
=> Handle disabled forms being zero

terraform/alerting/notifications.tf, terraform/alerting/probers.tf, terraform/alerting/workspace.tf
```release-note
NONE
```
/assign @yegle
=> Fix alerting project IDs

cmd/server/assets/login/_loginscripts.html
* We currently exit early and only show the first thing wrong with password validation.
* Show them all
* Show password / retyped password match validation
```release-note
Password complexity validation UI shows all validation stats (not just first failure)
```
=> Show all password validations

cmd/server/assets/admin/realms/index.html
```release-note
Display realm ID in admin view
```
=> Display realm ID

terraform/alerting/monitoring.tf
* Fixes alert that was firing to be more correct.
```release-note
NONE
```
=> Make alert better

pkg/controller/realmadmin/express.go
* remove dot that aligns next to and becomes part of link
```release-note
NONE
```
=> remove dot that impacts link

terraform/alerting/monitoring.tf
* Improve wording of alert text
* Change to 99%tile
* Limit to just Verification GCLB (ie not the redirect server)
* Exclude requests that GCLB ignored, ie didn't have a backend.
```release-note
NONE
```
=> Make latency alert a little more specific

cmd/server/assets/login/register-phone.html, pkg/controller/login/register.go, pkg/controller/login/session.go
* Hide/unhide the skip text for required/optional MFA realms
* Shows "continue" for required realms once enrolled
* Redirect to home if enrollment was from prompt rather than user navigation
```release-note
Automatically redirect home after MFA enrollment
```
=> Redirect to home if MFA registration from prompt

terraform/alerting/monitoring.tf
* For realm capacity alert, take max across all binaries per realm, instead of per realm and per binary.
```release-note
NONE
```
=> Make fixes to realm capacity alerts

cmd/server/assets/login/login.html
* Similar to password reset, let's leave the signin error vague and non-specific.
=> Don't alert the user to the full signin error

scripts/terraform.sh
Single word fix
/cc @sethvargo
=> Terraform smoke test: fix a typo

cmd/server/assets/login/register-phone.html
* Followup to https://github.com/google/exposure-notifications-verification-server/pull/695
* Also sets session as factors are removed. This will disallow the user to navigate on an MFA-required realm after their last factor is removed.
=> Update session as MFA factors are removed

cmd/server/assets/admin/sms/show.html, cmd/server/assets/realmadmin/_form_sms.html
```release-note
Add note about toll free and short codes to UI
```
=> Add note about toll free and short codes to UI

pkg/database/database.go, terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_cleanup.tf, terraform/service_e2e_runner.tf, terraform/service_modeler.tf, terraform/service_redirect.tf, terraform/service_server.tf
```release-note
Explicitly depend on database migrations and IAM during deployment
```
/assign @chaodaiG @icco
=> Explicitly depend on database migrations and IAM during deployment

pkg/controller/middleware/realm.go
* This time math wrong. This fixes it.
=> Fix some bad time math

terraform/main.tf
Fixes GH-1046
```release-note
NONE
```
=> Add service networking dependency for VPC connector

cmd/server/assets/login/change-password.html, cmd/server/assets/login/register-phone.html, pkg/controller/session.go
* This was cut/paste from select-password, but change-password should occur after login.
* Switch the link to account-settings.
=> Fix change-password back link

pkg/controller/cleanup/cleanup.go
=> Fix cleanup nil pointer dereference.

cmd/server/assets/login/register-phone.html, pkg/controller/login/register.go, pkg/controller/middleware/mfa.go, pkg/database/realm.go
* Ensures that the 'skip' option is shown for MFARequired realms if the user is within the grace-period.
=> Show skip link properly with grace period

pkg/controller/admin/realms.go, pkg/controller/codestatus/logic.go, pkg/controller/issueapi/issue.go, pkg/controller/login/change_password.go, pkg/controller/login/select.go, pkg/controller/middleware/auth.go, pkg/controller/middleware/emailverified.go, pkg/controller/middleware/realm.go, pkg/ratelimit/limitware/middleware.go
* Nit: we're calling the user from context `currentUser`
* Let's do this all at once so I don't forget this in other PRs and copy/paste propagate it
=> Nit: switch user -> currentUser

cmd/server/assets/mobileapps/_app.html, cmd/server/assets/mobileapps/show.html, pkg/controller/mobileapps/create.go, pkg/controller/mobileapps/update.go, pkg/database/migrations.go, pkg/database/mobile_app.go, tools/seed/main.go
* Add appstore links to the mobile apps, stored in the DB.
```release-note
Update the Mobile Apps to store links to their appstore.
```
=> Add appstore url to mobile apps.

cmd/server/assets/login/login.html, cmd/server/assets/users/import.html
* Add a note about quota to import
* Log errors on login to the console
=> Minor tweaks

pkg/controller/certapi/certapi.go, pkg/controller/certapi/certificate.go, pkg/controller/certapi/metrics.go, pkg/controller/cleanup/cleanup.go, pkg/controller/cleanup/metrics.go, pkg/controller/issueapi/issue.go, pkg/controller/issueapi/issueapi.go, pkg/controller/issueapi/metrics.go, pkg/controller/verifyapi/metrics.go, pkg/controller/verifyapi/verify.go, pkg/controller/verifyapi/verifyapi.go, pkg/database/database.go, pkg/database/metrics.go
This PR utilizes https://github.com/google/exposure-notifications-server/commit/7e6d29562b2ad52305104eb438baa47db6216c8e and simplified the view registration logic.
=> Refactor the view registration code in verification server.

.github/workflows/lock.yml
=> Lock merged PRs and closed issues after a day

cmd/server/assets/login/verify-email-check.html, cmd/server/main.go, internal/firebase/verify_password_reset_code.go, pkg/controller/login/verify_email.go
* Now that we've switched to a custom password-verify page, the firebase one is gone. It's all-or-nothing with the custom email links, so we need a custom email-verify too.
```release-note
Custom email verify page
```
=> Custom email verify page

terraform/alerting/monitoring.tf
* Small typo from https://github.com/google/exposure-notifications-verification-server/pull/759
```release-note
NONE
```
=> Forgot project field for requests_by_host metric

OWNERS
So that chaodaig can approve test related changes
=> Add chaodaig as approver

pkg/controller/redirect/index.go, pkg/controller/redirect/index_test.go
=> Fix bad ens:// protocol (E_MISSING_ONE_SLASH)

docs/development.md, pkg/config/server_config.go, terraform/README.md
This is no longer strictly required.
```release-note
NONE
```
=> Don't require Firebase TOS and PP

pkg/controller/associated/android.go, pkg/controller/associated/ios.go
* wrap errors
```release-note
NONE
```
=> wrap errors

pkg/database/migrations.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/232
* Add indexes to the verification code table for
* List of recent codes
* Lookup by uuid
=> Recent codes index

pkg/controller/issueapi/issue.go, pkg/controller/issueapi/metrics.go, pkg/controller/verifyapi/metrics.go, pkg/controller/verifyapi/verify.go
Similar to https://github.com/google/exposure-notifications-verification-server/pull/775
Part of https://github.com/google/exposure-notifications-verification-server/issues/773
=> Add /request metric.

pkg/controller/issueapi/issue.go, pkg/controller/issueapi/metrics.go, pkg/observability/observability.go
This is to replace /api/issue/sms_sent and /api/issue/sms_send_error metrics.
=> Add /api/issue/sms_request metric.

README.md, cmd/server/assets/firebase.html
* Update firebase js to the latest version
* Remove refs to firebaseUI
* Update docs to ref IdentityPlatform
=> Update firebase version, remove UI stuff

pkg/controller/certapi/certapi.go
We already increse the counter outside of this function.
- https://github.com/google/exposure-notifications-verification-server/blob/f2e04d8eb1abff6da33c77c1952d5931d7591201/pkg/controller/certapi/certificate.go#L91-L98
- https://github.com/google/exposure-notifications-verification-server/blob/f2e04d8eb1abff6da33c77c1952d5931d7591201/pkg/controller/certapi/certificate.go#L173-L181
=> Remove unnecessary metric increment in validateToken()

cmd/e2e-runner/main.go
* I was paged for a nil pointer here.
* Is there additional action we should take in this scenario?
=> Fixing a nil pointer in e2e

cmd/server/assets/email/_plainheader.html, pkg/controller/user/index.go
* Ensure the next/previous button don't show up for unexpected offsets
* Remove whitespace from the email
=> double checking things

go.mod, go.sum
=> Update key server dep

pkg/controller/issueapi/issue.go, pkg/controller/issueapi/metrics.go
The metric is already recorded as part of /requests_count metric.
Part of #773
=> Remove quota related metrics.

tools/seed/main.go
Fixes #820
```release-note
Fix failures during database seeding (local development)
```
=> Fix seed script (URL is required)

Makefile, docs/images/architecture/main.go, pkg/controller/healthz.go, pkg/controller/realmadmin/show_test.go, pkg/database/countries.go, pkg/observability/observability.go, pkg/ratelimit/limitware/middleware.go, pkg/sms/twilio_test.go, scripts/presubmit.sh
=> Add missing copyrights to files, and add a presubmit check.

pkg/database/mobile_app.go, pkg/database/mobile_app_test.go
Fixes #842
* App store URL should be optional.
```release-note
NONE
```
=> make url optional

pkg/database/mobile_app.go
Allow App URL to be blank on entry (rather than ignore blank).
=> Allow blank entry for URL.

cmd/server/assets/admin/_nav.html, cmd/server/assets/admin/email/show.html, cmd/server/main.go, pkg/controller/admin/email.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/787
* Add a system-level setting for email to system admin 
```release-note
System level email setting
```
=> System email settings

pkg/controller/redirect/index.go
* change log message so as not to alarm operators
```release-note
NONE
```
=> change log message when redirect doesn't redirect

terraform/database.tf
=> Retention policy and versioning are mutually exclusive

pkg/database/database.go
This has been annoying for awhile, because it makes failed tests very difficult to parse. This suppresses the log messages for callback registration unless debug mode is on.
```release-note
NONE
```
=> Don't output callback registration logs outside of debug mode

cmd/server/assets/realmadmin/show.html, internal/routes/server.go, pkg/controller/realmadmin/show.go, pkg/controller/realmadmin/stats.go, pkg/database/realm.go, pkg/database/realm_test.go
LMK what you think, happy to continue iterating.
- Add a pie chart when a column is selected
- Change cursor to pointer in table rows (to show the user something
can happen when clicking).
- Sort rows in reverse order
Updates #871
=> Revamp the realm stats

docs/api.md
* Document `testDate` in the verify response
```release-note
Updated API documentation to reflect new fields in verify response.
```
=> update api docs w/ new fields

pkg/clients/e2e.go, pkg/clients/metrics.go, pkg/observability/observability.go, terraform-e2e/state.tf
=> Record metrics in e2e runner.

cmd/server/assets/admin/email/show.html
```release-note
Make it possible to save system email configs
```
=> Make it possible to save system email configs

cmd/server/assets/email/_plainheader.txt
* Remove this content-transfer-type heading
=> remove content transfer type

pkg/controller/admin/users.go, pkg/controller/email.go
* .FromEmail should be sent to the template as a string rather than a func
=> fix email from string

pkg/controller/email.go, pkg/database/realm.go
* Add validation to realm-email-templates before save
* Populate emails from these instead of default
Note: There is no UI to  set  these yet. That's coming next.
=> Validate and populate realm email templates

pkg/database/realm.go
* Record changes to UseSystemEmail and templates to auditing
=> Include email templates / useSystem in auditing

cmd/server/assets/codestatus/index.html
```release-note
Clarify that recently issued codes are _your_ recently issued codes.
```
=> Recently issued codes are YOURs

OWNERS
* Last day at Google is tomorrow.
```release-note
NONE
```
=> Remove myself from owners

pkg/config/admin_server_config.go, pkg/config/server_config.go
* after further discussion w/ clinical team, we decided to extend this to 28 days.
```release-note
NONE
```
=> extend default symptom range to 28, from 27 days

go.mod, go.sum
=> Bump key server to v0.15.0

terraform/main.tf
```release-note
Enable BinaryAuth and Container Analysis APIs
```
=> Enable BinaryAuth and Container Analysis APIs

terraform/alerting/verification-server/scripts/upsert_alert_policy.sh
```release-note
Update to use new alpha flag
```
=> Update to use new alpha flag

pkg/database/realm.go
* fix bug where issuer would be assigned to audience
```release-note
BUG FIX - Issuer and Audience fields could be mixed up. Was introduced in v0.15.0
```
=> fix field mismatch typo

pkg/controller/home/home_test.go
=> Exchange the code for a token

internal/project/trim.go, internal/project/trim_test.go, pkg/controller/admin/users.go, pkg/controller/login/select_password.go, pkg/controller/user/create.go, pkg/controller/user/update.go, pkg/database/authorized_app.go, pkg/database/database.go, pkg/database/mobile_app.go, pkg/database/realm.go, pkg/database/user.go, pkg/database/vercode.go, pkg/render/render.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/933
* trim unicode zero-width no-break space everywhere
* add an option to trim space and non-printable
* Followup to @mikehelmick  https://github.com/google/exposure-notifications-verification-server/pull/931
=> Use super-trim all over

cmd/server/assets/shared/_pagination.html, internal/browser/executor.go, pkg/controller/middleware/currentpath.go, pkg/controller/middleware/template.go, pkg/database/pagination.go, pkg/pagination/pagination.go
```release-note
Add pagination helpers
```
=> Add generic pagination functionality

cmd/server/assets/apikeys/edit.html, cmd/server/assets/apikeys/index.html, cmd/server/assets/apikeys/new.html, cmd/server/assets/apikeys/show.html, cmd/server/assets/static/css/application.css, internal/envstest/server.go, pkg/controller/apikey/create.go, pkg/controller/apikey/create_test.go, pkg/controller/apikey/index.go, pkg/controller/apikey/show.go, pkg/controller/apikey/update.go, pkg/database/realm.go
```release-note
Improved UI and added pagination for API keys
```
=> Paginate API keys

scripts/ci-terraform.sh
```release-note
NONE
```
/assign @chaodaiG
=> Disable colored output for Terraform in CI

terraform/alerting/main.tf, terraform/alerting/variables.tf, terraform/alerting/verification-server/alerts.tf, terraform/alerting/verification-server/monitoring.tf, terraform/alerting/verification-server/variables.tf
Move its definition to alerts.tf. Conditionally enable this alert when
load balancer is used.
Part of #810
=> Define "Elevated latency" error using MQL.

terraform/alerting/verification-server/monitoring.tf
The incorrect one was deleted in
https://github.com/google/exposure-notifications-verification-server/pull/957
=> Fix the alerts

cmd/server/assets/apikeys/index.html, cmd/server/assets/mobileapps/index.html, cmd/server/assets/users/edit.html, cmd/server/assets/users/import.html, cmd/server/assets/users/index.html, cmd/server/assets/users/new.html, cmd/server/assets/users/show.html, internal/routes/server.go, pkg/controller/user/search.go, pkg/database/realm.go, pkg/pagination/pagination.go
```release-note
Update user list UI and UX
```
=> Use pagination for users and user search

cmd/server/assets/users/_form.html, cmd/server/assets/users/index.html, pkg/controller/user/search_test.go
=> Add a test

pkg/database/database.go, pkg/database/database_util.go
=> Fail the test if closing the connection fails

cmd/server/assets/admin/mobileapps/show.html, cmd/server/assets/admin/realms/edit.html
Issue https://github.com/google/exposure-notifications-verification-server/issues/910
* Link from realms system admin page to mobile-apps by realm
* Consistency on the apps icon/name
=> mobile apps link

cmd/server/assets/admin/mobileapps/show.html, cmd/server/assets/users/index.html, pkg/controller/admin/mobile_apps.go, pkg/database/mobile_app.go, pkg/database/realm.go
Issue https://github.com/google/exposure-notifications-verification-server/issues/910
* Allows search by realm name or by mobile app name
```release-note
Search for system-admin mobile apps
```
=> Search bar for mobile apps

cmd/server/assets/email/_plainheader.txt, pkg/controller/admin/superusers.go, pkg/controller/user/create.go, pkg/controller/user/update.go, pkg/database/mobile_app.go, pkg/database/realm.go, pkg/database/user.go, pkg/render/render.go
* Trims occur in BeforeSave for the user email/name
* Trim in the email template
* Trim in FindByEmail
* Trim search queries
* No more trim in the controller layer
=> Move string trims out of controller

pkg/controller/admin/users.go, pkg/database/user.go
* Audi the call to delete user
=> Audit delete user

pkg/database/user.go
* We missed a spot renaming admin to system_admin
=> Fix system admin query

cmd/server/assets/admin/realms/edit.html
Issue https://github.com/google/exposure-notifications-verification-server/issues/991
* Include more details about realm in the system admin page
=> Update system-admin realm details page

pkg/cache/redis_test.go, scripts/presubmit.sh
=> Authenticate to private Docker on CI

cmd/server/assets/admin/realms/edit.html, cmd/server/assets/admin/users/show.html, internal/routes/server.go, pkg/controller/admin/realms.go
Fixes #1003
```release-note
Allow admins to add/remove users from other realms
```
=> Allow admins to add/remove users from other realms

terraform/alerting/verification-server/alerts.tf
/cc @yegle 
```release-note
NONE
```
=> Fix missing commas

terraform/alerting/verification-server/alerts.tf
=> Strictify the MQL queries that were broken.

cmd/server/assets/realmadmin/events.html, pkg/controller/realmadmin/events.go, pkg/database/realm.go
* Add pagination for audit log page - continuing the theme of paginating our lists
```release-note
Pagination for audit logs
```
=> Pagination for event/audit logs

cmd/server/assets/realmadmin/events.html, pkg/controller/realmadmin/events.go, pkg/database/realm.go, pkg/database/scopes.go
* Add a search for start/end time to sort through event logs
```release-note
Create time-based search for event entries
```
=> Search through events by time

cmd/server/assets/admin/events/index.html
```release-note
Fix system admin events search form
```
=> Fix system admin events search form

pkg/controller/middleware/realm.go
=> Fix misnamed log header

cmd/server/assets/admin/events/index.html, cmd/server/assets/admin/mobileapps/index.html, cmd/server/assets/admin/realms/index.html, cmd/server/assets/admin/users/index.html, cmd/server/assets/apikeys/index.html, cmd/server/assets/users/index.html
* Where we are allowing searches we have a magnifying-glass icon that looks like a button... make it clickable so it does what you might expect.
* Adds one for the system-admin users search
=> Make the magnifying-glass search icon clickable everywhere

cmd/server/assets/admin/events/index.html, cmd/server/assets/admin/mobileapps/index.html, cmd/server/assets/admin/realms/index.html, cmd/server/assets/admin/users/index.html, cmd/server/assets/apikeys/index.html, cmd/server/assets/realmadmin/events.html, cmd/server/assets/users/index.html
Kinda reverts #1039
Closes #1038
```release-note
NONE
```
=> Unify search icons and UX

docs/api.md
=> Clarify chaff response parsing

cmd/server/assets/mobileapps/index.html, pkg/controller/mobileapps/index.go, pkg/database/realm.go, pkg/database/scopes.go
```release-note
Add search for mobile apps
```
=> Search mobile apps

internal/routes/server.go
```release-note
Fix user_id constraint
```
=> Fix user_id constraint

.github/workflows/codeql-analysis.yml
=> Run codeql on javascript too

internal/routes/server.go, internal/routes/server_test.go
Part of https://github.com/google/exposure-notifications-verification-server/issues/1026
```release-note
NONE
```
=> Add tests for system admin routes

cmd/server/assets/mobileapps/show.html
```release-note
Add noreferrer to external links
```
=> Add noreferrer to external links

internal/routes/server.go, internal/routes/server_test.go, pkg/controller/jwks/jwks.go
Part of https://github.com/google/exposure-notifications-verification-server/issues/1026
```release-note
Add more routing tests
```
=> Add more routing tests

cmd/server/assets/admin/caches/index.html, cmd/server/assets/admin/email/show.html, cmd/server/assets/admin/events/index.html, cmd/server/assets/admin/info.html, cmd/server/assets/admin/mobileapps/index.html, cmd/server/assets/admin/realms/index.html, cmd/server/assets/admin/sms/show.html, cmd/server/assets/admin/users/index.html, pkg/controller/admin/caches_test.go, pkg/controller/admin/email_test.go, pkg/controller/admin/events_test.go, pkg/controller/admin/mobile_apps_test.go, pkg/controller/admin/realms_test.go, pkg/controller/admin/sms_test.go, pkg/controller/admin/users_test.go, pkg/controller/apikey/create_test.go, pkg/controller/mobileapps/create_test.go, pkg/controller/user/search_test.go, pkg/database/database_util.go
* Creates a basic clicky-test for each admin tab
* Currently just loads each tab and verifies the body loads without error
* Next PRs will fill out functionality exercises for each page
```release-note
Integration test coverage for system-admin UI
```
=> Create a clicky test for each admin tab

cmd/server/assets/users/import.html, pkg/controller/user/import.go
* Remove extra variables from the user import page - they are unused
=> Nit: remove extra vars from import page

go.mod, go.sum, pkg/database/database.go
=> Let the observability package to register the sql related views.

cmd/server/assets/admin/_nav.html, cmd/server/assets/admin/mobileapps/index.html, cmd/server/assets/admin/realms/edit.html, cmd/server/assets/apikeys/edit.html, cmd/server/assets/apikeys/index.html, cmd/server/assets/apikeys/new.html, cmd/server/assets/apikeys/show.html, cmd/server/assets/header.html, cmd/server/assets/mobileapps/edit.html, cmd/server/assets/mobileapps/index.html, cmd/server/assets/mobileapps/new.html, cmd/server/assets/mobileapps/show.html, internal/routes/server.go, internal/routes/server_test.go, pkg/controller/admin/mobile_apps_test.go, pkg/controller/apikey/create.go, pkg/controller/apikey/create_test.go, pkg/controller/apikey/disable.go, pkg/controller/apikey/enable.go, pkg/controller/apikey/update.go, pkg/controller/mobileapps/create.go, pkg/controller/mobileapps/create_test.go, pkg/controller/mobileapps/disable.go, pkg/controller/mobileapps/enable.go, pkg/controller/mobileapps/update.go, pkg/controller/user/search_test.go
Issue https://github.com/google/exposure-notifications-verification-server/issues/1026
* Makes systemadmin "mobile-apps" instead of "mobileapps" to be consistent with realm
* Move realm-filtered paths to /realm
=> Update routing paths for apikeys and mobileapps

cmd/server/assets/admin/users/index.html, cmd/server/assets/admin/users/new.html, internal/auth/local.go, pkg/controller/admin/users_operations.go, pkg/controller/admin/users_test.go
1. Navigate to `New System Admin` page
2. Create an admin user
3. Submit and land on `Index` page
4. Search for newly created user by email
5. Assert row shown
4. Search for newly created user by name with a filter
5. Assert row shown
6. Search for non-existing user
7. Assert no rows shown
```release-note
Integration test assertions for new system admin
```
=> Fill out assertions for Users search test

cmd/server/assets/admin/mobileapps/index.html, pkg/controller/admin/mobile_apps_test.go
* Creates a mobile app in the DB
* Asserts search can find it by name
* Asserts search for notexisting gets no results
=> Assert system-admin mobile apps search

cmd/server/assets/admin/realms/edit.html, cmd/server/assets/admin/realms/index.html, cmd/server/assets/admin/realms/new.html, pkg/controller/admin/realms_test.go, pkg/controller/admin/users_test.go
* Creates a new realm with all of the fields set
* Searches for the realm and clicks to edit it
* Leave the realm and assert the join button appears
```release-note
Integration test for system-admin realms
```
=> Test system-admin realm create, search, and leave

cmd/server/assets/admin/sms/show.html, pkg/controller/admin/sms_test.go
* Sets fields of the system SMS config
* Asserts DB entry set
```release-note
System SMS settings integration test
```
=> Test system SMS config

cmd/server/assets/admin/email/show.html, pkg/controller/admin/email_test.go
* Fill out the system email settings form and save
* Assert the DB entry exists and matches
```release-note
Integration test for system-admin email setting
```
=> Test system email settings

cmd/server/assets/admin/_nav.html, cmd/server/assets/header.html, cmd/server/assets/home.html, cmd/server/assets/login/register-phone.html, cmd/server/assets/login/verify-email.html, internal/routes/server.go, pkg/controller/home/home_test.go, pkg/controller/login/change_password.go, pkg/controller/login/login.go, pkg/controller/login/select.go, pkg/controller/user/delete.go
Issue https://github.com/google/exposure-notifications-verification-server/issues/1026
Issue https://github.com/google/exposure-notifications-verification-server/issues/1090
* Duplicate /home route to /code/issue
* Place in same subrouter as /code/status
/home will go away in a future release
=> Update code issue path

pkg/controller/issueapi/issue.go
Should be no-op other than reorganizing the lines.
=> Organize the code to avoid the lint warning.

scripts/ci-terraform.sh
serverless-vpc-connector had been into bad state quite a few times after deleted by terraform, terraform remove it from state with the existence of a broken vpc connector, which prevents future terraform apply due to serverless vpc connector already exist. Forcing delete to avoid manual intervention
Copy/pasted from https://github.com/google/exposure-notifications-server/pull/1169
=> Delete serverless vpc connector ahead of time

cmd/server/assets/codes/bulk-issue.html
Fixes #1106
```release-note
NONE
```
=> Pretty bulk-upload form

cmd/server/assets/codes/bulk-issue.html
* Fix issue with the total count
* Fix the flashing progress bar
* The results table is still a little ugly and possibly confusing - I intend to keep improving error handling etc
=> More bulk upload js

cmd/server/assets/users/show.html
* These dates show up backwards - reverse the data array to match what we do with realm stats
=> Reverse dates for user stats

cmd/server/assets/apikeys/show.html
* These charts come in DESC but we need them reversed to draw the chart left to right
=> Reverse apikeys charts

cmd/server/assets/apikeys/show.html, cmd/server/assets/codes/bulk-issue.html, cmd/server/assets/codes/issue.html, cmd/server/assets/login/register-phone.html, cmd/server/assets/login/verify-email-check.html, cmd/server/assets/realmadmin/show.html, cmd/server/assets/static/js/application.js, cmd/server/assets/users/import.html
* Should be functionally identical, but scopes down function-level js
=> Switch var to let for function-scoped javascript

docs/playbooks/alerts/SlowErrorBudgetBurn.md, docs/playbooks/index.md, terraform/alerting/alerts.tf
Fixes #
* added slow burn (5% of error budget in 6 hours) alert
* added slow burn alert playbook
* modified index
```release-note
Added slow error budget burn (5% consumed in 6 hours) alert.
```
=> Slow burn alert

cmd/server/assets/codes/issue.html, cmd/server/assets/header.html, internal/i18n/locales/en/default.po, internal/i18n/locales/es/default.po
=> Add more i18n examples

cmd/server/assets/login/_loginscripts.html, cmd/server/assets/login/login.html
* Load recaptcha in jquery
* Use the recaptcha callback submit to ensure captcha solved on login
* Reset recaptcha on unhandled failures
* Fixes an 'error' misnamed 'err'
* Capitalization of SMS pin heading
=> More resilient recaptcha

cmd/server/assets/login/register-phone.html, internal/routes/server.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1131
* Guard places where we display realm in SMS registration and show system defaults
=> Don't require realm for sms registration

cmd/server/assets/admin/events/index.html, cmd/server/assets/realmadmin/events.html
```release-note
Truncate long event entries in UI
```
=> Truncate long event entries

docs/playbooks/alerts/ElevatedLatencyGreaterThan2s.md
This was mentioned during the table top exercise.
=> Add additional queries to understand the latency

cmd/server/assets/codes/bulk-issue.html
=> helper function for retries

cmd/server/assets/login/register-phone.html, pkg/controller/login/select.go, pkg/controller/middleware/mfa.go
* Fires the recaptcha on form submit
* This makes the 2 minute timeout less likely to expire if you load the page and sit there
* Already did this for the login page
* Reset the captcha on failure / cancel
* Reset the captcha on successful enrollment
* Gives a new captcha token if you're enrolling more than one phone
* Store MFA prompted when we decide it's not needed for the realm
* Clear MFA prompted on realm select (if its a different realm)
=> Update register phone catcha

cmd/server/assets/codes/bulk-issue.html, cmd/server/assets/static/js/application.js, cmd/server/assets/users/import.html
* Adds retry logic to user-import and moves the js to application.js
=> Share js retry logic

internal/i18n/locales/es/default.po
=> Spanish feedback

cmd/server/assets/header.html, cmd/server/assets/static/js/application.js
* Check the error enum codes too
* Append the server build string to our `application.js?{{.buildID}}` to cause clients to not use outdated cached versions.
=> Have the bulk uploader pay attention to our enum values, version js

.github/ISSUE_TEMPLATE/feature.md
=> Fix feature tag

pkg/database/database.go
```release-note
Set timeouts on rawSQL before gorm
```
/assign @jeremyfaller
=> Set timeouts on rawSQL before gorm

cmd/server/assets/static/js/application.js
```release-note
Do not trust responses from the server to contain HTML
```
=> Do not trust responses from the server to contain HTML

cmd/server/assets/admin/email/show.html, cmd/server/assets/admin/sms/show.html, cmd/server/assets/realmadmin/_form_email.html, cmd/server/assets/realmadmin/_form_sms.html, internal/project/root.go, pkg/controller/admin/email.go, pkg/controller/admin/sms.go, pkg/controller/realmadmin/settings.go, pkg/controller/realmadmin/sms_test.go, pkg/controller/realmadmin/smtp_test.go, pkg/render/render.go
* Don't give back passwords
* @sethvargo  did this for realm in https://github.com/google/exposure-notifications-verification-server/pull/1163
=> Password sentinel for system admin too

terraform/alerting/alerts.tf, terraform/alerting/notifications.tf, terraform/alerting/variables.tf
The previous naive approach doesn't work.
=> Fix the alert notification channels

pkg/database/migrations.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1158
* Maybe it's failing partway through?
=> Check existence on rollback

terraform/main.tf
```release-note
Add REGION to .env
```
=> Add REGION to .env

cmd/app-sync/main.go, pkg/config/appsync_server_config.go, pkg/controller/appsync/appsync.go
Issue https://github.com/google/exposure-notifications-verification-server/issues/1092
* Scaffolding for a new service endpoint "appsync"
* Config with default value for the endpoint
* Do-nothing Handle() that errors
=> Scaffolding for app sync endpoint

.github/workflows/codereview.yaml, Makefile, pkg/controller/admin/caches.go, pkg/controller/admin/realms.go, pkg/controller/admin/users_operations.go, pkg/controller/certapi/certificate.go, pkg/controller/codes/expire.go, pkg/controller/codes/index.go, pkg/controller/codes/show.go, pkg/controller/controller.go, pkg/controller/issueapi/issue.go, pkg/controller/middleware/csrf.go, pkg/controller/middleware/firewall.go, pkg/controller/middleware/realm.go, pkg/controller/realmadmin/show.go, pkg/controller/user/reset_password.go, pkg/controller/verifyapi/verify.go
=> Add linter for missing return after controller funcs

cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/app-sync/main.go, cmd/cleanup/main.go, cmd/e2e-runner/main.go, cmd/enx-redirect/main.go, cmd/modeler/main.go, cmd/server/assets/codes/bulk-issue.html, cmd/server/main.go, docs/api.md
* Looks like users of this scenario are currently using issueAPI with testDate only. This prompts the user at the app for their symptom date.
* Bulk uploader should use testDate.
* Optional 3rd row of csv for symptomDate
* BUILD BREAK FIX. Add exporter ctx pulled in from key-server 0.17.0 dep
=> Switch symptomDate to testDate for bulk uploader

cmd/server/assets/codes/bulk-issue.html, cmd/server/assets/codes/issue.html, cmd/server/assets/static/js/application.js
* Adds a random encoded string to the "padding" field
* This conforms to the API guidance to vary request sizes which can help obfuscate attempts to sniff traffic.
```release-note
Add random padding to requests in bulk-uploader
```
=> Add random padding to issue requests

.github/workflows/codeql-analysis.yml, .github/workflows/lock.yml, .github/workflows/stale.yml
=> Turn up CodeQL frequency and down lock/stale

pkg/controller/associated/android.go, pkg/controller/associated/ios.go, pkg/controller/redirect/appstore.go, pkg/controller/user/export.go, pkg/database/mobile_app.go, pkg/database/mobile_app_test.go, pkg/database/scopes.go
* Change ListActiveAppsByOS to ListActiveApps that takes a list of scopes
* Pass in a ByOS scope
Note: This is simple, but will lead others to use more scopes if we need other variations of this.
=> Use scopes for list mobile apps by OS

pkg/controller/healthz.go
=> Also handle no query param in healthz

terraform/alerting/probers.tf, terraform/redirect-lb.tf, terraform/verification-lb.tf
These only become obvious on fresh project creation, which we haven't done in a long while.
```release-note
Add some missing dependencies to Terraform setup
```
=> Add some missing dependencies to Terraform setup

pkg/controller/issueapi/issue.go
* Adding observability tags for client-provided UUID errors
=> Add observability results for client UUID

docs/playbooks/alerts/HostDown.md
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1202
=> Add playbook for HostDown alert.

cmd/server/assets/admin/realms/edit.html, pkg/controller/admin/realms.go
```release-note
Add UI to share system SMS config
```
=> Add UI to share system SMS config

builders/build.yaml, builders/deploy.yaml, builders/promote.yaml
```release-note
Build and deploy app-sync
```
=> Build and deploy app-sync

terraform/service_appsync.tf
=> Use correct container name

pkg/controller/user/importbatch.go
* I believe these all will point to the address of `var batchUser` which is not the intent.
* This data isn't really used on receipt which is why this went uncaught.
* TODO: factor logic out and unit test. Coming soon.
=> point back to the new user

scripts/ci-terraform.sh, terraform-e2e-ci/main.tf
/hold
The test hasn't pass yet
=> Smoke test: also test deploy alerting module with terraform

README.md, docs/link_handling.md
* add docs for deep link handling
```release-note
DOCS: Added documentation for EN Express link handling for custom apps.
```
=> add deep link handling instructions

cmd/server/assets/realmadmin/show.html
```release-note
Print a message when loading returns with no stats
```
=> Print a message when loading returns with no stats

docs/case-worker-guide.md, docs/realm-admin-guide.md, docs/system-admin-guide.md
=> Add table of contents to markdown guides

docs/api.md
* add new field to sample API call
```release-note
NONE
```
=> add externalIssuerID to issue sample

pkg/controller/issueapi/handle_issue_batch.go
* Improving an error string to show the violated limit
=> Nit: Show batch limit in error message

cmd/server/assets/realmadmin/show.html
```release-note
Add more detailed stats help information
```
=> Add more detailed stats help information

internal/routes/server_test.go
* This is minor, but since /codes/{uuid} matches any string, I want all of the routes covered in test so nobody comes in later and messes up the order.
=> Test nit: Include issue and bulk-issue route

docs/api.md
* Add documentation for the batch-issue API
* Add a TOC to the API doc
```release-note
Documentation for batch-issue API
```
=> Document batch-issue API

cmd/server/assets/apikeys/show.html, internal/routes/server.go, internal/routes/server_test.go, pkg/controller/apikey/apikey.go, pkg/controller/apikey/disable.go, pkg/controller/apikey/enable.go, pkg/controller/apikey/stats.go, pkg/database/authorized_app.go, pkg/database/authorized_app_stats.go, pkg/database/migrations.go, pkg/database/user.go, pkg/database/user_stats.go, pkg/database/vercode_test.go
```release-note
Provide JSON and CSV output for API key stats
```
=> Update API key stats too (CSV and JSON)

internal/i18n/locales/tr/default.po
Some strings such as
msgid "codes.issue.countdown-expires-in"
could use %s formatting to ensure value can be appropriately placed in the
translated string.
If there's a Turkish person working on the project, peer reviews are
appreciated.
=> Turkish (tr) translation

docs/realm-admin-guide.md
=> Correct link in docs

docs/playbooks/dos.md, terraform/dos.tf, terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_modeler.tf, terraform/service_redirect.tf, terraform/service_server.tf
Enabled predefined rules:
- XSS
- Remote Code Execution
- SQL Injection
All of them are in preview mode so no actual traffic will be blocked.
Also added instruction on how to use them, as well as example configs for common use cases.
=> Initial config for Cloud Armor

docs/api.md
Fixes #https://github.com/google/exposure-notifications-verification-server/issues/1301
* Flipped request with response in the batch API doc
=> flipped response/request

cmd/server/assets/mobileapps/_app.html, docs/link_handling.md, pkg/controller/associated/ios.go, pkg/database/mobile_app.go
Issue  https://github.com/google/exposure-notifications-verification-server/issues/1299
* Include the empty "apps": [] in our [Universal Links](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html) for IOS
```release-note
Fixes to iOS Universal Links formatting
```
=> Update to iOS mobile apps format

terraform/alerting/alerts.tf
=> Fix the threshold of the stackdriver export failure alert.

internal/i18n/locales/de/default.po
* Adding i18n translation for German[de]
=> Adding translation for German[de]

docs/api.md
=> Document SMS client errors

cmd/server/assets/static/js/application.js
Issue https://github.com/google/exposure-notifications-verification-server/issues/1305
* What we've got works on localhost:8080 (for me) but gets a connection issue elsewhere.
* Trying to tweak the way the reset works
=> Try different recatcha reset

OWNERS
* Jeremy is back at his day-job. This'll stop prow from auto-assigning.
=> remove jeremyfaller from owners

pkg/controller/issueapi/issue_batch.go
* fix logging in batch issue
```release-note
Fix logging error in batch issue API.
```
=> use warnw correctly

pkg/controller/issueapi/logic.go, pkg/controller/issueapi/logic_test.go
* add `The 'To' number %s is not a valid phone number.` to scrub pattern
```release-note
Add another twilio error message to scrub pattern
```
=> add another scrubbing pattern

pkg/controller/associated/ios.go
* Paths should be serialized as 'paths'
```release-note
Fix json output for iOS universal links
```
=> Fix json output name

.github/workflows/terraform.yml, terraform-e2e-ci/main.tf, terraform/alerting/variables.tf, terraform/mirror/variables.tf, terraform/variables.tf
Lint and check formatting on all Terraform configs
```release-note
NONE
```
=> Add linters for Terraform

terraform/alerting/module.availability-slo/main.tf, terraform/alerting/module.availability-slo/variables.tf, terraform/alerting/module.latency-slo/main.tf, terraform/alerting/module.latency-slo/variables.tf, terraform/alerting/slos.tf
Add a knob to set latency SLO threshold.
=> Disable SLO alerts except for adminapi/apiserver/server.

cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/e2e-runner/main.go, cmd/server/main.go, internal/routes/adminapi.go, internal/routes/apiserver.go, internal/routes/enx_redirect.go, internal/routes/server.go, pkg/testsuite/integration.go
Fixes #1359
```release-note
Only generate Apache logs for local dev
```
/assign @yegle
=> Only create Apache logs for local dev

internal/i18n/locales/ph/default.po
```release-note
Add ph translations
```
=> Add ph translations

cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/enx-redirect/main.go, cmd/server/main.go, internal/routes/adminapi.go, internal/routes/apiserver.go, internal/routes/enx_redirect.go, internal/routes/server.go
We don't want these appearing in tests.
```release-note
NONE
```
=> Mount Apache logger in binary

cmd/server/assets/users/_form.html, pkg/controller/user/update_test.go, pkg/rbac/rbac.go, pkg/render/renderer_impl.go
```release-note
Document implied permissions, enforce via javascript
```
=> Document implied permissions, enforce via javascript

pkg/controller/controller.go, pkg/controller/issueapi/logic.go
```release-note
Make SMS message failures info level in logs
```
=> Make SMS message failures info level

pkg/controller/middleware/logger.go
```release-note
Extract trace context if present and add to logger
```
/assign @yegle
=> Extract trace context if present and add to logger

pkg/controller/redirect/index_test.go
=> Show bad path 404s

cmd/apiserver/main.go, internal/routes/apiserver.go
=> Don't close chaff on routes return

internal/routes/adminapi.go, internal/routes/server.go, pkg/controller/issueapi/controller.go, pkg/controller/issueapi/issue_batch_test.go, pkg/controller/issueapi/logic.go, pkg/integration/integration_test.go, pkg/testsuite/clients.go, pkg/testsuite/integration.go
* Integration test looks at partial success / failure responses
* These code paths are shared with single-issue, so should be adding coverage
```release-note
correct response for invalid_test_type previously returned unsupported_test_type even if unparsable.
added integration test coverage for code issue
```
=> Adding an test for bulk-issue error handling

pkg/controller/admin/events.go, pkg/controller/admin/mobile_apps.go, pkg/controller/admin/realms.go, pkg/controller/admin/users_list.go, pkg/controller/apikey/index.go, pkg/controller/controller.go, pkg/controller/mobileapps/index.go, pkg/controller/realmadmin/events.go, pkg/controller/user/index.go
```release-note
Make bad query params a 400-level user error
```
=> Make bad query params a user error

cmd/server/assets/apikeys/edit.html, cmd/server/assets/apikeys/new.html, cmd/server/assets/header.html, pkg/controller/apikey/stats.go, pkg/controller/apikey/stats_test.go, pkg/controller/apikey/update.go, pkg/database/authorized_app.go, pkg/database/errors.go
```release-note
Add tests for authorized app stats
```
=> Add tests for authorized app stats

cmd/server/assets/mobileapps/edit.html, cmd/server/assets/mobileapps/index.html, cmd/server/assets/mobileapps/new.html, cmd/server/assets/mobileapps/show.html, internal/envstest/unit.go, internal/routes/server.go, pkg/controller/apikey/disable_test.go, pkg/controller/apikey/index_test.go, pkg/controller/apikey/show_test.go, pkg/controller/apikey/update_test.go, pkg/controller/mobileapps/create.go, pkg/controller/mobileapps/create_test.go, pkg/controller/mobileapps/disable.go, pkg/controller/mobileapps/disable_test.go, pkg/controller/mobileapps/enable.go, pkg/controller/mobileapps/enable_test.go, pkg/controller/mobileapps/index_test.go, pkg/controller/mobileapps/mobileapps.go, pkg/controller/mobileapps/show.go, pkg/controller/mobileapps/show_test.go, pkg/controller/mobileapps/update.go, pkg/controller/mobileapps/update_test.go, pkg/database/mobile_app.go
```release-note
Add tests for mobileapps
```
=> Add tests for mobileapps

cmd/server/assets/404.html, internal/envstest/sql.go, pkg/controller/apikey/create.go, pkg/controller/apikey/create_test.go, pkg/controller/apikey/disable_test.go, pkg/controller/apikey/enable_test.go, pkg/controller/apikey/index_test.go, pkg/controller/apikey/show_test.go, pkg/controller/apikey/stats.go, pkg/controller/apikey/stats_test.go, pkg/controller/apikey/update.go, pkg/controller/apikey/update_test.go, pkg/database/authorized_app.go, pkg/database/database.go
```release-note
Add harness and tests for testing internal errors
```
=> Add harness and tests for testing internal errors

pkg/controller/login/reset_password.go, pkg/database/membership_test.go, pkg/database/user.go
* Unit tests
* Drop an unnecessary join
=> Add unit test for membership list/selectfirst

pkg/controller/middleware/firewall.go, pkg/controller/middleware/firewall_test.go
```release-note
Add tests for firewall
```
/cc @yegle 
=> Add tests for firewall

go.mod, go.sum
/assign @yegle
```release-note
NONE
```
=> Bump core server to pull in logger changes

pkg/controller/middleware/apikey.go, pkg/controller/middleware/apikey_test.go, pkg/controller/middleware/firewall_test.go, pkg/controller/middleware/middleware_test.go
```release-note
Add tests for apikey middleware
```
=> Add tests for apikey middleware

terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_appsync.tf, terraform/service_cleanup.tf, terraform/service_e2e_runner.tf, terraform/service_modeler.tf, terraform/service_redirect.tf, terraform/service_server.tf
The annotation will be used to do the ingress control (currently EAP).
Part of #895
=> Do not ignore annotation changes.

Makefile, go.mod, go.sum, pkg/controller/issueapi/issueapi_test.go, scripts/presubmit.sh, tools/tools.go
The tool only found 1 instance, but this is super fast to run on CI.
```release-note
Check for unclosed response bodies in CI
```
=> Check for unclosed response bodies

cmd/server/assets/codes/bulk-issue.html, cmd/server/assets/static/js/application.js
* Moves much of the javascript of bulk-issue to application.js
* Why: caches better in the client browser, separate js controller from html view, IDEs can figure it out too
=> Staticify bulk issue js

cmd/server/assets/realmadmin/_form_codes.html, pkg/api/api.go, pkg/database/migrations.go, pkg/database/sms_config_test.go
* I have two held PRs open where I came across these nits. Hoping to get these in at least so I don't forget them.
* Rollback for IssuerExternalId drops an entire table
* Some spelling mistakes
*  Test coverage for HasSMSConfig
=> Some nits from other PRs

cmd/server/assets/static/js/application.js
* It's annoying that this filename is always the same, append the current date.
=> Add in the current date to the bulk upload receipt csv filename

builders/migrate.yaml, cmd/adminapi/main.go, cmd/apiserver/main.go, cmd/appsync/main.go, cmd/cleanup/main.go, cmd/e2e-runner/main.go, cmd/enx-redirect/main.go, cmd/migrate/main.go, cmd/modeler/main.go, cmd/server/main.go, docs/development.md, go.mod, go.sum, scripts/migrate, terraform-e2e-ci/main.tf, terraform/database.tf, tools/e2e-test/main.go, tools/gen-keys/main.go, tools/gen-secret/main.go, tools/get-certificate/main.go, tools/get-code/main.go, tools/get-token/main.go, tools/seed/main.go
```release-note
Update logger package
```
=> Update logger package

docs/realm-admin-guide.md
* Add a leading `/`
* I accidentally pushed this directly to the main branch, tried to undo, but branch protection. Now this is a third commit and it looks like I can't git.  /shame
=> Fix a link

pkg/controller/middleware/debug_test.go
```release-note
Add tests for debug middleware
```
=> Add tests for debug middleware

pkg/controller/middleware/method_test.go
```release-note
Add tests for method middleware
```
=> Add tests for method middleware

internal/routes/apiserver.go, pkg/controller/middleware/chaff.go, pkg/controller/middleware/chaff_test.go, pkg/database/database.go
```release-note
Add tests for chaff middleware
```
=> Add tests for chaff middleware

internal/routes/server.go, pkg/controller/middleware/csrf.go, pkg/controller/middleware/csrf_test.go
```release-note
Add tests for csrf middleware
```
=> Add tests for csrf middleware

docs/case-worker-guide.md, pkg/database/realm.go, pkg/database/realm_test.go, pkg/database/user_test.go
* Adding some unit-test coverage for some common Realm operations (and removing a dead one)
=> Adding some realm test coverage

pkg/controller/middleware/header.go, pkg/controller/middleware/header_test.go
```release-note
Add tests for header middleware
```
=> Add tests for header middleware

pkg/controller/middleware/i18n.go, pkg/controller/middleware/i18n_test.go
```release-note
Add tests for i18n middleware
```
=> Add tests for i18n middleware

internal/routes/server.go, pkg/controller/middleware/membership.go, pkg/controller/middleware/membership_test.go
```release-note
Add tests for membership middleware
```
=> Add tests for membership middleware

pkg/controller/middleware/mfa.go, pkg/controller/middleware/mfa_test.go
```release-note
Add tests for MFA middleware
```
=> Add tests for MFA middleware

pkg/controller/middleware/request_id_test.go
```release-note
Add tests for request_id middleware
```
=> Add tests for request_id middleware

pkg/controller/middleware/template_test.go
```release-note
Add tests for template middleware
```
=> Add tests for template middleware

pkg/database/authorized_app_test.go, pkg/database/mobile_app_test.go, pkg/database/realm_test.go, pkg/database/user_test.go
* Covers some audits for MobileApp, AuthorizedApp, Realm, and User
* I'll keep going with some others, but this is very boring
=> Cover some audits unit tests

pkg/controller/middleware/sessions_test.go
```release-note
Add tests for sessions middleware
```
=> Add tests for sessions middleware

pkg/controller/user/stats.go, pkg/database/user.go
This is the first part of migrating the user stats from being rendered on the page to being served via javascript like the other stats pages.
```release-note
Move user stat caching into the model
```
=> Move user stat caching into the model

builders/build.yaml
=> Allow builds to take 20min

.github/workflows/codereview.yaml, Makefile, scripts/presubmit.sh
/hold
```release-note
NONE
```
=> Check copyright and date

go.mod, go.sum
* Updates the dep on exposure-notifications-server to v0.19.0
=> Update key server dep to 0.19.0

cmd/server/assets/codes/bulk-issue.html, internal/i18n/locales/de/default.po, internal/i18n/locales/en/default.po, internal/i18n/locales/es/default.po, internal/i18n/locales/fr/default.po, internal/i18n/locales/it/default.po, internal/i18n/locales/ja/default.po, internal/i18n/locales/ph/default.po, internal/i18n/locales/pt/default.po, internal/i18n/locales/tr/default.po
* Add translations for the bulk-issue codes page
*  I've left a bunch of languages in English for now. I intend to follow up with translation help, but our test require that string keys exist for all languages.
```release-note
I8n strings for bulk-issue
```
=> I18N for bulk-issue

cmd/server/assets/firebase.html
* Update Firebase dep from 7.22.1 to 8.2.1
* from the release notes:
*  "Fixed an issue with IndexedDB retry logic causing uncaught errors."
* "Updated auth token logic to rely on device clock time instead of server time. This fixes an issue seen when a device's clock is skewed by a lot"
=> Update firebase to the latest version

OWNERS
=> Remove Chao :(

pkg/database/migrations.go
/cc @bschlaman 
```release-note
Delete any orphaned entries before creating foreignkey. This handles an extreme edge case where an entry was manually deleted from the database before the FK constraint existed.
```
=> Delete any orphaned entries before creating foreignkey

pkg/controller/healthz.go
Fixes #1536
```release-note
Retry database pings in health checks
```
=> Retry database pings in health checks

terraform/alerting/monitoring.tf
Part of https://github.com/google/exposure-notifications-verification-server/issues/1389
```release-note
Create metrics for when humans access secrets or decrypt values
```
/assign @yegle
/assign @yuriatgoogle
=> Create metrics for when humans access secrets or decrypt values

pkg/controller/jwks/jwks.go, pkg/database/realm.go, pkg/database/realm_test.go
```release-note
Allow JWK lookup URLs to work with region codes in addition to IDs
```
=> Allow JWKs to work with region code as well

internal/project/util.go, internal/project/util_test.go, pkg/database/realm.go, pkg/database/sms_config.go
* Move AllDigits to its own function and share it
=> Share alldigits as a project util

cmd/server/assets/admin/_nav.html, cmd/server/assets/header.html, go.mod, go.sum, pkg/controller/codes/bulk_issue_test.go, pkg/render/renderer_impl.go
* Assert the status 200 ok for the test
=> fix bulk_issue_test

pkg/controller/appsync/appsync.go
```release-note
Move appsync warning to debug level
```
=> Move appsync warnings to debug level

cmd/server/assets/admin/users/index.html, pkg/database/migrations.go, pkg/database/user.go
```release-note
Delete users who are deleted
```
=> Delete users who are deleted

docs/system-admin-guide.md
* Docs for adding ENX redirect domains
```release-note
DOCS: Add procedure for adding new ENX redirect domains.
```
=> add directions for adding redirect domains

terraform/alerting/dashboards/verification-server.yaml
* Add average latency of /api/issue to the verification dashboard
* Note: this metric includes both single and batch issue 
```release-note
Add api/issue latency to the verification dashboard
```
=> Add issue mean latency metric to dashboard

terraform/main.tf
=> Fix deprecation notice

pkg/controller/middleware/auth.go, pkg/controller/middleware/membership.go
This allows the realm id to be picked up by various metrics.
=> Save Realm into context

pkg/database/email_config_test.go, pkg/database/sms_config.go, pkg/database/sms_config_test.go
* Cover the system config, deleting configs, and validation
* Improves coverage by a whopping 1%
=> Test email/sms validation and system

internal/envstest/bootstrap.go
Oops...
```release-note
NONE
```
=> Use correct prefix

internal/envstest/bootstrap.go
=> ios != android

cmd/server/assets/realmadmin/_stats_codes.html
* Adds trendline to codes issued / cods claimed
* Adds chart control to change displayed date range
```release-note
Realm stats: Slider control to select date range to display. Trend lines are shown for codes issued and codes claimed.
```
=> add trendline to realm stats

pkg/config/cleanup_server_config.go, pkg/controller/cleanup/handle_cleanup.go, pkg/database/realm_test.go, pkg/database/signing_key.go
* cleanup for soft deleted signing keys
* 
```release-note
Garbage collection of references to deleted signing keys.
```
=> purge signing keys

terraform/service_rotation.tf
* correct permissions for rotate job
```release-note
Give rotate job permissions to admin crypto key ring
```
=> add key admin permissions to rotate job

builders/build.yaml
```release-note
Ensure bin dir exists on builds
```
=> Ensure bin dir exists

go.mod, go.sum
* Update ens dependency
```release-note
Updated exposure-notifications-sever dependency to v0.20.0
```
=> update ENS deps

pkg/database/scopes.go, tools/seed/main.go
```release-note
Make codes/stats bit of seeding optional
```
=> Make codes/stats bit of seeding optional

pkg/database/database.go
Also reduce shadowing and increase total allowed timeout to 30s.
I've noticed an increase in test flakes, likely due to the increase in test coverage and additional overhead of creating more database instances.
```release-note
Ping when opening SQL connection
```
=> Ping when opening SQL connection

docs/ens-spec.md
* define ens://onboard in the ens:// spec
* no implementation yet.
* 
```release-note
NONE
```
=> Onboarding in ens:// spec

docs/ens-spec.md
* change ens onboard to onboarding
```release-note
NONE
```
=> change onboard -> onboarding

pkg/database/vercode.go
* Followup from https://github.com/google/exposure-notifications-verification-server/pull/1638
* Fire away in the comments if we have any other nits to fix
=> Resolving nits

terraform/redirect-lb.tf
```release-note
Ensure distinct certificates on the redirect load balancer for root certificates.
```
=> Distinct certificates on load balancer

cmd/server/assets/realmadmin/_stats_codes.html, cmd/server/assets/realmadmin/_stats_tokens.html, cmd/server/assets/realmadmin/stats.html
Part of https://github.com/google/exposure-notifications-verification-server/issues/1232
```release-note
Add invalid codes and full token graphs to stats
```
=> Add invalid codes and full token graphs to stats

terraform/alerting/alerts.tf
=> Condition should contain a unit.

docs/case-worker-guide.md
=> Fix doc link

internal/i18n/locales/de/default.po, internal/i18n/locales/en/default.po, internal/i18n/locales/es/default.po, internal/i18n/locales/fr/default.po, internal/i18n/locales/it/default.po, internal/i18n/locales/ja/default.po, internal/i18n/locales/ph/default.po, internal/i18n/locales/pt/default.po, internal/i18n/locales/tr/default.po
for #1640 
* Add menu text translations (not used in this PR)
```release-note
NONE
```
=> add sms signing keys menu translations

internal/project/errors_test.go, internal/project/util_test.go
```release-note
Add more unit tests for internal/project package
```
=> Add more unit tests for internal/project package

pkg/api/api.go, pkg/api/api_test.go
Part of https://github.com/google/exposure-notifications-verification-server/issues/1399
```release-note
Add tests for api package
```
=> Add tests for api package

internal/routes/server.go, pkg/controller/admin/admin.go, pkg/controller/admin/caches.go, pkg/controller/admin/email_test.go, pkg/controller/admin/info_test.go
Part of https://github.com/google/exposure-notifications-verification-server/issues/1399
```release-note
Add some more admin tests
```
=> Add some more admin tests

cmd/server/assets/realmadmin/_stats_keyserver.html
* Publish requests by OS chart
```release-note
Show publish requests by OS
```
=> Distribution by OS

tools/seed/main.go
* Needs authapps to be created before this can succeed
=> Move stats to the end

cmd/server/assets/realmadmin/_stats_keyserver.html
=> Use gray for unknown

docs/development.md, pkg/config/admin_server_config.go, pkg/config/api_server_config.go, pkg/config/appsync_server_config.go, pkg/config/cleanup_server_config.go, pkg/config/e2e_runner_server_config.go, pkg/config/redirect_config.go, pkg/config/rotation_config.go, pkg/config/stats_puller_config.go
* Added instructions for flag guarding features
```release-note
Dev Docs: Added instructions for flag guarding features.
```
=> add docs for feature flags, make config available in all servers

cmd/server/assets/realmadmin/_stats_codes.html, cmd/server/assets/realmadmin/_stats_keyserver.html, cmd/server/assets/realmadmin/_stats_tokens.html, cmd/server/assets/realmadmin/stats.html
* The charts don't resize automatically and need to be resized with the window
* The resize event fires as the window is dragged, delay we only redraw every 300ms
=> Redraw stats charts on window resize

cmd/adminapi/main.go, cmd/server/main.go, docs/development.md, internal/envstest/adminapi.go, internal/envstest/server.go, internal/routes/adminapi.go, internal/routes/adminapi_test.go, internal/routes/server.go, internal/routes/server_test.go, pkg/config/admin_server_config.go, pkg/config/server_config.go, pkg/config/sms_signing_config.go, pkg/controller/issueapi/controller.go, pkg/controller/issueapi/gen_code_test.go, pkg/controller/issueapi/handle_issue_batch_test.go, pkg/controller/issueapi/handle_issue_test.go, pkg/controller/issueapi/issue_test.go, pkg/controller/issueapi/issueapi_test.go, pkg/controller/issueapi/send_sms_test.go, pkg/controller/issueapi/validate_code_test.go, pkg/database/realm.go, terraform/services.tf
```release-note
Create SMSSigning config and instantiate SMS signing key manager where needed
```
=> Create SMSSigning config and instantiate key manager

terraform/alerting/alerts.tf, terraform/alerting/notifications.tf, terraform/alerting/slos.tf, terraform/alerting/variables.tf
Fixes #
* Added paging and non-paging notification channels
* Specified paging alerts for SLO and latency violations
* Specified paging and non-paging alerts 
```release-note
Creates separate paging and non-paging alert mechanisms.
```
=> separating notification channels -paging and non-paging

docs/playbooks/alerts/CloudSchedulerJobFailed.md
Add newly added cloud scheduler jobs to the playbook.
=> Update CloudSchedulerJobFailed playbook.

terraform/service_cleanup.tf
```release-note
Grant cleanup service permission to manage keys for cleanup
```
=> Give cleanup permission to cleanup keys

README.md, docs/architecture.md
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1678
```release-note
Update architecture documentation
```
=> Update architecture docs

terraform/service_stats_puller.tf
* stats puller service needs KMS signer-verifier
```release-note
Gives stats puller services the correct KMS permissions.
```
=> give stats puller signer verifier

pkg/controller/statspuller/handle_pull.go
* log the error if retrieve signer fails
=> log signer error

terraform/service_cleanup.tf
```release-note
Ensure permissions are applied for cleanup service in Terraform
```
=> Ensure permissions are applied for cleanup service

internal/routes/adminapi.go
* Make the key-sever stats json available in apiserver
* CSV coming soon
=> Make key server json available over apiserver

cmd/e2e-runner/main.go, cmd/server/assets/realmadmin/_stats_keyserver.html
* I changed the json type to match key-server but now it doesn't render the intermediate 'statistics' struct
* made a cut/paste error with e2e - really wish this ran here in prow
=> Fixing some mistakes

docs/development.md, pkg/controller/issueapi/issue.go, pkg/controller/issueapi/send_sms.go, pkg/controller/issueapi/send_sms_test.go, pkg/database/realm.go, pkg/signatures/sms.go, pkg/signatures/sms_test.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1640
```release-note
Add SMS signing functionality. This functionality is off by default, as Google and Apple are still developing the necessary client-side features to support it.
```
=> Connect SMS signing functionality

pkg/database/migrations.go, pkg/database/realm_stats.go
* This column should be named correctly
* Made another migration line so we can rerun on dev
=> Fix bad column name for new stats

cmd/server/assets/realmadmin/_stats_codes.html, cmd/server/assets/realmadmin/_stats_keyserver.html, cmd/server/assets/realmadmin/stats.html, pkg/database/realm.go
* Adds a claim age chart to the statistics page
* Move the dropdown smooth page controls to be shared 
```release-note
Claim age distribution chart added to UI
```
=> Claim age charts

cmd/server/assets/realmadmin/_stats_codes.html, cmd/server/assets/realmadmin/_stats_keyserver.html, pkg/database/token.go, pkg/database/token_test.go
* Adds a test to check that the bucketing and average calculation are being saved properly
* Updates a condition with smoothing (off by one)
=> Add a unit test for issue-claim stat update

terraform/binary_authorization.tf, terraform/build.tf, terraform/database.tf, terraform/main.tf, terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_appsync.tf, terraform/service_cleanup.tf, terraform/service_e2e_runner.tf, terraform/service_modeler.tf, terraform/service_redirect.tf, terraform/service_rotation.tf, terraform/service_server.tf, terraform/service_stats_puller.tf
https://github.com/hashicorp/terraform-provider-google/issues/8326
```release-note
NONE
```
=> Use a local instead of data source

cmd/server/assets/realmadmin/_stats_keyserver.html
* fix JS copy/paste
```release-note
NONE
```
=> fix bad copy/paste

cmd/server/assets/realmadmin/_stats_codes.html, cmd/server/assets/realmadmin/_stats_keyserver.html, cmd/server/assets/realmadmin/_stats_tokens.html, cmd/server/assets/realmadmin/stats.html
* Give every chart a boostrap card
* Show download links on headers
* Float right the smoothing options
* Give each chart its own explanation
```release-note
Styling updates for statistics page & about links
```
=> Styling cards for the statistics page

cmd/server/assets/realmadmin/_stats_codes.html, cmd/server/assets/realmadmin/_stats_keyserver.html, cmd/server/assets/realmadmin/_stats_tokens.html, cmd/server/assets/realmadmin/stats.html
* Padding left/right margins for sliders
* Move the html inline (and json the id)
```release-note
padding for stats sliders
```
=> Pad and inline slider html

internal/clients/clients.go
=> Parse response as json if there's an error

terraform/alerting/module.service/variables.tf, terraform/alerting/slos.tf
=> Remove latency slo and slow burn variables

cmd/server/assets/realmadmin/_stats_keyserver.html, pkg/controller/realmadmin/stats.go
* This addresses user-feedback on clarifying these chart titles
*  I'm not certain that these are definitely clearer, but feel free to suggest
=> Feedback on chart titles

go.mod, go.sum
* Bumping key-server dep to v0.21.0 in preparation for the release cut
=> Bump key-server dep to v0.21.0

cmd/server/assets/realmadmin/_form_sms.html
```release-note
Include multiline and whitespace in search in SMS preview to fix a bug where an SMS message contained newline characters. This did not affect delivered SMSes, only the preview window.
```
=> Include multiline and whitespace in search in SMS preview

cmd/server/assets/codes/index.html, cmd/server/assets/codes/show.html, pkg/controller/codes/api.go, pkg/controller/codes/expire.go, pkg/controller/codes/expire_test.go, pkg/controller/codes/index_test.go, pkg/controller/codes/issue_test.go, pkg/controller/codes/logic.go, pkg/controller/codes/show.go, pkg/controller/codes/show_test.go
* Render code and assert expiry button is shown
* Render code + click expire + assert expiry button not shown
* Render index
```release-note
Basic coverage for /codes pages
```
=> Test render of all the code pages

pkg/controller/codes/expire_test.go, pkg/controller/codes/index.go
* This brings coverage of this package to 57%
* The remaining is all of the error cases :anguished:
=> Cover expire API

pkg/controller/codes/expire_test.go, pkg/controller/codes/logic.go, pkg/controller/codes/show.go, pkg/controller/codes/show_test.go
* Adds coverage for some of the code issue error cases
=> Cover some /codes error cases

pkg/database/config.go, pkg/database/database_util.go
=> Fix data race

terraform/service_stats_puller.tf
=> trim a whitespace

cmd/server/assets/realmadmin/_stats_keyserver.html
```release-note
minor wording fix in TEK publish metrics chart description
```
=> fixing chart description wording

builders/build.yaml, builders/deploy.yaml, builders/promote.yaml
```release-note
Upgrade to gcloud 324.0.0 in builds
```
=> Upgrade to gcloud 324.0.0 in builds

docs/api.md
* Add the JSON and CSV route for key-server stats to docs
=> Add key-server stats route to docs

cmd/server/assets/realmadmin/_form_sms.html
```release-note
Highlight when a message crosses an SMS boundary
```
=> Highlight when a message crosses an SMS boundary

pkg/ratelimit/limitware/middleware.go
```release-note
Do not produce debug logs for rate limiting facets. Do log info when a key has been rate limited. The key will be HMACed and non-identifiable, but correlatable.
```
=> Do not debug log on rate limiting, log on rate limited

terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_appsync.tf, terraform/service_cleanup.tf, terraform/service_e2e_runner.tf, terraform/service_modeler.tf, terraform/service_redirect.tf, terraform/service_rotation.tf, terraform/service_server.tf, terraform/service_stats_puller.tf
```release-note
Tune ignore_changes to prevent recurring diff in Terraform
```
=> Add ignore_changes to prevent recurring diff

terraform/README.md
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1770
* Update terraform example
=> Update example tf

terraform/alerting/alerts.tf
Set CloudSchedulerJobFailed Alert to non-paging and E2ETestErrorRatio to paging.
=> Update paging and non-paging alerts

terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_appsync.tf, terraform/service_cleanup.tf, terraform/service_e2e_runner.tf, terraform/service_modeler.tf, terraform/service_redirect.tf, terraform/service_rotation.tf, terraform/service_server.tf, terraform/service_stats_puller.tf, terraform/variables.tf
=> Add sandbox annotation

pkg/database/user_stats_test.go, pkg/database/vercode_test.go
* Run the stats queries in test to ensure properly formed SQL
=> Ensure stats queries are  run in tests

pkg/database/vercode_test.go
* Fixing a test nit
* Adds the inmemorycacher
=> scope to 'if' and include a cacher

docs/system-admin-guide.md
Issue https://github.com/google/exposure-notifications-verification-server/issues/1794
* Reference the bootstrap section of Production from system-admin-guide
=> Tweak doc with bootstrap note

cmd/server/assets/realmadmin/_stats_codes.html, cmd/server/assets/realmadmin/_stats_keyserver.html
* Specify a minimum distance for the date-range slider of 1 day
* The chart gets all funny and empty if you have < 1 day distances
=> User feedback on stats

.golangci.yaml, Makefile
```release-note
Allow parallel linting, fix missing newline in tabcheck
```
=> Allow parallel linting, fix missing newline

pkg/controller/login/session_test.go
* Adds a test for session
* Sadly it's hard to actually get a success since we use localauth to build a cookie, but this covers most of unmarshalling the form and making an attempt.
=> Add a test for session

terraform/database.tf, terraform/service_appsync.tf, terraform/service_cleanup.tf, terraform/service_e2e_runner.tf, terraform/service_modeler.tf, terraform/service_rotation.tf, terraform/service_stats_puller.tf
=> Update retry_count and database backup to synchronous

docs/api.md
* remove reference to daily request counts, we removed that code
```release-note
NONE
```
=> remove stats piece

go.mod, go.sum
=> Upgrade key server pin to v0.22.0

terraform/services.tf
```release-note
Set blobstore, key manager, and secret manager on services
```
=> Set blobstore, key manager, and secret manager on services

terraform/service_admin_apiserver.tf, terraform/service_apiserver.tf, terraform/service_appsync.tf, terraform/service_cleanup.tf, terraform/service_e2e_runner.tf, terraform/service_modeler.tf, terraform/service_redirect.tf, terraform/service_rotation.tf, terraform/service_server.tf, terraform/service_stats_puller.tf
```release-note
Ignore more annotations in Terraform diff
```
=> Ignore more annotations in Terraform diff

internal/clients/e2e.go
```release-note
Use append instead of inserting at index in e2e test
```
=> Use append instead of inserting at index

pkg/controller/form.go
```release-note
Wrap returned error from decoding form
```
=> Wrap returned error from decoding form

builders/build.yaml
```release-note
fixing path of buildinfo package for build flags
```
=> updating path of buildinfo package for build flags

internal/envstest/integration.go, pkg/controller/login/register_phone_test.go
Secrets are not available in forks.
```release-note
NONE
```
=> Only run when envvar is set

terraform/alerting/alerts.tf
```release-note
Strictify MQL for CloudSchedulerFailed
```
=> Strictify MQL

Makefile
=> Only test verification server with google tags

pkg/controller/admin/caches_test.go, pkg/controller/admin/email_test.go, pkg/controller/admin/events_test.go, pkg/controller/admin/info_test.go, pkg/controller/admin/mobile_apps_test.go, pkg/controller/admin/realms.go, pkg/controller/admin/realms_test.go, pkg/controller/admin/sms_test.go, pkg/controller/admin/users_list_test.go, pkg/controller/admin/users_operations_test.go
```release-note
Use less chromedp on admin controller tests
```
=> Use less chromedp on admin controller tests

internal/routes/adminapi.go, internal/routes/server.go, pkg/controller/admin/events_test.go, pkg/controller/codes/bulk_issue_test.go, pkg/controller/codes/controller.go, pkg/controller/codes/expire.go, pkg/controller/codes/expire_test.go, pkg/controller/codes/index.go, pkg/controller/codes/index_test.go, pkg/controller/codes/show_test.go
```release-note
Use less chromedp on codes tests
```
=> Use less chromedp on codes tests

pkg/controller/issueapi/gen_code_test.go, pkg/controller/issueapi/handle_issue_batch_test.go, pkg/controller/issueapi/handle_issue_test.go, pkg/controller/issueapi/issue_test.go, pkg/controller/issueapi/issueapi_test.go, pkg/controller/issueapi/parse_date_test.go, pkg/controller/issueapi/send_sms_test.go, pkg/controller/issueapi/validate_code_test.go, pkg/controller/login/account_test.go, pkg/controller/login/change_password_test.go, pkg/controller/login/login_test.go, pkg/controller/login/post_authenticate_test.go, pkg/controller/login/reauth_test.go, pkg/controller/login/register_phone_test.go, pkg/controller/login/reset_password_test.go, pkg/controller/login/select_password_test.go, pkg/controller/login/select_realm_test.go, pkg/controller/login/session_test.go, pkg/controller/login/signout_test.go, pkg/controller/login/verify_email_receive_test.go, pkg/controller/login/verify_email_send_test.go
```release-note
Use less chromedp in login controller
```
=> Use less chromedp in login controller

pkg/database/database_logger.go, pkg/database/database_logger_test.go
=> Capture "error" gorm output too

.github/workflows/ci.yaml, internal/i18n/i18n.go, internal/i18n/i18n_test.go
Also run the linter on all changes now that we've addressed existing issues.
```release-note
NONE
```
=> Fix updated linter issues

assets/assets.go, internal/project/util.go
This allows reloading asset files
```release-note
Do not use embedded fs in dev mode
```
=> Do not use embedded fs in dev mode

terraform/database.tf
```release-note
Enable query insights
```
=> Enable query insights

assets/server/header.html
```release-note
Update to latest bootstrap, jquery, and intlTelInput
```
=> Update to latest bootstrap, jquery, and intlTelInput

go.mod, go.sum
* Change key server dependency to v0.23.0
```release-note
NONE
```
=> bump key server dep to v23

.github/workflows/ci.yaml
=> Also run all tests at least once a day

CODEOWNERS, OWNERS
=> Update and rename OWNERS to CODEOWNERS

pkg/controller/stats/composite.go, pkg/database/authorized_app_stats_test.go, pkg/database/composite_stats.go, pkg/database/composite_stats_test.go, pkg/database/external_issuer_stats_test.go, pkg/database/realm_stats_test.go, pkg/database/realm_user_stats_test.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1889
```release-note
NONE
```
=> Add JSON tests for stats APIs

terraform/service_appsync.tf, terraform/service_modeler.tf, terraform/service_rotation.tf, terraform/service_stats_puller.tf
=> Adjust cron job schedule according to #1777

terraform/service_modeler.tf
```release-note
Remove modeler backend service (it is not public-facing).
```
=> Modeler is not a public-facing service

pkg/controller/login/reauth.go, pkg/controller/login/reauth_test.go
* Ensure redirects only go to necessary URLs post redirect
```release-note
Re-auth login redirect uses allowlist for post auth redirects.
```
=> restrict redirects to allowed paths

go.mod, go.sum
```release-note
Upgrade keyserver dependency to v0.24.0
```
=> bump keyserver dep version

pkg/controller/appsync/handle_sync.go, pkg/controller/appsync/metrics.go, pkg/controller/cleanup/handle_cleanup.go, pkg/controller/cleanup/metrics.go, pkg/controller/modeler/metrics.go, pkg/controller/modeler/modeler.go, pkg/controller/rotation/handle_token_rotate.go, pkg/controller/rotation/handle_verification_rotate.go, pkg/controller/rotation/metrics.go, pkg/controller/statspuller/handle_pull.go, pkg/controller/statspuller/metrics.go
Part of https://github.com/google/exposure-notifications-verification-server/issues/1777
```release-note
Increment metric on success for background jobs
```
=> Increment metric on success for background jobs

builders/build.yaml, builders/deploy.yaml, builders/promote.yaml, cmd/backup/main.go, docs/playbooks/alerts/ForwardProgressFailed.md, pkg/config/backup_config.go, pkg/controller/backup/backup.go, pkg/controller/backup/backup_test.go, pkg/controller/backup/handle_backup.go, pkg/controller/backup/handle_backup_test.go, pkg/controller/backup/metrics.go, terraform/alerting/variables.tf, terraform/database.tf, terraform/service_backup.tf, terraform/services.tf
Unfortunately this is required to measure forward progress.
```release-note
Introduce a new service: `backup`. Be sure to taint the null_resource builder during the Terraform apply to get the new service version.
```
=> Use an intermediate proxy for backups

.github/workflows/ci.yaml, pkg/controller/issueapi/send_sms_test.go, pkg/controller/user/create_test.go
* fix lint errors found on previous presubmit
```release-note
NONE
```
=> Address SA5011 static check findings

pkg/database/authorized_app_test.go
* fix staticcheck errors
```release-note
NONE
```
=> fix static check error

terraform/alerting/alerts.tf
```release-note
Set alignment to 1m
```
=> Set alignment to 1m

assets/server/realmadmin/_stats_keyserver.html
Towards #1928
* add sliders for graphs that didn't have them
```release-note
Add sliders to graphs for publish requests and TEKs published
```
=> add sliders to key server graphs

terraform/alerting/alerts.tf, terraform/alerting/variables.tf
```release-note
Switch to standard alerts away from MQL
```
=> Switch to standard alerts away from MQL

go.sum, pkg/controller/appsync/handle_sync.go, pkg/controller/backup/handle_backup.go, pkg/controller/cleanup/handle_cleanup.go, pkg/controller/modeler/modeler.go, pkg/controller/rotation/handle_token_rotate.go, pkg/controller/rotation/handle_verification_rotate.go, pkg/controller/statspuller/handle_pull.go, pkg/render/json.go
Also always log start and finish in debug mode
```release-note
Simplify background job error handling and response consistency.
```
=> Simplify background job error handling

terraform/alerting/alerts.tf
=> Fix copy-pasta errors

internal/i18n/locales/mn/default.po
* Adds Mongolian translations, from Google Translate
```release-note
Mongolian translations for case worker UI.
```
=> add Mongolian translations

assets/server/realmadmin/_stats_keyserver.html, pkg/controller/stats/composite.go
* fix nil ptr in composite.go
* fix series settings when self report is off
```release-note
NONE
```
=> fix os chart stack + nil ptr

cmd/e2e-runner/main.go
This reverts commit 202ccb7faafbc6516630a70b485e95749e51f679.
```release-note
Restore e2e bootstrap on container start. 
```
=> Revert "bootstrap e2e runner on first run instead of startup (#1957)"

assets/server/codes/bulk-issue.html, assets/server/codes/issue.html, assets/server/header.html, assets/server/static/css/application.css, internal/i18n/i18n.go, internal/i18n/i18n_test.go, internal/i18n/locales/ar/default.po, pkg/controller/middleware/i18n.go, terraform/verification-lb.tf
Fixes #1968 
* Arabic translations
* right aligned text
```release-note
Add Arabic translations for case worker UI.
```
=> add Arabic translations and right-aligned locale option

terraform/verification-lb.tf
* fix unintended tf change
```release-note
NONE
```
=> remove add that wasn't ready

terraform/redirect-lb.tf
```release-note
Generates specific host name matches for all ENX redirect subdomains. For anything not matching on the http port, the user set sent to an information page at g.co/ens
```
=> specific host match redirect rules for ENX redirect domains

terraform/redirect-lb.tf
=> Fix names on path matcher rules

assets/server/header.html, builders/build.yaml
Also add more build IDs to resources to help with caching
```release-note
Minify js and css assets on build.
```
=> Minify js and css assets on build

builders/build.yaml
=> Flags go on each line

builders/build.yaml, builders/deploy.yaml, builders/promote.yaml
```release-note
Upgrade to gcloud 335.0.0 in deployment scripts.
```
=> Upgrade to gcloud 335.0.0

assets/server/codes/issue.html, assets/server/header.html, assets/server/login/register-phone.html
```release-note
Use min versions of intl-tel-input script.
```
=> Use min versions of intl-tel-input

internal/project/util.go, pkg/controller/codes/issue_test.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/1995
```release-note
NONE
```
=> Retry chromedp test 3 times

assets/enx-redirect/404.html, assets/enx-redirect/header.html, assets/server/404.html, internal/i18n/locales/ar/default.po, internal/i18n/locales/de/default.po, internal/i18n/locales/en/default.po, internal/i18n/locales/es/default.po, internal/i18n/locales/fil/default.po, internal/i18n/locales/fr/default.po, internal/i18n/locales/id/default.po, internal/i18n/locales/it/default.po, internal/i18n/locales/ja/default.po, internal/i18n/locales/mn/default.po, internal/i18n/locales/pt/default.po, internal/i18n/locales/tr/default.po, internal/routes/enx_redirect.go, internal/routes/server.go, pkg/controller/context.go, pkg/controller/controller.go, pkg/render/html.go
Internationalize 404 pages too
```release-note
Mention links should be clicked on mobile devices and internationalize 404 pages.
```
=> Mention links should be clicked on mobile devices

pkg/database/realm.go
=> Fix audit logs typo

internal/i18n/locales/ar/default.po
- Fixes https://github.com/google/exposure-notifications-verification-server/issues/2007
- Fixes https://github.com/google/exposure-notifications-verification-server/issues/2008
- Fixes https://github.com/google/exposure-notifications-verification-server/issues/2009
- Fixes https://github.com/google/exposure-notifications-verification-server/issues/2010
```release-note
NONE
```
=> Incorporate translation suggestions

internal/i18n/locales/ar/default.po
Fixes https://github.com/google/exposure-notifications-verification-server/issues/2013
```release-note
NONE
```
=> Updates to arabic translations

go.mod, go.sum
=> Update key server deps

docs/production.md, terraform/keys.tf
```release-note
Lower Cloud KMS database-encrypter rotation to 90d
```
=> Lower Cloud KMS database-encrypter rotation to 90d

pkg/database/database_logger.go
```release-note
Handle string or log in gorm log type.
```
=> Handle string or log in gorm log type

assets/server/mobileapps/show.html, pkg/render/renderer.go
```release-note
Unescape mobile app paths in UI.
```
=> Unescape mobile app paths in UI

assets/server/login/verify-email.html
```release-note
Do not run email verification javascript until after load. This fixes an issue where users may be unable to verify their email address.
```
=> Do not run email verification js until after load

assets/server/firebase.html
The MFA page expects this cookie to exist.
```release-note
NONE
```
=> Persist Firebase cookie for the session duration

terraform/sessions.tf
* fix missing id tag
```release-note
NONE
```
=> missing ID tag

terraform/service_rotation.tf
This is included in the other PR, but that may take some time to get reviewed and at HEAD.
```release-note
NONE
```
=> Fix permissions on rotation service

internal/envstest/bootstrap.go
=> Annotate why realm saving failed

internal/envstest/bootstrap.go, pkg/database/realm.go
=> Remove spaces after column definition

assets/server/admin/info.html, go.mod, go.sum, pkg/controller/admin/info.go
```release-note
Display feature statuses on system admin info page.
```
=> Display feature statuses on system admin info page

go.mod, go.sum
=> Bump key server dep

assets/enx-redirect/report/index.html, internal/routes/enx_redirect.go, pkg/controller/issueapi/parse_date.go, pkg/controller/middleware/sessions.go, pkg/controller/userreport/controller.go, pkg/controller/userreport/index.go, pkg/controller/userreport/send.go
Towards #1928 
* Handle error messages on user report form
```release-note
Handle and display error messages on the user-report webview form.
```
=> error handling for user report

internal/routes/enx_redirect.go, pkg/config/redirect_config.go
* for dev server so we can demo the web view
```release-note
NONE
```
=> separate flag for allow user report get

internal/i18n/locales/bn/default.po
```release-note
Adds translations for Bengali, bn.
```
=> add translations for bengali

assets/enx-redirect/report/index.html
Towards #1928 
* product requested string changes
```release-note
Update user report webview strings.
```
=> user report strings update

go.mod, go.sum
* move to pre v0.28 version of ENS dependency
```release-note
NONE
```
=> unpin ens dependency

pkg/config/feature_config.go
* enable user report feature by default
* 
```release-note
User report feature is now enabled by default.
```
=> enable user report by default

go.mod, go.sum
```release-note
Upgrade to latest exposure-notifications-server release
```
=> upgrade ens dep

assets/server/apikeys/index.html, assets/server/apikeys/show.html, assets/server/realmadmin/_form_codes.html, cmd/e2e-runner/main.go, internal/envstest/enx_redirect.go, internal/routes/apiserver.go, internal/routes/enx_redirect.go, pkg/config/feature_config.go, pkg/controller/associated/index_test.go, pkg/controller/realmadmin/settings_modify.go, pkg/controller/userreport/index_test.go
Fixes #2074 
* remove feature flags
```release-note
Removes all current feature flags. Where applicable, features are still controlled at a realm level.
```
=> Remove feature flags in prep for 1.0 release

assets/server/admin/realms/index.html, assets/server/realmadmin/_form_codes.html
* phone number notice on enabling user report
* show realms w/ user report enabled
*
```release-note
Show which realms have user report enabled on system admin realm listing.
```
=> show which realms have user report enabled.

assets/enx-redirect/report/issue.html, internal/routes/enx_redirect.go, pkg/controller/userreport/send.go
```release-note
Send signal to close webview window on iOS when user report is complete.
```
=> send signal to close window when user report done

internal/routes/enx_redirect.go
=> Only create the filesystem server once

.github/workflows/ci.yaml, .golangci.yaml, assets/server/admin/realms/edit.html, assets/server/realmadmin/_form_codes.html, docs/api.md, docs/playbooks/alerts/UserReportWebhookError.md, pkg/api/api.go, pkg/controller/admin/realms.go, pkg/controller/issueapi/handle_issue_test.go, pkg/controller/issueapi/issue.go, pkg/controller/issueapi/issueapi_test.go, pkg/controller/issueapi/phone.go, pkg/controller/issueapi/send_sms.go, pkg/controller/issueapi/validate_code.go, pkg/controller/issueapi/validate_code_test.go, pkg/controller/realmadmin/settings_modify.go, pkg/controller/userreport/controller.go, pkg/controller/userreport/index.go, pkg/controller/userreport/metrics.go, pkg/controller/userreport/send.go, pkg/controller/userreport/send_test.go, pkg/database/database.go, pkg/database/migrations.go, pkg/database/realm.go, pkg/database/realm_test.go, terraform/alerting/alerts.tf, tools/seed/main.go
```release-note
Introduce new optional fields to the `/issue` API for requesting the generated SMS message. This feature must be enabled on a per-realm basis.
```
=> Merge experimental

pkg/controller/userreport/send.go, pkg/controller/userreport/send_test.go
=> Marshal the response, not the interim structure

docs/api.md
=> Add phone field to API docs

terraform/alerting/alerts.tf
=> Express as a rate

pkg/controller/userreport/send.go
=> Only send webhooks on successful backend responses

assets/server/login/change-password.html
* This code includes the same auth checks as login which may lead to a missing captcha block
* We might separate the js so that this doesn't require the captcha, but this is the lowest-risk thing to avoid errors
=> Include captcha div on password-change

assets/server/admin/sms/show.html, assets/server/apikeys/show.html, assets/server/codes/index.html, assets/server/codes/show.html, assets/server/header.html, assets/server/login/change-password.html, assets/server/login/verify-email.html, assets/server/realmadmin/_form_abuse_prevention.html, assets/server/realmadmin/_form_security.html, assets/server/realmadmin/keys.html, assets/server/realmadmin/smskeys.html, assets/server/static/js/application.js, assets/server/users/_form.html, assets/server/users/index.html, assets/server/users/show.html, tools/seed/main.go
=> Remove some unnecessary jquery use

go.mod, go.sum
* upgrade exposure-notifications-server dependency
```release-note
NONE
```
=> upgrade ENS dep to v0.29.0

internal/clients/app_sync.go, pkg/config/appsync_server_config.go, pkg/controller/appsync/handle_sync_test.go
Towards #2102
* add fields for localization sync from Google feed
* increase body size for app sync to accommodate
```release-note
Introduce data structures to sync localization strings synced from the Google feed.
```
=> Sync localizations

assets/server/apikeys/show.html, assets/server/login/select-password.html, assets/server/mobileapps/_app.html, assets/server/realmadmin/_stats_external_issuers.html, assets/server/realmadmin/_stats_users.html, assets/server/realmadmin/edit.html
Continuing work on this piece by piece.
```release-note
NONE
```
=> Remove some more jquery in favor of plain javascript

internal/appsync/app_sync.go, internal/clients/app_sync.go, pkg/controller/appsync/handle_sync_test.go, pkg/controller/appsync/helpers.go, pkg/controller/appsync/helpers_test.go, pkg/database/dynamic_translation.go, pkg/database/dynamic_translation_test.go, pkg/database/migrations.go, pkg/database/realm.go
Towards #2102
* add per-realm localization sync method
* attach to app sync job
* refactor data structures to remove circular dependency
```release-note
Sync and store per-realm localization strings as part of the appsync process.
```
=> start syncing translations

pkg/controller/admin/caches.go
* Add clear cache option for translations
```release-note
none
```
=> add translations cache clear

assets/server/realmadmin/_form_codes.html, internal/envstest/enx_redirect.go, internal/routes/enx_redirect.go, internal/routes/enx_redirect_test.go, internal/routes/routes_test.go, pkg/config/feature_config.go, pkg/controller/realmadmin/settings_modify.go, pkg/controller/userreport/index_test.go, pkg/database/migrations.go, pkg/database/realm.go
* user report web view is a realm setting now
* remove system feature flag for this
```release-note
User report web view moves from system setting to realm setting.
```
=> Make user report web view a realm setting

pkg/controller/userreport/index.go, pkg/controller/userreport/index_test.go, pkg/database/migrations.go
* fix migration
* use user report web setting
```release-note
Make use of all user report web setting
```
=> Make use of realm web setting for user report

assets/server/admin/realms/edit.html, assets/server/admin/realms/index.html
```release-note
System admin realm overview shows user report web view status per realm.
```
=> display user report web view on sys admin overview

assets/server/mobileapps/show.html
* minor string change
```release-note
NONE
```
=> change display of headless ENX apps in mobile apps display

assets/enx-redirect/report/index.html
=> Remove placeholder from "date" fields, fix ID

pkg/controller/middleware/chaff.go
This mitigates a (very rare) edge case where a chaff request came in near a UTC boundary. In that case, it's possible that the Cloud Run instance throttled CPU to 0 between when the go routine was scheduled and when it executed. Since "now" was relative to when the go routine executed, this could result in incrementing the statistic for the wrong UTC day. In practice, this wouldn't matter because you'd have more than one chaff event per each day.
```release-note
Fix an issue where a realm chaff event might be recorded for the wrong date.
```
=> Capture time during call to record chaff events

docs/images/architecture/go.sum, go.mod, go.sum, pkg/controller/certapi/certapi.go, pkg/controller/certapi/certificate.go, pkg/controller/statspuller/handle_pull.go, pkg/controller/verifyapi/verify.go, pkg/jwthelper/jwthelper.go
Signed-off-by: Mike Helmick <helmick@google.com>
Fixes #2128
* upgrade JWT library
```release-note
Migrate from unsupported JWT library to supported JWT library
```
=> upgrade JWT library

docs/api.md
* fix documentation
```release-note
Remove platform field from user-report API documentation.
```
=> remove platform from user report request fields in doc

internal/appsync/app_sync.go, pkg/controller/appsync/helpers.go, pkg/controller/appsync/helpers_test.go
Fixes #2102 
* sync learn more URL
```release-note
Syncs web report learn more URL from the Google ENX application feed.
```
=> sync web report learn more url from google feed

assets/server/realmadmin/_form_codes.html
Fixed wording
```release-note
NONE
```
=> Wording fix

assets/enx-redirect/report/index.html
* change learn more target for iOS
```release-note
NONE
```
=> change learn more target to blank

pkg/render/csv.go, pkg/render/html.go, pkg/render/json.go
```release-note
Print a log message at the error level when html/json/csv fails to marshal.
```
=> Log when html/json/csv fails to marshal

assets/enx-redirect/header.html, assets/enx-redirect/report/header.html, assets/server/codes/issue.html, assets/server/header.html, pkg/controller/middleware/csrf.go
Some small things I noticed while working on something else.
```release-note
NONE
```
=> Fix some HTML validation errors

internal/i18n/locales/es/default.po
* missed one...
```release-note
NONE
```
=> missed Spanish translation

assets/server/static/js/__poly.js, assets/server/static/js/_flash.js
Our current transpiler doesn't support private methods yet
```release-note
NONE
```
=> Don't use private javascript methods

terraform/build.tf
=> Expire build cache after 7 days

assets/server/admin/events/index.html, assets/server/admin/mobileapps/index.html, assets/server/admin/realms/index.html, assets/server/admin/users/index.html, assets/server/mobileapps/_app.html, assets/server/mobileapps/show.html, assets/server/realmadmin/events.html, pkg/database/mobile_app.go
Fixes a few things I noticed while clicking around on dev.
```release-note
NONE
```
=> Fix some remaining bootstrap items and  fix a js error

assets/server/codes/issue.html
=> Upgrade issue UI

assets/server/realmadmin/_form_sms.html
=> Remove extra >

pkg/controller/modeler/modeler.go
=> Return validation error messages in modeler

pkg/render/assets.go
```release-note
Fix an issue where javascript and stylesheets would not load on Firefox.
```
=> Use std base64 encoding on SRI calculation

assets/enx-redirect/report/index.html
```release-note
On the user report webview, disable the submit button after press
```
=> disable button on issue request

go.mod, go.sum
* rev to latest keyserver release
```release-note
NONE
```
=> bump keyserver version

assets/enx-redirect/report/issue.html
* fixes rounded corners and spacing on user report success page
```release-note
NONE
```
=> fix success style

pkg/controller/appsync/helpers.go
```release-note
App sync - all Android ENX apps will use picker when imported.
```
=> change app sync for redirect

assets/server/static/js/application.js
```release-note
Only prompt the user to select the MFA device when more than one device is registered.
```
=> Do not display factors list when there's only one factor

docs/api.md
```release-note
Add user-report example to /api/verify documentation
```
=> add user-report to api doc

assets/server/login/register-phone.html, assets/server/static/js/register-phone.js
```release-note
Fix an issue with the client-side javascript when registering a new MFA device.
```
=> Fix MFA registration javascript

assets/enx-redirect/report/header.html, assets/enx-redirect/report/index.html, assets/enx-redirect/report/invalid.html
```release-note
CSS Tweaks for user report webview.
```
=> CSS changes for user report

assets/enx-redirect/report/header.html
* CSS tweaks for user report web view
```release-note
NONE
```
=> user report css adjustments

pkg/database/key_server_stats.go
* Use same project.StatsDisplayDays for key server stats listing
```release-note
Fix issue where key server stats used different display window from other stats
```
=> use project constant for key server stats listing

terraform/service_apiserver.tf
```release-note
Fixes the apiserver terraform config to include the code issue config, required for user-initiated report.
```
=> add issue config to apiserver for user report

.github/workflows/ci.yaml, .golangci.yaml, Makefile, builders/build.yaml, internal/buildinfo/buildinfo.go, pkg/controller/redirect/index.go, pkg/database/user.go, pkg/render/renderer.go, pkg/sms/noop.go
=> Fix dockerfile path

builders/build.yaml
=> Pass in service name

pkg/controller/issueapi/handle_issue.go
```release-note
Admin API user-report code request where the phone number is not eligible, returns success. Other avenues, like web view and device report already work this way.
```
=> user report success on admin api

pkg/database/realm_stats.go
=> Fix misleading code comments

pkg/database/bulk_permission.go, pkg/database/bulk_permission_test.go
```release-note
Automatically remove a user from a realm if all their permissions on that realm have been removed through bulk permission management.
```
=> Remove users when all permissions are removed

pkg/controller/userreport/send_test.go
=> Clean up some TODOs

go.mod, go.sum
* Updating deps to point at the new v0.37.0 release of key-server
=> Update verification server deps to new key-server release

internal/i18n/locales/redirect/my/default.po
Sample
```release-note
Adds Burmese user report webview translations
```
=> Add Burmese (my) translations for user report

docs/realm-admin-guide.md
```release-note
Add more documentation for SMS error statistics.
```
=> Add SMS errors statistics docs

pkg/controller/cleanup/handle_cleanup_test.go, pkg/controller/issueapi/gen_code.go, pkg/controller/issueapi/gen_code_test.go, pkg/controller/issueapi/issueapi_test.go, pkg/database/migrations.go, pkg/database/vercode.go, pkg/database/vercode_test.go
=> Add FK constraints on verification codes

pkg/controller/cleanup/handle_cleanup_test.go, pkg/controller/issueapi/gen_code.go, pkg/controller/issueapi/gen_code_test.go, pkg/controller/issueapi/issueapi_test.go, pkg/database/migrations.go, pkg/database/vercode.go, pkg/database/vercode_test.go
Reverts google/exposure-notifications-verification-server#2265
Going to revert this and take another stab in the original PR
=> Revert "Add FK constraints on verification codes"

tools/seed/main.go
This still isn't perfect (~1min), but it dramatically reduces the amount
of time it takes to seed with stats.
```release-note
NONE
```
=> Dramatically reduce seed time with stats

pkg/database/authorized_app.go, pkg/database/errors.go, pkg/database/membership.go, pkg/database/mobile_app.go, pkg/database/realm.go, pkg/database/secret.go, pkg/database/token_signing_keys.go, pkg/database/user.go, pkg/database/vercode.go
=> Return a common error when Auditable actor is missing

assets/server/admin/user-report/index.html, internal/routes/server.go, pkg/controller/admin/user_report.go, pkg/controller/admin/user_report_test.go, pkg/database/user_report.go, pkg/database/user_report_test.go, pkg/database/vercode.go, pkg/database/vercode_test.go
=> Clean up some edge cases in user report phone purging

internal/i18n/locales/redirect/af/default.po, internal/i18n/locales/redirect/zu/default.po
```release-note
Adds user report translations for AF and ZU.
```
=> add af and zu translations

go.mod, go.sum
* upgrade exposure-notificaitons-server dependency
```release-note
NONE
```
=> upgrade ens dep to v1.2.0

builders/build.yaml, builders/deploy.yaml, builders/promote.yaml
=> Bump gcloud version in build

internal/i18n/locales/redirect/ps/default.po
```release-note
Add user report translations for PS.
```
=> add PS translations

internal/clients/clients.go
=> Use structured logs

internal/routes/enx_redirect.go, pkg/config/redirect_config.go
```release-note
Add user report debug option for development environments.
```
=> add query param debug option

terraform/build.tf, terraform/database.tf
* typo in dependencies block googleaips -> googleapis
```release-note
NONE
```
=> fix googleaips -> googleapis typo

assets/server/realmadmin/_stats_codes.html, docs/realm-admin-guide.md
```release-note
Add explanation for possible delta in token claim / publish rate due to iOS user-report behavior
```
=> Add explanation for possible delta in token claim / publish rate

docs/production.md, terraform/alerting/alerts.tf, terraform/alerting/variables.tf
=> Fix small emailer issues

pkg/database/migrations.go, pkg/database/sms_config.go
Fixes https://github.com/google/exposure-notifications-verification-server/issues/2314
```release-note
NONE
```
=> Update sms_config column types to text

assets/server/email/sms_errors.txt
=> s/server operator/Twilio account owner

assets/server/email/anomalies.txt, assets/server/email/sms_errors.txt, assets/server/realmadmin/_form_general.html, docs/production.md, pkg/config/emailer_config.go, pkg/controller/emailer/emailer.go, pkg/controller/emailer/handle_anomalies.go, pkg/controller/emailer/handle_anomalies_test.go, pkg/controller/emailer/handle_sms_errors.go, pkg/controller/emailer/handle_sms_errors_test.go
=> Send a single email to multiple recipients

pkg/database/realm.go
Still testing
```release-note
Fix a bug with the sms anomalies emailer where it may fail after the first run.
```
=> Copy slice before modifying

pkg/controller/emailer/emailer.go, pkg/controller/emailer/handle_anomalies.go, pkg/controller/emailer/handle_sms_errors.go
```release-note
Fix an issue where CC and BCC recipients were not included in the email envelope for system alerts.
```
=> Ensure all recipients are included in the RCPT call

internal/routes/server.go
```release-note
Security related headers are applied to /static/ serving as well as main web contect.
```
=> apply secure headers to static assets

assets/server/login/_loginscripts.html, assets/server/login/login.html, docs/development.md
```release-note
Disable spellchecking and autocorrect on login fields.
```
=> Fix development guide and disable spellcheck on login fields

assets/server/static/js/stats-codes.js, assets/server/static/js/stats-keyserver.js
```release-note
Fixes a bug in chart smoothing on stats page.
```
=> fix chart smoothing

pkg/controller/codes/bulk_issue.go, pkg/controller/codes/controller.go, pkg/controller/codes/index.go, pkg/controller/codes/issue.go, pkg/controller/issueapi/handle_issue.go, pkg/controller/middleware/membership.go
=> Switch to middleware for realm maintenance mode

assets/server/firebase.html
```release-note
Upgrades firebase javascript version.
```
=> upgrade firebase javascript

.golangci.yaml, pkg/controller/codes/show.go, pkg/controller/middleware/membership.go
Fixes GH-2344
```release-note
Switch to newer function for making strings titlecase.
```
=> Remove deprecated strings.Title function

pkg/jwthelper/jethelper_test.go, pkg/jwthelper/jwthelper.go
* Remove unnecessary key size calculation
```release-note
NONE
```
=> remove unnecessary code and increase test coverage

pkg/controller/verifyapi/verify.go, pkg/database/token.go
* Add the ability for additional debug logging for the verify API flow
* We are getting sporadic reports of invalid code errors on devices in situations where it is not expected, temporarily enabling debug logging can help diagnose these errors and determine best resolution
```release-note
For operators: ability to get extended error information on why verification codes fail to claim when debug logging is enabled.
```
=> add additinal logging for debugging verification code failures

assets/server/realmadmin/_stats_keyserver.html
```release-note
Adds clarification to keyserver stats help text on realm admin statistics page.
```
=> add clarity to keyserver stats help

pkg/database/realm.go
=> Fix error message

assets/enx-redirect/header.html, assets/enx-redirect/report/header.html, assets/server/header.html
This one isn't quite as big as the key server because we were already on the 5.2 beta.
```release-note
NONE
```
=> Upgrade bootstrap and intl-tel-input

go.mod, go.sum
* Pin dep to our other repo now that the release is available. 
```release-note
NONE
```
=> pin en server dep

docs/system-admin-guide.md
* instructions for system turn down for operators.
```release-note
NONE
```
=> system turndown first pass

README.md
* Add archive notice
```release-note
NONE
```
=> add archive notice
